### PR TITLE
Adding load_model param to training API /model/train to load the model after training.

### PR DESCRIPTION
**Pull request by dingusagar**
**Proposed changes**:
A new request param : load_model is added to the model training http API (/model/train). If load_model is set to true, the trained model will be loaded to the agent.  

Linked issue #4163 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @JustinaPetr will take a look at it as soon as possible ✨

**Review by ancalita — COMMENTED** [review]
@dingusagar Could you please offer more insight into why you need this amendment into this particular endpoint? Rasa HTTP API already offers `PUT /model` for the purpose of loading a model.

**Comment by danjacob12** [comment]
hi @ancalita ,
so this PR was raised sometime back from this issue https://github.com/RasaHQ/rasa/issues/4163.
I found it on the issues board while trying to do small open source contributions. 

I think it's just for convenience, to train and load the model in a single API. Also, there were discussions about PUT not being the correct HTTP method for this task. please check the discussions. 

Actually, I haven't been keeping track of the latest rasa codebase, so if this feature doesn't make much sense now, feel free to close this PR.

**Comment by ancalita** [comment]
@dingusagar Thank you for providing more context here. 
After discussing with our squad product manager, we decided to create a ticket for the implementation of a new endpoint `POST /model` to have the responsibility of loading a model. I'll therefore close this PR.

**Pull request closed without merging**
