### PR TITLE
Bump boto3, matplotlib, jsonpickle, tqdm and rocketchat-api

### PR DESCRIPTION
**Pull request by rasabot**
Bumps [boto3](https://github.com/boto/boto3), [matplotlib](https://github.com/matplotlib/matplotlib), [jsonpickle](https://github.com/jsonpickle/jsonpickle), [tqdm](https://github.com/tqdm/tqdm) and [rocketchat-api](https://github.com/jadolg/rocketchat_API).
Updates `boto3` from 1.16.60 to 1.17.5
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/boto/boto3/blob/develop/CHANGELOG.rst">boto3's changelog</a>.</em></p>
<blockquote>
<h1>1.17.5</h1>
<ul>
<li>api-change:<code>quicksight</code>: [<code>botocore</code>] Update quicksight client to latest version</li>
<li>api-change:<code>mediaconvert</code>: [<code>botocore</code>] Update mediaconvert client to latest version</li>
<li>api-change:<code>qldb-session</code>: [<code>botocore</code>] Update qldb-session client to latest version</li>
<li>api-change:<code>sagemaker</code>: [<code>botocore</code>] Update sagemaker client to latest version</li>
<li>api-change:<code>gamelift</code>: [<code>botocore</code>] Update gamelift client to latest version</li>
</ul>
<h1>1.17.4</h1>
<ul>
<li>api-change:<code>dataexchange</code>: [<code>botocore</code>] Update dataexchange client to latest version</li>
<li>api-change:<code>cloudtrail</code>: [<code>botocore</code>] Update cloudtrail client to latest version</li>
<li>api-change:<code>elbv2</code>: [<code>botocore</code>] Update elbv2 client to latest version</li>
<li>api-change:<code>ivs</code>: [<code>botocore</code>] Update ivs client to latest version</li>
<li>api-change:<code>macie2</code>: [<code>botocore</code>] Update macie2 client to latest version</li>
<li>api-change:<code>globalaccelerator</code>: [<code>botocore</code>] Update globalaccelerator client to latest version</li>
<li>api-change:<code>iotsitewise</code>: [<code>botocore</code>] Update iotsitewise client to latest version</li>
<li>api-change:<code>elasticache</code>: [<code>botocore</code>] Update elasticache client to latest version</li>
</ul>
<h1>1.17.3</h1>
<ul>
<li>api-change:<code>macie</code>: [<code>botocore</code>] Update macie client to latest version</li>
<li>api-change:<code>elbv2</code>: [<code>botocore</code>] Update elbv2 client to latest version</li>
<li>api-change:<code>organizations</code>: [<code>botocore</code>] Update organizations client to latest version</li>
</ul>
<h1>1.17.2</h1>
<ul>
<li>api-change:<code>quicksight</code>: [<code>botocore</code>] Update quicksight client to latest version</li>
<li>api-change:<code>appflow</code>: [<code>botocore</code>] Update appflow client to latest version</li>
<li>api-change:<code>emr-containers</code>: [<code>botocore</code>] Update emr-containers client to latest version</li>
<li>api-change:<code>dlm</code>: [<code>botocore</code>] Update dlm client to latest version</li>
<li>api-change:<code>athena</code>: [<code>botocore</code>] Update athena client to latest version</li>
<li>api-change:<code>ec2</code>: [<code>botocore</code>] Update ec2 client to latest version</li>
</ul>
<h1>1.17.1</h1>
<ul>
<li>api-change:<code>lambda</code>: [<code>botocore</code>] Update lambda client to latest version</li>
<li>api-change:<code>codebuild</code>: [<code>botocore</code>] Update codebuild client to latest version</li>
<li>api-change:<code>ec2</code>: [<code>botocore</code>] Update ec2 client to latest version</li>
<li>api-change:<code>ce</code>: [<code>botocore</code>] Update ce client to latest version</li>
<li>api-change:<code>databrew</code>: [<code>botocore</code>] Update databrew client to latest version</li>
</ul>

</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/boto/boto3/commit/d753f9fb5b5946c1cd81d99c35649f5831078496"><code>d753f9f</code></a> Merge branch 'release-1.17.5'</li>
<li><a href="https://github.com/boto/boto3/commit/f56bd466588d7da356983dd8330150bee2807021"><code>f56bd46</code></a> Bumping version to 1.17.5</li>
<li><a href="https://github.com/boto/boto3/commit/44e8347394e36405c751f18c4733a4f24b3c9909"><code>44e8347</code></a> Add changelog entries from botocore</li>
<li><a href="https://github.com/boto/boto3/commit/e3282273d0c79ea6e60bd1a764e8a6efe8956c9d"><code>e328227</code></a> Merge branch 'release-1.17.4'</li>
<li><a href="https://github.com/boto/boto3/commit/aef57a9094420e2db104475ee4f853acab2c8acf"><code>aef57a9</code></a> Merge branch 'release-1.17.4' into develop</li>
<li><a href="https://github.com/boto/boto3/commit/1a8fdf8ab1ade80da96d30647d81fb6b9b28cafa"><code>1a8fdf8</code></a> Bumping version to 1.17.4</li>
<li><a href="https://github.com/boto/boto3/commit/66d6f3d4edeb350199e35a32a13fa161cc86d8d4"><code>66d6f3d</code></a> Add changelog entries from botocore</li>
<li><a href="https://github.com/boto/boto3/commit/727c7c9a9714219d2525f1eb00f834f9ac8c0e84"><code>727c7c9</code></a> Merge branch 'release-1.17.3'</li>
<li><a href="https://github.com/boto/boto3/commit/bf5d4dd01f6c86ab096e8ad45849039e721a9024"><code>bf5d4dd</code></a> Merge branch 'release-1.17.3' into develop</li>
<li><a href="https://github.com/boto/boto3/commit/d87be8177e75232b83dbd32afba149fd375896ef"><code>d87be81</code></a> Bumping version to 1.17.3</li>
<li>Additional commits viewable in <a href="https://github.com/boto/boto3/compare/1.16.60...1.17.5">compare view</a></li>
</ul>
</details>
<br />

Updates `matplotlib` from 3.3.3 to 3.3.4
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/matplotlib/matplotlib/releases">matplotlib's releases</a>.</em></p>
<blockquote>
<h2>REL: v3.3.4</h2>
<p>This is the fourth bugfix release of the 3.3.x series.</p>
<p>This release contains several critical bug-fixes:</p>
<ul>
<li>Fix WebAgg initialization.</li>
<li>Fix parsing <code>QT_API</code> setting with mixed case.</li>
<li>Fix build with link-time optimization disabled in environment.</li>
<li>Fix test compatibility with NumPy 1.20.</li>
<li>Fix test compatibility with pytest 6.2.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/matplotlib/matplotlib/commit/396e8c72b132f9a659d6f86388da6b40275b9290"><code>396e8c7</code></a> REL: v3.3.4</li>
<li><a href="https://github.com/matplotlib/matplotlib/commit/188a6fb3b058fa0ce90dc5329bd9dc028cc198d0"><code>188a6fb</code></a> Merge branch 'v3.3.3-doc' into v3.3.x</li>
<li><a href="https://github.com/matplotlib/matplotlib/commit/6adafceb03ccadbdb77c921bd4dd0ebe3615269f"><code>6adafce</code></a> DOC: Update GitHub stats for 3.3.3.</li>
<li><a href="https://github.com/matplotlib/matplotlib/commit/bae33a073910e2ca27d455de0a0aacfff0b8365e"><code>bae33a0</code></a> Merge pull request <a href="https://github-redirect.dependabot.com/matplotlib/matplotlib/issues/19386">#19386</a> from meeseeksmachine/auto-backport-of-pr-19238-on-v...</li>
<li><a href="https://github.com/matplotlib/matplotlib/commit/81305b4d1e9accbf3deafd8e127fefc467cfc99d"><code>81305b4</code></a> Backport PR <a href="https://github-redirect.dependabot.com/matplotlib/matplotlib/issues/19238">#19238</a>: Fix build with LTO disabled in environment</li>
<li><a href="https://github.com/matplotlib/matplotlib/commit/db5b330bc93315b04353d963095526d06c14fd33"><code>db5b330</code></a> Merge pull request <a href="https://github-redirect.dependabot.com/matplotlib/matplotlib/issues/19382">#19382</a> from meeseeksmachine/auto-backport-of-pr-19052-on-v...</li>
<li><a href="https://github.com/matplotlib/matplotlib/commit/491c95773ff7091ef176a2050fcab251d0cc7361"><code>491c957</code></a> Backport PR <a href="https://github-redirect.dependabot.com/matplotlib/matplotlib/issues/19052">#19052</a>: Always pass integers to wx.Size.</li>
<li><a href="https://github.com/matplotlib/matplotlib/commit/d262e5353fce86e99ef96279cc08a3c76b1d7c8a"><code>d262e53</code></a> Merge pull request <a href="https://github-redirect.dependabot.com/matplotlib/matplotlib/issues/19377">#19377</a> from meeseeksmachine/auto-backport-of-pr-19371-on-v...</li>
<li><a href="https://github.com/matplotlib/matplotlib/commit/638165699d98a6c74f27c94df62a8a799ba5d859"><code>6381656</code></a> Backport PR <a href="https://github-redirect.dependabot.com/matplotlib/matplotlib/issues/19371">#19371</a>: Fix specgram test on NumPy 1.20.</li>
<li><a href="https://github.com/matplotlib/matplotlib/commit/a9ff466ff440c58b2912343550dabf08792014aa"><code>a9ff466</code></a> Merge pull request <a href="https://github-redirect.dependabot.com/matplotlib/matplotlib/issues/19305">#19305</a> from QuLogic/auto-backport-of-pr-19301-on-v3.3.x</li>
<li>Additional commits viewable in <a href="https://github.com/matplotlib/matplotlib/compare/v3.3.3...v3.3.4">compare view</a></li>
</ul>
</details>
<br />

Updates `jsonpickle` from 1.5.0 to 2.0.0
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/jsonpickle/jsonpickle/blob/master/CHANGES.rst">jsonpickle's changelog</a>.</em></p>
<blockquote>
<h1>v2.0.0</h1>
<pre><code>* Major release: the serialized JSON format now preserves dictionary
  identity, which is a subtle change in the serialized format.  ([#351](https://github.com/jsonpickle/jsonpickle/issues/351))
* Dictionary identity is now preserved.  For example, if the same
  dictionary appears twice in a list, the reconstituted list
  will now contain two references to the same dictionary.  ([#255](https://github.com/jsonpickle/jsonpickle/issues/255)) (+332)
</code></pre>
<h1>v1.5.2</h1>
<pre><code>* Patch release to avoid the change in behavior from the preservation
  of dict identity.  The next release will be v2.0.0.  ([#351](https://github.com/jsonpickle/jsonpickle/issues/351))
* This relese does *not* include the performance improvements
  from v1.5.1.
* Pandas DataFrame objects with multilevel columns are now supported.
  ([#346](https://github.com/jsonpickle/jsonpickle/issues/346)) (+347)
* Numpy 1.20 is now officially supported.  ([#336](https://github.com/jsonpickle/jsonpickle/issues/336))
* Python 3.9 is now officially supported.  (+348)
* Achieved a small speedup for _get_flattener by merging type checks. (+349)
</code></pre>
<h1>v1.5.1</h1>
<pre><code>* The performance of the unpickler was drastically improved by
  avoiding tag checks for basic Python types.  (+340)
* ``decode()`` documentation improvements.  (+341)
* Serialization of Pandas DataFrame objects that contain
  timedelta64[ns] dtypes are now supported.  (+330) ([#331](https://github.com/jsonpickle/jsonpickle/issues/331))
* Dictionary identity is now preserved.  For example, if the same
  dictionary appears twice in a list, the reconstituted list
  will now contain two references to the same dictionary.  ([#255](https://github.com/jsonpickle/jsonpickle/issues/255)) (+332)
* Unit tests were added to ensure that sklearn.tree.DecisionTreeClassifier
  objects are properly serialized.  ([#155](https://github.com/jsonpickle/jsonpickle/issues/155)) (+344)
* The ``is_reducible()`` utility function used by ``encode()`` is now
  4x faster!  Objects that provide ``__getstate__()``, ``__setstate__()``,
  and ``__slots__`` benefit most from these improvements.  (+343)
* Improved pickler ``flatten()/encode()`` performance.  (+345)
</code></pre>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/jsonpickle/jsonpickle/commit/6ef91dfb3e930f0fd8342f6f258ea1f502262ee0"><code>6ef91df</code></a> jsonpickle v2.0.0: preserve dictionary identity</li>
<li><a href="https://github.com/jsonpickle/jsonpickle/commit/38751c87d5ff0013756318bf2a64b2891520328b"><code>38751c8</code></a> CHANGES.rst: the next patch release is v1.5.2</li>
<li><a href="https://github.com/jsonpickle/jsonpickle/commit/474f5a736a246875e35f90925d122ab80a28aed2"><code>474f5a7</code></a> Revert &quot;serialization: preserve dictionary identity when un/pickling&quot;</li>
<li><a href="https://github.com/jsonpickle/jsonpickle/commit/4e250e69780de45c45b4f8c1cfb8de8a61b25156"><code>4e250e6</code></a> CHANGES: prepare for v1.5.3</li>
<li><a href="https://github.com/jsonpickle/jsonpickle/commit/c77def90a18e23d298d28e250a09fa8db5795d43"><code>c77def9</code></a> github: add sponsorshop details</li>
<li><a href="https://github.com/jsonpickle/jsonpickle/commit/09e02a240bd48d0597bbc1a15b6b96fa61a6f243"><code>09e02a2</code></a> tox: avoid yajl on python &lt; 3.8</li>
<li><a href="https://github.com/jsonpickle/jsonpickle/commit/24cefabb2107baca17c37e45ad8e557e0617c2df"><code>24cefab</code></a> tox: revamp coverage setup</li>
<li><a href="https://github.com/jsonpickle/jsonpickle/commit/fa383acb2ae6ad2aa658502e9a2f17bcc96e59a9"><code>fa383ac</code></a> Merge pull request <a href="https://github-redirect.dependabot.com/jsonpickle/jsonpickle/issues/349">#349</a> from Theelgirl/master</li>
<li><a href="https://github.com/jsonpickle/jsonpickle/commit/7c4aee5f5b3cfa89d4699a8d7ff646420f83e2a1"><code>7c4aee5</code></a> Merge branch 'master' of <a href="https://github.com/Theelgirl/jsonpickle">https://github.com/Theelgirl/jsonpickle</a></li>
<li><a href="https://github.com/jsonpickle/jsonpickle/commit/3cc726cb2d2598b9136f4dd627f11903dd5dbeb1"><code>3cc726c</code></a> Added changelog entry</li>
<li>Additional commits viewable in <a href="https://github.com/jsonpickle/jsonpickle/compare/v1.5.0...v2.0.0">compare view</a></li>
</ul>
</details>
<br />

Updates `tqdm` from 4.56.0 to 4.56.1
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/tqdm/tqdm/releases">tqdm's releases</a>.</em></p>
<blockquote>
<h2>tqdm v4.56.1 stable</h2>
<ul>
<li>fix <code>repr()</code> &amp; <code>format_dict</code> when disabled (<a href="https://github-redirect.dependabot.com/tqdm/tqdm/issues/1113">#1113</a> &lt;- <a href="https://github-redirect.dependabot.com/tqdm/tqdm/issues/624">#624</a>)</li>
<li>rename <code>__repr__()</code> =&gt; <code>__str__()</code></li>
<li>minor documentation updates﻿ (<a href="https://github-redirect.dependabot.com/tqdm/tqdm/issues/1113">#1113</a>)
<ul>
<li>fix Binder demo notebook (<a href="https://github-redirect.dependabot.com/tqdm/tqdm/issues/1119">#1119</a>)</li>
<li>remove explicit Dockerfile</li>
<li>move some images to external repo</li>
</ul>
</li>
<li>add &amp; update tests</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/tqdm/tqdm/commit/94842e1027570867885788dc9d7fe038484f085b"><code>94842e1</code></a> bump version, merge pull request <a href="https://github-redirect.dependabot.com/tqdm/tqdm/issues/1113">#1113</a> from tqdm/devel</li>
<li><a href="https://github.com/tqdm/tqdm/commit/ea0638319442bd429c6c663cf6f8c16e889e6502"><code>ea06383</code></a> rename <code>__repr__</code> =&gt; <code>__str__</code></li>
<li><a href="https://github.com/tqdm/tqdm/commit/b2245bf5b6c4e83a502bafeef6f7488c65616827"><code>b2245bf</code></a> tests: add disabled repr, misc docstrings</li>
<li><a href="https://github.com/tqdm/tqdm/commit/42de6bdfc90aca4174b54f01728b61bd2d023f8b"><code>42de6bd</code></a> fix <code>repr()</code> &amp; <code>format_dict</code> when disabled</li>
<li><a href="https://github.com/tqdm/tqdm/commit/a774e3ff8d763116f96c88012e5b0671e3cc2130"><code>a774e3f</code></a> remove Dockerfile</li>
<li><a href="https://github.com/tqdm/tqdm/commit/ca23ad4dd5218cf5b6af8e9549d62797ecc2b61f"><code>ca23ad4</code></a> docs: move away some images to external repo</li>
<li><a href="https://github.com/tqdm/tqdm/commit/718a124858973595260865037ff57d13925d66fd"><code>718a124</code></a> tests: tidy</li>
<li><a href="https://github.com/tqdm/tqdm/commit/94ae1e7a417d874ead74a393ebe3c6f48ca7c6e0"><code>94ae1e7</code></a> add &amp; update contributors</li>
<li><a href="https://github.com/tqdm/tqdm/commit/6805711757d02f50d1eb1a931b13476c555b1e16"><code>6805711</code></a> update year</li>
<li>See full diff in <a href="https://github.com/tqdm/tqdm/compare/v4.56.0...v4.56.1">compare view</a></li>
</ul>
</details>
<br />

Updates `rocketchat-api` from 1.9.1 to 1.14.0
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/jadolg/rocketchat_API/commit/da8907f96fb0dea81d6035d9204515f4428e2eeb"><code>da8907f</code></a> Bump version to 1.14.0</li>
<li><a href="https://github.com/jadolg/rocketchat_API/commit/8e3d0defc9f5ec2dcf44648c8750f47b0f980ff0"><code>8e3d0de</code></a> Merge pull request <a href="https://github-redirect.dependabot.com/jadolg/rocketchat_API/issues/113">#113</a> from JayBraker/patch-1</li>
<li><a href="https://github.com/jadolg/rocketchat_API/commit/c6246ce89dd426818e7e14d97dc2dc1bd4c13a96"><code>c6246ce</code></a> Formatted using black..</li>
<li><a href="https://github.com/jadolg/rocketchat_API/commit/48e3ea89bd55b20dde15a92f403c5760be4e18f6"><code>48e3ea8</code></a> Added Test for raise</li>
<li><a href="https://github.com/jadolg/rocketchat_API/commit/6ffd2ce32fd6bc2967ee7e4aa38f0df780e69a7c"><code>6ffd2ce</code></a> Updated Tests</li>
<li><a href="https://github.com/jadolg/rocketchat_API/commit/78983b39677dd4a6b0916a437e9d05769e62c92f"><code>78983b3</code></a> Tests implemented, formatting</li>
<li><a href="https://github.com/jadolg/rocketchat_API/commit/3157bc97221148c9bd24e413c1c3c89456b47078"><code>3157bc9</code></a> Updated Tests for empty message, custom message ID, updating and deleting</li>
<li><a href="https://github.com/jadolg/rocketchat_API/commit/93571f2ef060096811ab8e31eb9287696896ad27"><code>93571f2</code></a> Implemented API Endpoint sendMessage, implementing tests</li>
<li><a href="https://github.com/jadolg/rocketchat_API/commit/43ee147ec1bfb8dace26df171333cb18c1cdeb29"><code>43ee147</code></a> Updated Style</li>
<li><a href="https://github.com/jadolg/rocketchat_API/commit/1fe29add2cfd6c249a1290453bc3fbccce9dbe94"><code>1fe29ad</code></a> fixed bloopers</li>
<li>Additional commits viewable in <a href="https://github.com/jadolg/rocketchat_API/compare/1.9.1...1.14.0">compare view</a></li>
</ul>
</details>
<br />

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @samsucik will take a look at it as soon as possible ✨

**Comment by samsucik** [comment]
@m-vdb I think sara-tagger shouldn't tag folks in PRs opened by rasabot? In any case, this isn't a PR I can review 🙂

**Comment by m-vdb** [comment]
yes you're right 👍🏻 @erohmensing any easy way to disable this behaviour?

**Comment by erohmensing** [comment]
Hm, if no one gets tagged in it then no one will be responsible for it though 😄

**Comment by m-vdb** [comment]
it's the responsibility of Enable though, and they have their own system 😄

**Comment by alwx** [comment]
Oh, it even has conflicts this time. Makes it interesting to review :)

**Review by alwx — APPROVED** [review]

**Pull request merged**
