### PR TITLE
Fix mapping policy priority

### LINKED ISSUE #3542: Mapping Policy Ignores NLU Thresholds--And is there any way to prioritize one policy over another?
**Rasa version**:  0.14.4

**Python version**:   3.6

**Operating system** (windows, osx, ...):  Redhat

**Issue**:
I have NLU Threshold configured with default 0.3 value. “greet” intent is mapped to “action_greet”. When I get incoming user intent classified as “greet” with 0.24 confidence, I would expect the classification to fail and use the fallback policy. Instead the mapping policy is invoked. So you get the following:

2019-05-21 11:30:25 DEBUG rasa_core.processor - Received user message ‘attending training tomorrow’ with intent ‘{‘name’: ‘greet’, ‘confidence’: 0.24704762503877342}’ and entities ‘[{‘start’: 19, ‘end’: 27, ‘text’: ‘tomorrow’, ‘value’: ‘2019-05-22T00:00:00.000-07:00’, ‘confidence’: 1.0, ‘additional_info’: {‘values’: [{‘value’: ‘2019-05-22T00:00:00.000-07:00’, ‘grain’: ‘day’, ‘type’: ‘value’}], ‘value’: ‘2019-05-22T00:00:00.000-07:00’, ‘grain’: ‘day’, ‘type’: ‘value’}, ‘entity’: ‘time’, ‘extractor’: ‘DucklingHTTPExtractor’}]’

2019-05-21 11:30:25 DEBUG rasa_core.policies.fallback - NLU confidence 0.24704762503877342 is lower than NLU threshold 0.3.

2019-05-21 11:30:25 DEBUG rasa_core.policies.memoization - There is a memorised next action ‘35’ 2019-05-21 11:30:25 DEBUG rasa_core.policies.form_policy - There is an active form ‘student_loan_form’ 2019-05-21 11:30:25 DEBUG rasa_core.policies.ensemble - Predicted next action using policy_4_MappingPolicy

Is there any way for the MappingPolicy to only work when the NLU confidence is greater than threshold?

**Content of configuration file (config.yml)**:
```yml
  - name: KerasPolicy
    epochs: 270
    max_history: 3
  - name: FallbackPolicy
    fallback_action_name: 'action_custom_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
  # add your intents
  - wait: {triggers: action_waiting}
  - ready: {triggers: action_ready}
  - initialize
  - greet: {triggers: action_greet}
  - affirm
  - inform_none
  - deny
  - repeat: {triggers: action_repeat}
  - more_info: {triggers: action_utter_verify_info}
  - not_sure: {triggers: action_not_sure}
  - inform_loan
  - inform_loan_exceeds
  - inform_loan_under
  - automated_message_hold
  - automated_message_terminate
  - out_of_scope: {triggers: action_utter_back_on_track}
  - ambiguous_affirm_deny: {triggers: action_utter_ambiguous_response}
  - ask_is_machine: {triggers: utter_i_am_machine}
  - want_agent: {triggers: utter_will_get_agent}
```

### LINKED ISSUE #3545: mapping policy doesn't persist/load custom priority

### PR DESCRIPTION
**Pull request by erohmensing**
**Proposed changes**:
- Form > Fallback > Mapping priority (mapping will only happen if form validation rejects and NLU threshold is reached)
- fixes #3542
- Mapping Policy correctly persists priority
- fixes #3545 
- Update mapping policy docs to clarify UserUtteranceReverted

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by akelad** [comment]
hmm ok actually i think it shouldn't beat the form policy

**Comment by erohmensing** [comment]
but if the nlu confidence isn't high enough? then how do you know if someone wants to be in the form or  not

**Comment by akelad** [comment]
well the thing is when people are entering information you reeeally don't care whether the correct intent is identified or not. On the other hand if `chitchat` gets recognised with a confidence of 0.3, i'm not sure we should be breaking out of the form

**Comment by erohmensing** [comment]
Hmm. Maybe @Ghostvv has an opinion?

**Comment by Ghostvv** [comment]
I say let the form decide

**Comment by tahamr83** [comment]
I think my input could be useful. Actually giving the form priority in our use case gives us more control. We can decide whether to reject the form based on low NLU confidence and particular requested slots. For example we had a use case where we wanted to move ahead on *any* user input when trying to validate a slot value. Even for very low confidences. And for others we wanted to reject the form.

**Comment by akelad** [comment]
@Ghostvv there's another dilemma here though -- FormPolicy should override FallbackPolicy, MappingPolicy should override FormPolicy (?), but FallbackPolicy should override MappingPolicy... this does not work

**Comment by Ghostvv** [comment]
wait, isn't Fallback should override map only in case of low nlu, so
- in case of high nlu: `Map > Form > Fallback`
- in case of low nlu: `Form > Fallback > Map`

would that work?

**Comment by akelad** [comment]
yeah i guess, how do we easily configure that though?

**Comment by erohmensing** [comment]
Sounds like maybe mapping policy should get its own NLU threshold, since
> basically in case of low nlu, map should be disabled completely 

should probably be the case regardless of whether you have a fallback policy in your config right?

**Comment by tahamr83** [comment]
In our bots we have Form>Fallback>Map and no intent for any form overlaps with map intents. So In case of low NLU we fallback. In case of high NLU the form is rejected (since there is no slot mapping for this intent) and map kicks in. Even if there is an overlap we have control over form and we can decide to reject the form. 
PS: I am not suggesting a strategy. Just helping you guys decide. :)

**Comment by Ghostvv** [comment]
thanks a lot @tahamr83 but I think for general case it makes more sense for map to be higher than a form

@erohmensing can we differentiate in ensemble the reason of fallback?

**Comment by Ghostvv** [comment]
I would like to avoid separate nlu threshold in mapping policy

**Pull request merged**
