### PR TITLE
Unpin urllib3<1.25 as botocore issue is fixed

### PR DESCRIPTION
**Pull request by gthb**
**Proposed changes**:
- remove the urllib3 version constraint; in-range versions of boto3 and botocore no longer require urllib3<1.25, so there's no longer a reason for rasa to do so.

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by tmbo** [comment]
Looks great thanks a lot for this fix - do you mind signing the contributor agreement?

**Comment by gthb** [comment]
> do you mind signing the contributor agreement?

Sure, just waiting for the OK from my employer. (Should have just posted an issue instead :-) )

**Comment by erohmensing** [comment]
Hi @gthb, any update on the CLA approval? 

> Should have just posted an issue instead 

We could also close this PR and have one of us implement your changes if that's easier -- though we'd love your contribution, we appreciate you pointing this out nonetheless!

**Comment by gthb** [comment]
> We could also close this PR and have one of us implement your changes

Sure, of course, go ahead!

**Pull request closed without merging**
