### PR TITLE
Replace old os.path calls by pathlib correspondents - part 1

### PR DESCRIPTION
**Pull request by ErickGiffoni**
This PR partially addresses #3153.

Me, @jps12 and @caue96 are continuing the work that was being done previously in #7383 and #7118.

While this PR makes changes to some directories under `rasa/`, we will be doing 2 or 3 other separated PRs,
as suggested by @wochinge, so the changes can be reviewed more easily.

**Proposed changes**:
- in general: replace `os.path` calls with each `pathlib.Path` correspondent.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by wochinge — COMMENTED** [review]
@ErickGiffoni Thanks for your contribution! 

There is unfortunately one issue: We are currently doing a big revamp of the model architecture which will cause a lot of changes in the training / testing and prediction (server, Agent) modules. We aim to wrap this up by the end of next but until then I'd like to put this on hold as this will cause quite a lot of merge conflicts and I want to avoid making the quite complex integration even more messy. Would that be okay for you?

**Comment by ErickGiffoni** [comment]
> @ErickGiffoni Thanks for your contribution!
> 
> There is unfortunately one issue: We are currently doing a big revamp of the model architecture which will cause a lot of changes in the training / testing and prediction (server, Agent) modules. We aim to wrap this up by the end of next but until then I'd like to put this on hold as this will cause quite a lot of merge conflicts and I want to avoid making the quite complex integration even more messy. Would that be okay for you?

Ok, me and my colleagues understand !
Do you think we better make the other 3 PRs mentioned targeting branch `2.8.x`,
or should we wait... or maybe make them as drafts ?

**Comment by wochinge** [comment]
Thanks for understanding this! I think 2.8.x would eventually cause the same merge conflicts as we'd have to merge that to `main` eventually. Drafts would be the better solution (however, they have the risk that you'd do some duplicate work). We are basically touching all modules related to training and prediction (`Agent`, `Processor`) - you can also see our current state [here](https://github.com/RasaHQ/rasa/pull/9747). Anything outside of this should be fine to touch

**Comment by ErickGiffoni** [comment]
@wochinge and @ancalita ok, sure, thanks !
We will get back to it soon and hold off the specific modules.

**Comment by ErickGiffoni** [comment]
Hey guys, I'd like to inform in advance that from Nov 10 to Dec 13 (at least)
I'l be working on another project at Gloria Institute in a partnership with Microsoft.
Because of that I won't be working on this PR for that period of time. I apologise, but
when I get back I can let you know if I'll still be able to finish this here !
Thanks for understanding :)

**Comment by ancalita** [comment]
Hi @ErickGiffoni hope all is well! Double-checking if you're still interested in completing this PR? If so, since `main` branch has diverged quite significantly since Nov-21, I'd advise opening a new PR. Otherwise, if not interested any longer, please close this PR.

**Comment by ErickGiffoni** [comment]
> Hi @ErickGiffoni hope all is well! Double-checking if you're still interested in completing this PR? If so, since `main` branch has diverged quite significantly since Nov-21, I'd advise opening a new PR. Otherwise, if not interested any longer, please close this PR.

Hey @ancalita tks for checking in on me, hope all is well with you too.
I'll close this PR then. For now I'm very very busy and I can't continue
working on this. But hopefully another time I can contribute more !

=)

**Pull request closed without merging**
