### PR TITLE
Fix incorrect attribute for key prefix in RedisTrackerStore

### LINKED ISSUE #7306: 'RedisTrackerStore' object has no attribute 'prefix'
**Rasa version**: 2.1.0

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): 

**Issue**: 

An error occurred when using `tracker_store` of type `redis`.

**Error (including full traceback)**:
```
2020-11-18 08:22:25 ERROR    rasa.core.tracker_store  - Error happened when trying to save conversation tracker to 'RedisTrackerStore'. Falling back to use the 'InMemoryTrackerStore'. Please investigate the following error: 'RedisTrackerStore' object has no attribute 'prefix'.
```

Looks like the issue comes from this line: https://github.com/RasaHQ/rasa/blob/384b078b74e7f365f9262d80977a30615d6ecb3f/rasa/core/tracker_store.py#L349

It should be `self.key_prefix` instead of `self.prefix`.

### PR DESCRIPTION
**Pull request by ducminh-phan**
Fix #7306

**Proposed changes**:
- Use `self.key_prefix` instead of the erroneous `self.prefix` in `rasa.core.tracker_store.RedisTrackerStore`.

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @dakshvar22 will take a look at it as soon as possible ✨

**Comment by dakshvar22** [comment]
@federicotdn Can you please review this as I am not very aware of this part of the code 🙏

**Review by federicotdn — APPROVED** [review]
Looks good! Thanks for fixing this 👍

**Comment by federicotdn** [comment]
@ducminh-phan could you take a look at this failing build? https://github.com/RasaHQ/rasa/pull/7334/checks?check_run_id=1466365759#step:9:19 Thanks!

**Pull request merged**
