### PR TITLE
Rename changelogs that end with .enhancement.md

### PR DESCRIPTION
**Pull request by Tawakalt**
**Proposed changes**:
- Rename changelogs that end with .enhancement.md

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by m-vdb — APPROVED** [review]
🤩 thanks!

**Comment by m-vdb** [comment]
@Tawakalt apparently you need to sign the CLA agreement 🤔

**Comment by Tawakalt** [comment]
@m-vdb Where/How do I do that? 🤔

**Comment by m-vdb** [comment]
check out the link in [this comment](https://github.com/RasaHQ/rasa/pull/8427#issuecomment-816811150)

**Pull request merged**
