### PR TITLE
upgrade pip in dockerfile, prevents tensroflow 1.15 install error

### PR DESCRIPTION
**Pull request by amn41**
**Proposed changes**:
- upgrade pip to latest in base Dockerfile
- related to https://github.com/RasaHQ/rasa/issues/4782 

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
I just created a pr to upgrade pip, happens in line 52 🤔

**Comment by wochinge** [comment]
just wanted to say the same :-D

**Comment by wochinge** [comment]
@erohmensing it's already on 1.4.x? So we can just update `master` with these changes?

**Comment by erohmensing** [comment]
no it's already in the file that alan edited here, on master as well https://github.com/RasaHQ/rasa/blob/master/Dockerfile#L49

**Comment by erohmensing** [comment]
@amn41 here is the relevant PR https://github.com/RasaHQ/rasa/pull/4763/files

**Comment by wochinge** [comment]
Ah, pycharm hadn't updated yet after the pull 👍

**Pull request closed without merging**
