### PR TITLE
Allow requests to /status for NLU-only models

### LINKED ISSUE #4250: HTTP API - Cannot fetch /status for NLU-only model
**Rasa version**:
1.2.2 
(via Docker container: rasa/rasa:1.2.2-spacy-en)

**Issue**:
There is an endpoint /status as part of the HTTP API.
https://rasa.com/docs/rasa/api/http-api/#tag/Server-Information/paths/~1status/get

This returns some metadata about the currently loaded model, including the model file, trained date, Rasa version used for training, and more. (I'm mostly interested in obtaining the trained date).

After loading an NLU only model, the /status endpoint returns this error:

```
{
  ​code: 409,
  help: "https://rasa.com/docs/rasa/user-guide/running-the-server/",
  message: "No agent loaded. To continue processing, a model of a trained agent needs to be loaded.",
  reason: "Conflict",
  status: "failure",
  version: "1.2.2"
}
```

The error message is not particularly clear, but the referenced documentation page contains the following:

> If you start the server with an NLU-only model, not all the available endpoints can be called. Be aware that some endpoints will return a 409 status code, as a trained Core model is needed to process the request.

It looks to me like the /status endpoint is one of the endpoints that returns the 409 status code when an NLU-only model is loaded. But surely status should be available for any kind of model? Some of the metadata properties might not be relevant for an NLU-only model, but much of it is still useful.

It was possible to retrieve the model status in Rasa NLU 0.14.x. I believe the same should be possible in Rasa 1.x.

**Error (including full traceback)**:
```
{
  ​code: 409,
  help: "https://rasa.com/docs/rasa/user-guide/running-the-server/",
  message: "No agent loaded. To continue processing, a model of a trained agent needs to be loaded.",
  reason: "Conflict",
  status: "failure",
  version: "1.2.2"
}
```

**Command or request that led to error**:
```
HTTP GET /status
```

### PR DESCRIPTION
**Pull request by Polarisation**
**Proposed changes**:
- In the HTTP API, allow /status to be fetched for NLU-only models. Fixes #4250

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by msamogh** [comment]
Thanks for the PR, we'll give it a review as soon as possible.

**Comment by wochinge** [comment]
@Polarisation Thanks for your contribution. I'm afraid the solution is not that easy since the status should be communicated correctly in case things are not ready.

I think we could set `allow_nlu_only` https://github.com/RasaHQ/rasa/blob/3df8ba165867931e1466af8e35aad4f7f4e96b9c/rasa/core/agent.py#L391 to `True` for the status check. This would required to add a `allow_nlu_only` parameter to `ensure_loaded_agent` which then get's passed to `app.agent.is_ready`. what do you think?

**Comment by Polarisation** [comment]
I'm not so familiar with the concept of agents since I have only used the
NLU functionality, but if all I would have to do is add a parameter to the
request to get the status for an NLU-only model, that works for me!

**Comment by wochinge** [comment]
>  but if all I would have to do is add a parameter to the
request to get the status for an NLU-only model, that works for me!

No, we have to make same changes to the code so that your request works. The additional parameter has to be added to the `ensure_loaded_agent` decorator and from there passed to the `agent.is_ready` method. Is that clear now?

**Comment by Polarisation** [comment]
Yes, I understand code changes will be necessary, I just don't have any preferences on the implementation so long as it's possible to get a status 🙂

I'm not currently planning to update this PR further since I'm not that familiar with the codebase (I wouldn't know how to test the scenario you raised). So feel free to amend / reject and start with a fresh fix.

**Comment by wochinge** [comment]
@Polarisation Cool, then I close this issue add it to our backlog so that we have it on our roadmap!

**Pull request closed without merging**
