### PR TITLE
Persistence of rabbitMq messages

### PR DESCRIPTION
**Pull request by skerdudou**
The queue si already created "durable" and persist over rabbitMq server restart but messages in it doesn't by default.
We need to flag messages as persistent with `delivery_mode`.
source : https://www.rabbitmq.com/tutorials/tutorial-two-python.html

### CODE REVIEW

**Comment by akelad** [comment]
thanks for submitting this PR, we'll give it a review as soon as possible

**Comment by wochinge** [comment]
Good catch! Thanks a lot! Can you please provide also provide changelog? 🙏

**Comment by skerdudou** [comment]
Hi, I'm kind of busy and indeed it would be great if you could do it, thank you ;-)

**Comment by wochinge** [comment]
wrapping it up in https://github.com/RasaHQ/rasa/pull/5211

**Pull request closed without merging**
