### PR TITLE
Amendmend to PR #7423

### PR DESCRIPTION
**Pull request by hotzenklotz**
**Proposed changes**:
@dakshvar22 To my dismay I discovered that my refactoring reintroduced a bug in my original PR #7423. Unfortunately, it was not captured by any of the unit the tests. I came across it when running a new response selector evaluation today. This PR should fix it.

In short, the default value for a response selector key was wrong. It needs to default to `None` for all "regular" intent examples or otherwise those won't be filtered out further down the pipeline and crash the sklearn reports.

cc @tmbo 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by dakshvar22** [comment]
Thanks @hotzenklotz. Can you please also post what the output now looks like after running a fresh evaluation on the trained response selector model?

**Comment by hotzenklotz** [comment]
It looks pretty much the same as before. Only now the response selector labels include their parents intent name as well, e.g. `ask_faq/question_1`.

image

**Comment by dakshvar22** [comment]
Thanks! Can you please also add a unit test which would check if training examples with no response keys are correctly filtered during evaluation?

**Comment by hotzenklotz** [comment]
There is already a unit test for that: https://github.com/RasaHQ/rasa/blob/1.10.x/tests/nlu/test_evaluation.py#L582

**Review by dakshvar22 — APPROVED** [review]

**Comment by dakshvar22** [comment]
@hotzenklotz I just pushed a changelog to indicate this is a bugfix.

**Pull request merged**
