### PR TITLE
added in test to ensure the /status api route gives back a model dir

### PR DESCRIPTION
**Pull request by btotharye**
**Proposed changes**:
- Added in test for previous merge that updated the `/status` api route to give back the true model directory and file and not the tmp directory.  This test ensures we get back the proper model dir and not the tmp location.

**Status (please check what you already did)**:
- [X] made PR ready for code review
- [X] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [X] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by btotharye** [comment]
any idea why the response.json is empty on the travis test?  This works fine when testing locally for me @wochinge

**Comment by wochinge** [comment]
@btotharye Just realized that I overlooked sth during the actual bug fix review.

`model.get_latest_model()` this get's the just the latest trained file in the model directory. That's not necessarily the one is actually used. 

Instead we have to pass the `model_path` in `load_local_model` to the `Agent` save it there. 
I think that might also be the reason for the failing test.

**Comment by btotharye** [comment]
> @btotharye Just realized that I overlooked sth during the actual bug fix review.
> 
> `model.get_latest_model()` this get's the just the latest trained file in the model directory. That's not necessarily the one is actually used.
> 
> Instead we have to pass the `model_path` in `load_local_model` to the `Agent` save it there.
> I think that might also be the reason for the failing test.

ok I'll try to look into this today/tomorrow then to fix it

**Comment by btotharye** [comment]
> load_local_model

So do you mean something like this I see in other functions in the `server.py` file as far as to create the model path and use it like you mentioned?  Or do you mean actually calling the `load_local_mode` function?

```
model_path = await train_async(
                domain=domain_path,
                config=config_path,
                training_files=temp_dir,
                output_path=model_output_directory,
                force_training=rjs.get("force", False),
            )
```

**Comment by wochinge** [comment]
When we start rasa locally without a model server, the `agent` will use `load_local_model` to load the model from disk. The parameter `model_path` of `load_local_model` specifies the path to the local model. When we then call the constructor of `Agent` we have to pass in the `model_path` to be able to return the `model_path` whenever there is a request to `/status`. Currently we are only passing the `unpacked_model` which is a temporary directory.

**Comment by btotharye** [comment]
> Looks great @btotharye ! Thanks for fixing this.
> I suggest we merge this into `1.4.x` (please wait for travis to pass all tests although this branch is not protected) instead of `master`. I'd also update the changelog since the other change was already released (sth like `- `/status` endpoints show correct path to model archive)

Would this go in the `1.4.2` part of the changelog then?

**Comment by btotharye** [comment]
closing out this PR and starting a new one @wochinge kept having issues trying to rebase this into 1.4.x

**Pull request closed without merging**
