### PR TITLE
Fix domain_responses KeyError

### PR DESCRIPTION
**Pull request by Tawakalt**
**Proposed changes**:
- Fixes [ATO-1529](https://rasahq.atlassian.net/browse/ATO-1529)

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [X] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [X] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

[ATO-1529]: https://rasahq.atlassian.net/browse/ATO-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Tawakalt** [comment]
I believe this is already being tested [here](https://github.com/RasaHQ/rasa/blob/f2766695f4b4039688919c1e98d3f6c074584dbb/tests/core/nlg/test_callback.py#L94). 🤔

**Review by ancalita — COMMENTED** [review]
LGTM 👍🏻 Since we don't have integration testing with the action server, I'd just test manually the use-case from @l2nguyen to make sure the fix is the correct one.

**Comment by Tawakalt** [comment]
@l2nguyen How can I manually test this use-case?

**Comment by l2nguyen** [comment]
@Tawakalt I asked the customer that reported it to test the fix. Will let you know if it works.

**Comment by l2nguyen** [comment]
@Tawakalt - They tested it and it works as intended.

**Review by ancalita — APPROVED** [review]

**Pull request merged**
