### PR TITLE
Use output_channel of externally triggered intent as input_channel

### PR DESCRIPTION
**Pull request by pheel**
**Proposed changes**:
- Currently any intent pushed to the tracker via `/conversations/<conversation_id>/trigger_intent` results in a user event with input channel `None`. This means `latest` output channel is effectively lost until a "real" user message comes in from a channel. This sets input channel using the output channel determined from the request.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @b-quachtran will take a look at it as soon as possible ✨

**Comment by federicotdn** [comment]
It's a bit strange to be using an output channel to populate the latest input channel field of the tracker, given that they are not the same thing. Maybe we could update the tracker in a way where the latest input channel property is not lost? Maye @JEM-Mosig has an opinion on this.

**Comment by pheel** [comment]
@federicotdn, @b-quachtran, I could make `rasa.core.trackers.DialogueStateTracker.get_latest_input_channel` skip over messages with null output channel, and it would have the same effect of `latest` not losing its meaning. Sounds like a less invasive change. Should I go for it?

**Comment by pheel** [comment]
Ah, I see this was cloned at https://github.com/RasaHQ/rasa/pull/6472.

**Comment by federicotdn** [comment]
@pheel 
> I could make rasa.core.trackers.DialogueStateTracker.get_latest_input_channel skip over messages with null output channel, and it would have the same effect of latest not losing its meaning. Sounds like a less invasive change. Should I go for it?

I think that makes a lot of sense, given the name of the method `get_latest_input_channel`. The thing is, that with that change we would be effectively modifying the value the method returns in different contexts (on trackers with trailing UserUttered events with no input channel). The PR I opened was a test to see if it made sense to instead make the change more specific to the externally triggered intents feature (note that I did not change `get_latest_input_channel`). Apart from this, I still think we should not mix input and output channels.

**Comment by pheel** [comment]
Yeah, I'll close this PR in favor of https://github.com/RasaHQ/rasa/pull/6472 then.

**Pull request closed without merging**
