### PR TITLE
Update tensorflow-hub and tensorflow-probability

### PR DESCRIPTION
**Pull request by tabergma**
**Proposed changes**:
- Update `tensorflow-hub` to `0.9.0`
- Update `tensorflow-probability` to `0.11.1`

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by tabergma** [comment]
/modeltest
```
include:
 - dataset: ["all"]
   config: ["all"]
```

**Comment by tabergma** [comment]
/modeltest

```yml
include:
 - dataset: ["all"]
   config: ["all"]

```

**Review by wochinge — APPROVED** [review]
Does it make sense to use `>=` and `<=` to also work with the old versions or was there a breaking change?

**Comment by dakshvar22** [comment]
There wasn't a breaking change but we wanted tensorflow deps to be updated to the latest version before 2.0 release.
Do you suggest including the older version in a range in that case?

**Comment by wochinge** [comment]
> Do you suggest including the older version in a range in that case?

Imo a bigger range of compatible versions is better for our users as they might have other things installed. However, this might be slightly different for tensorflow things so up to you.

**Comment by dakshvar22** [comment]
I think for tensorflow related deps it's better to pin them since they tend to be fragile with each other. For example, `tensorflow-text==2.2` may not be compatible with `tensorflow==2.3` and then finding that combination is hard from the ranges specified.

**Pull request merged**
