### PR TITLE
Return "Migrate from" entry to the docs sidebar

### PR DESCRIPTION
**Pull request by alwx**
**Proposed changes**:
- Returns back the "Migrate from" entry to the docs sidebar
Screenshot 2020-11-19 at 13 59 10

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by akelad** [comment]
@m-vdb remind me - does the sidebar get updated with patch releases? Because if yes i'd like this to go into version 2.1 (since that's where we released the updated code right?)

**Comment by m-vdb** [comment]
@akelad no it doesn't automatically. But we can definitely propagate the changes manually on the `documentation` branch, and that will do the trick (you wouldn't even have to do a patch release)

**Review by akelad — APPROVED** [review]

**Comment by akelad** [comment]
@alwx could you also apply it to the documentation branch as maxime suggested then please?

**Comment by alwx** [comment]
@akelad yes, will do that in a min

**Comment by alwx** [comment]
Hm, merged it but it still looks the same.
Here is the PR: https://github.com/RasaHQ/rasa/pull/7314

Anything I did wrong, @m-vdb ?

**Comment by akelad** [comment]
I guess it somehow needs to go in here? https://github.com/RasaHQ/rasa/blob/documentation/docs/versioned_sidebars/version-2.1.x-sidebars.json

not an expert with this though

**Comment by m-vdb** [comment]
yes exactly like @akelad said. Sorry, I wasn't clear enough 😬

**Pull request merged**
