### PR TITLE
Support server list, drop group_id from producer

### PR DESCRIPTION
**Pull request by rgstephens**
**Proposed changes**:
- Add support for list of Kafka servers, drop group_id from producer

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by b-quachtran — APPROVED** [review]

**Comment by akelad** [comment]
@b-quachtran does this do the same as your PR?

**Comment by akelad** [comment]
@b-quachtran what should we do with this PR now? Did the other PR cover this already?

**Comment by b-quachtran** [comment]
@akelad My PR didn't include support for server list and I removed the ready-to-merge status because of some failed CI checks, but that looks resolved now.

**Comment by akelad** [comment]
is the support server list actually a request from a customer? Because we shouldn't really be merging new features into patch releases

**Comment by akelad** [comment]
also the changelog entry needs to be changed, some of the stuff listed in there is not part of this PR

**Comment by b-quachtran** [comment]
@akelad Yeah, a customer specifically asked about adding multiple Kafka server support in 1.10.X

**Comment by akelad** [comment]
@b-quachtran will you take care of doing a minor release then?

**Comment by b-quachtran** [comment]
@akelad Yep, definitely. I'll take care of the release

**Pull request merged**
