### PR TITLE
configure algolia search

### PR DESCRIPTION
**Pull request by m-vdb**
**Proposed changes**:
- Fixes https://github.com/RasaHQ/rasa/issues/6330

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by tmbo** [comment]
should we merge this and release it?

**Comment by m-vdb** [comment]
for reference: no, we need to wait for updates on Algolia's end to ensure it works properly

**Review by erohmensing — CHANGES_REQUESTED** [review]
Unfortunately it also provides links to rasa x which don't work when you click on them 😕  think we need to wait for algolia as discussed

**Review by erohmensing — APPROVED** [review]
yay 🙌🏻  😭

**Pull request merged**
