### PR TITLE
Handle Facebook chatbot referal in metadata

### PR DESCRIPTION
**Pull request by RogersNtr**
**Handle Facebook referal postback**:
- The idea is to handle the m.me/ref=<ref_code> type link from messenger. The result of the change is that for the first interaction of the user with the bot, if the user has joined the bot using a referal link, the code will add the metadata to the tracker, enabling the use of this referal for later purpose.
- I test it already locally and it works fine without breaking anything

**Status (please check what you already did)**:
- [] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @koaning will take a look at it as soon as possible ✨

**Comment by erohmensing** [comment]
Hey @RogersNtr, thanks for the PR and your patience on a review! 

This use case is a perfect example for why we make the connectors easily extensible. In this case, it'd be preferred if you made a `CustomFacebookInputChannel(FacebookInputChannel)` that extends the class by adding a `get_metadata` method. That is the only piece of code that needs to be in your custom connector, as the rest will be inherited. 

The metadata function is there to allow different users to pass the information they need for their specific use cases to the actions, but we don't want to add code and more weight to the trackers being sent around if the information is not relevant to all users. A post in the forum about what you achieved and how you achieved it, in case others were looking to do the same, wouldn't go amiss though!

**Comment by RogersNtr** [comment]
Hi @erohmensing 
Get it! Thanks for the reviews. So should I recreate a Pull request integrating these changes ?  or you integrate them already ? 

Thanks in advance for your reply.

**Comment by erohmensing** [comment]
I meant that in your project, instead of using the default facebook channel, you should make a custom connector module that implements your `get_metadata` function, and call that channel from your credentials instead 🙂

**Pull request closed without merging**
