### PR TITLE
Allow multiple entities for one token

### PR DESCRIPTION
**Pull request by raoulvm**
**Proposed changes**:
Allow multiple entities to be annotated for the same word/tokens.

When using entity extractors that support generating multiple entities from a single expression, the test stories fail as there is no way to annotate multiple entity_types and entity_values

New annotation option is

```YAML
stories:
  - story: Some story
    steps:
      - user: |
          I would like work for [Rasa][{"entity":"chatbot_software", "value":"rasa"},{"entity":"software_company", "value":"rasa"},{"entity":"employer", "value":"rasa"}]
        intent: apply_job
```
As the extractors as pipeline components neither have access to _domain_ during training, nor to the dialog _tracker_ during inference, they can't judge which _characteristic_ (or _attribute_) of the word "Rasa" is important for answering a question. If the entity extractor could access the _domain_ knowledge, it would probably be able to filter the possible entity types to those defined with `use_entities` in the domain (e.g. employer).

If it could access the tracker, and the preceding question was a closed question, the possible answers could also limit the applicable entity types. 

In this PR I have changed the training data parser to be able to cope with the format shown above, and also changed the readerwriter.py to be able to generate such training data messages if the entities found have exact same start and end positions. 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [X] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by raoulvm** [comment]
@ancalita Do you know why I get linting errors in "old" code? And if I change that, some other old lines are complained about.
Thanks
Raoul

**Comment by raoulvm** [comment]
Hi @samsucik I was told by @hsm207 that you are the dev on duty today.
Could you explain why `extractors` is `None` (and thus it [returns True here](https://github.com/RasaHQ/rasa/pull/10394/files#diff-8d9591f26ceb08200d3364a40b1b25b9403f13501efd9dd8922ff1c2e47901c3L1092)) if it was `[CRFEntityExtractor.name]` [provided here](https://github.com/RasaHQ/rasa/blob/2.8.x/tests/nlu/test_evaluation.py#L203)? 

I do not understand what is happening here.

Thanks
Raoul

**Comment by ancalita** [comment]
> After changing that globally I could run `poetry run flake8 rasa test --extend-ignore D` without getting old code complained about.

@raoulvm Great! In addition, you can also use `make lint` [command](https://github.com/RasaHQ/rasa/blob/2c17cd24003e2cc9e23276e02b32757445867774/Makefile#L82) in your Terminal for a more comprehensive check.

**Comment by samsucik** [comment]
@raoulvm I checked your changes now. I'm glad you found a workaround for the failing test. And 'm excited about the proposed improvement, thanks a lot for that!

As for going ahead with this, I have to think about it a bit more and discuss with others because it'd likely have a broader impact. Some points that come to my mind are:
- When an entity can be "multi-annotated", the validity of this annotation is strongly coupled with the models used. I.e. it'd be invalid if we only have DIET in the pipeline (or a different extractor that assigns only a single entity label to a token), but would be valid if we've got a RegexExtractor.
- Once an entity can be "multi-annotated" in test stories, a natural follow-up is "why not in training stories?". And that leads us to the thick line drawn between extractors like DIET vs ones like RegexExtractor -- namely, the latter one not requiring annotations in training data. Additionally, we'd be also drawing another line, this time between training and test story format.
- The exact annotation format needs to work with all special cases, i.e. we'd need to triple-check the regexes (one immediate candidate edge case to check is when a language doesn't have words separated by spaces and you've got 2 entities coming one right after another). But this is ultimately just a technicality.
- If we decide to go with the change, then it'll have to become part of 3.x sooner or later, which means we want to be certain about it.

**Comment by raoulvm** [comment]
HI @ancalita , you should consider cleaning "old stuff" anyhow. If you run the lint against the whole repo (no diff) you get 3000+ doc-string complaints.
```shell
(rasa2source) #:~/PyProjects/rasa$ poetry run flake8 rasa tests --select D | wc -l
3720
```

**Comment by raoulvm** [comment]
Hi @samsucik 

> it'd be invalid if we only have DIET in the pipeline. 

I just ran a test with the mood bot including new _multi-annotated_ entities in the NLU Training Data , with DIET as the entity extractor. DIET is training on the last item in the list only.

> Once an entity can be "multi-annotated" in test stories, a natural follow-up is "why not in training stories?"  

Good question. It should.

> And that leads us to the thick line drawn between extractors like DIET vs ones like RegexExtractor -- namely, the latter one not requiring annotations in training data.  

Actually that line is already there. There are intent training data _containing_ entities, and there are Regex Expressions and Lookups, which are separated. If you include other ontological tools like mine it is separated even more, as those data do not fit into the nlu files at all.

For the other details, you are perfectly right: I do not speak any non-whitespace language, and I am no fan of regex for literal lookups (regards to @koaning for his splendid flashtext extractor idea which I used as a basis for the hierarchies) so I wasn't very deep into those and did not make test cases for them beyond what is already in the tests.

**Comment by samsucik** [comment]
Thanks for digging into the questions so quickly. As you can see, there are some rough edges to overcome if this was to become part of 2.8 (and later 3.x) and, more importantly, if these changes were to be maintained and further built upon in future iterations.

Regarding the line between DIET and RegexExtractor: Indeed, that line already exists (sorry for not being 100% clear in my previous reply). But, in my opinion, we should try to not make these arbitrary lines even worse.

All in all, I think it's important that you're exploring how far you can go with 2.8. The other part is then taking a step back and seeing what's the high-level problem that you're trying to solve, as we discussed previously 🙂

**Comment by raoulvm** [comment]
Test with 3.0 see here #10404

**Comment by JEM-Mosig** [comment]
We should use this also to resolve [this issue](https://github.com/RasaHQ/rasa/issues/6712).

**Pull request closed without merging**
