### PR TITLE
Increase speed of augmented lookup for `AugmentedMemoizationPolicy`

### PR DESCRIPTION
**Pull request by JEM-Mosig**
**Proposed changes**:
- Identical to https://github.com/RasaHQ/rasa/pull/9064 but targeted at 2.8.x

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- ~updated the documentation~
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by JEM-Mosig** [comment]
@mprazz Will 2.8.x bugfixes be auto-merged into main before the 3.0 release, or will I have to create another PR onto main?

**Comment by mprazz** [comment]
> @mprazz Will 2.8.x bugfixes be auto-merged into main before the 3.0 release, or will I have to create another PR onto main?

@JEM-Mosig we've recently pushed a workflow that does this automatically yes, so a PR should be opened automatically. That being said it is very recent, so please do check that a PR was opened shortly after you merge this, and let us know if it doesn't look like it's working :pray:

**Review by kedz — COMMENTED** [review]
LGTM 🚀

**Review by joejuzl — APPROVED** [review]

**Comment by JEM-Mosig** [comment]
@mprazz I don't see a separate PR for `main`. Did I overlook something?

**Comment by mprazz** [comment]
@JEM-Mosig Indeed it has not worked ([workflow run here](https://github.com/RasaHQ/rasa/runs/3372722142?check_suite_focus=true) ) -- there is a file missing in 2.8.x as the fix for it came after the branch was made. I think you'll have to make the PR manually this time, sorry! I'll port the fix in the meantime.

**Comment by mprazz** [comment]
Opened a fix PR here: #9434

**Pull request merged**
