### PR TITLE
Upgrade prompt-toolkit to 3.0

### PR DESCRIPTION
**Pull request by ancalita**
**Proposed changes**:
- Upgrades prompt-toolkit with a constraint `<3.0.29` version because this version introduces breaking changes to unit testing interface (see submitted issue: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1660)
- Make some edits to the use of `questionary` which has `prompt-toolkit` as dependency, e.g. replace sync method `questionary.ask()` with `ask_async()`, otherwise this breaks `rasa shell` by raising `RuntimeError: This event loop is already running`. The change was made in a few places: 

1. `rasa/core/channels/console.py::_get_user_input()`
2. `rasa/cli/utils.py::payload_from_button_question()`
3. `rasa/core/training/interactive.py::_ask_questions()`
4. `rasa/core/training/interactive.py::_retry_on_error()`
5. `rasa/core/training/interactive.py::_ask_if_quit()`
6. `rasa/core/training/interactive.py::_request_export_info()`
7. `rasa/core/training/interactive.py::_get_button_choice()`

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by ancalita** [comment]
@losterloh This is now ready for review after a great troubleshooting round with @tmbo 🥳

**Comment by tmbo** [comment]
@ancalita do you mind linking the ticket you created on the prompt-toolkit repo here so that we have a reference to it if / when we need to get back to this pr in the future?

**Comment by ancalita** [comment]
> @ancalita do you mind linking the ticket you created on the prompt-toolkit repo here so that we have a reference to it if / when we need to get back to this pr in the future?

@tmbo I've just linked to it in the PR description. I also just noticed that `prompt-toolkit` version is still at `3.0.3` in `poetry.lock`, I'll update now and push the change.

**Review by losterloh — APPROVED** [review]
🚀 💯

**Comment by ancalita** [comment]
@tmbo I just ran a sanity check with `rasa interactive` on a `rasa init` project and everything works fine up until a point 😅 
I tried this conversation:
```
- Hi # correct prediction
- Hey! How are you? # correct action
- fANTASTIC # here i have to correct intent to `mood_great`
- Great, carry on! # correct predicted action
```
After the last predicted action `action_listen`, I get an error, with this stacktrace:
```
 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/Users/ancalita/rasa-projects/rasa/rasa/core/training/interactive.py", line 1504, in record_messages
    await _predict_till_next_listen(
  File "/Users/ancalita/rasa-projects/rasa/rasa/core/training/interactive.py", line 978, in _predict_till_next_listen
    await _print_history(conversation_id, endpoint)
  File "/Users/ancalita/rasa-projects/rasa/rasa/core/training/interactive.py", line 483, in _print_history
    print(table)
BlockingIOError: [Errno 35] write could not complete without blocking
2022-08-11 10:34:33 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<SignalRouter._dispatch() done, defined at /Users/ancalita/rasa-projects/oss-0908-3.2.x/lib/python3.9/site-packages/sanic/signals.py:121> exception=BlockingIOError(35, 'write could not complete without blocking', 0)>
Traceback (most recent call last):
  File "/Users/ancalita/rasa-projects/oss-0908-3.2.x/lib/python3.9/site-packages/sanic/signals.py", line 161, in _dispatch
    retval = await maybe_coroutine
  File "/Users/ancalita/rasa-projects/oss-0908-3.2.x/lib/python3.9/site-packages/sanic/app.py", line 1581, in run_delayed_task
    await prepped
  File "/Users/ancalita/rasa-projects/rasa/rasa/core/training/interactive.py", line 1596, in run_interactive_io
    await record_messages(
  File "/Users/ancalita/rasa-projects/rasa/rasa/core/training/interactive.py", line 1504, in record_messages
    await _predict_till_next_listen(
  File "/Users/ancalita/rasa-projects/rasa/rasa/core/training/interactive.py", line 978, in _predict_till_next_listen
    await _print_history(conversation_id, endpoint)
  File "/Users/ancalita/rasa-projects/rasa/rasa/core/training/interactive.py", line 483, in _print_history
    print(table)
BlockingIOError: [Errno 35] write could not complete without blocking
```
I've tried amending `print(table, flush=True)`, but it didn't help. 
I also double-checked this is not an error dating before this PR, so I tested with rasa `3.2.5` on `3.2.x` branch and no errors were triggered. Any ideas? 🆘

**Pull request merged**
