### PR TITLE
Add template name to bot event

### LINKED ISSUE #4424: Add template id to bot event
**Description of Problem**:

Right now, [bot events](https://rasa.com/docs/rasa/api/events/#bot-responded-message) only include the message text. It would be useful to also include the template id (eg: `utter_[action]` ) to make it easier to get all events for a single utterance. We are using events for analysis purposes with multi-language bots so having a common ID across languages would make it easier to analyze questions/answers. Also when copy of a template changes, the event would still keep the same template id.

**Overview of the Solution**:

Add templates to bot utterance events

**Definition of Done**:
- [ ] Templates are added as a property in the bot events
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog

### PR DESCRIPTION
**Pull request by ViniciusBernardo**
**Proposed changes**:
Closes #4424 
- Added the `template_name` to metadata of BotUttered object

**Changes Made**:
- The default behavior of the method `run` of the class `ActionUtterTemplate` was changed to add the `template_name` inside the `message` dict. This will make the function `create_bot_utterance(message)` always add the template_name into a `BotUttered` object;
- Some tests needed to be changed, especially those which assert events of type `BotUttered`.

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
Thanks for the PR, @ViniciusBernardo! In the future, it would be great if you would write on the issue that you're interested in working on that specific issue, so that someone can assign it to you and others will know it is already being worked on. 

One question: did you install `black` via `pip install -r requirements.txt`? It looks like black changed some files you haven't touched, which shouldn't happen if you're on the same version we are.

I notice the PR is still a WIP, please add a comment when it is ready for review so that I don't miss it 😄

**Comment by ViniciusBernardo** [comment]
Sorry, my bad, next time I will write on the issue. About the black package, I installed again using `pip install -r requirements-dev.txt` and it only changed the files that I touched. I will ammend the modification into the last commit and force the update of the branch. Thanks for the advises!

**Comment by tmbo** [comment]
Regarding the implementation: 
- I think some sort of template-id should be an event property and not part of the metadata
- every `BotUttered` event should get this information (you currently implemented it only for utter actions, but there are other actions which use templates as well and create bot utterances)

**Comment by ViniciusBernardo** [comment]
@tmbo, I think I added the template_name to all actions that create `BotUttered` events. About the template_id. Do you think it would be a great idea to add an attribute called `template_id` to the class `BotUttered`? This way, I would be able to remove the template_name from the metadata and set the template_id attribute of the event as the template_name.

**Comment by erohmensing** [comment]
> Do you think it would be a great idea to add an attribute called template_id to the class BotUttered? This way, I would be able to remove the template_name from the metadata and set the template_id attribute of the event as the template_name.

Not sure if @tmbo will get back to this, but seems like a solid solution to `I think some sort of template-id should be an event property and not part of the metadata`

**Comment by ViniciusBernardo** [comment]
@erohmensing, Thanks for the feedback. I will try to add an attribute called `template-id` at the `BotUttered`. When I finish I will notify you for another review.

**Comment by tmbo** [comment]
@ViniciusBernardo is this ready for another review?

**Comment by ViniciusBernardo** [comment]
@tmbo, I made the change requested adding a new attribute called `template_id` to the class `BotUttered`, intead of putting the `template_name` into the metadata of a BotUttered object. But that change broke a lot of tests. I fixed some of them but still there are a lot of broken tests at the cli. Do you think it is a good a idea keeping this extra attribute?

**Comment by tmbo** [comment]
needed some additional changes, will be merged as part of #5836

**Pull request closed without merging**
