### PR TITLE
Update the code for tf 2.5

### PR DESCRIPTION
**Pull request by koernerfelicia**
DRAFT PR FOR TESTING

### CODE REVIEW

**Comment by koernerfelicia** [comment]
Note this is a draft for https://github.com/RasaHQ/rasa/issues/8700. Known remaining tasks in order to actually update code for tf 2.5 are:
- [ ] see TODOs marked with 2.5
- [ ] investigate failed memory leak tests
- [ ] remove keras-nightly from lockfile and figure out appropriate substitute

**Comment by TyDunn** [comment]
@koernerfelicia It sounds like we were able to verify the bug was fixed?

**Comment by koernerfelicia** [comment]
@TyDunn not much has changed from my update here: https://github.com/RasaHQ/rasa/issues/8700#issuecomment-863405940

I guess I can say it is fixed in the sense that the code no longer hangs, but I'm not sure if it is a complete fix, since there seem to be some performance issues which *look* like they're related to the original bug, simply because they only occur in the same scenario in which the original bug occurred (anytime we are using our custom CRF layer).

How would you suggest I handle this? I'm thinking I'll update the original issue with the TODO's I wrote above, and add a note about this flakiness?

**Comment by TyDunn** [comment]
> How would you suggest I handle this? I'm thinking I'll update the original issue with the TODO's I wrote above, and add a note about this flakiness?

@koernerfelicia  That seems reasonable to me. And then throw it in the Research inbox?

**Comment by koernerfelicia** [comment]
@TyDunn, done! I updated the issue description to include the list of todos and added a note about the somewhat fishy behaviour around our custom CRF layer.

**Comment by samsucik** [comment]
/modeltest

```yml
include:
 - dataset: ["all"]
   config: ["all"]

**Pull request closed without merging**
