### PR TITLE
Handle evaluation request when no model is loaded

### PR DESCRIPTION
**Pull request by pheel**
**Proposed changes**:
Previously resulted in a unhandled exception when `eval_agent.model_directory` was null.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @rgstephens will take a look at it as soon as possible ✨

**Comment by rgstephens** [comment]
@pheel You need to review and agree to the license/cla for the PR to move forward.

**Comment by pheel** [comment]
@rgstephens It's signed.

**Review by tmbo — APPROVED** [review]
thanks a lot for this improvement :rocket:

**Pull request merged**
