### PR TITLE
Removing Unused Import with name core_cli

### PR DESCRIPTION
**Pull request by deenaik**
**Proposed changes**:
- It should have been removed during cleanup "Refactoring of cmd args." Commit: 5589cfc
Changed train_arguments import as suggested by @federicotdn to fix types failing issue.
Reference: #4152 

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by federicotdn** [comment]
Hey @deenaik, thanks for resubmitting your PR, the only thing I'll add is that you're missing the change from this commit: https://github.com/RasaHQ/rasa/pull/4152/commits/7a9f99386b5069a9f5368cd7c1694dcb793c38f2, which was included in the previous PR.

**Comment by deenaik** [comment]
In fact I have identified 90+ instances of unused imports, I wasn't sure if I should do those changes as individual PRs, in batches or all at once, off course after verifying all tests locally.

For Now I have removed 'BUILTIN_CHANNELS'

**Comment by federicotdn** [comment]
Don't worry about it! For now let's just replicate your previous PR so that we can continue were we left off. Would you mind pushing your changes to remove the `BUILTIN_CHANNELS` import?

**Comment by federicotdn** [comment]
(requesting myself for review as it was requested from me in https://github.com/RasaHQ/rasa/pull/4152)

**Comment by federicotdn** [comment]
Thank you @deenaik for your contribution!

**Pull request merged**
