### PR TITLE
Replace "PERSON" to "PER" in the dimensions

### PR DESCRIPTION
**Pull request by brunohjs**
**Proposed changes**:
- Change "PERSON" to "PER" in the dimensions parameter of the SpacyEntityExtractor component. This is how the component is identifying this entity in Rasa.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @akelad will take a look at it as soon as possible ✨

**Comment by akelad** [comment]
Hey @brunohjs, are you sure about this? As far as I'm aware the spacy entity is `PERSON` and not `PER`?

**Comment by brunohjs** [comment]
> Hey @brunohjs, are you sure about this? As far as I'm aware the spacy entity is `PERSON` and not `PER`?

Yes, I'm sure. I know Spacy considers "PERSON", but Rasa appears as "PER". Look at this print:
image

**Comment by brunohjs** [comment]
Now it's clear. When using the `en_core_web_md` model, the entity is `PERSON`. When using the `pt_core_news_lg` model (my case), the entity is `PER`.

image


So, there is no need to change the documentation. Maybe add a note for this case.

**Comment by akelad** [comment]
oh, that's strange on spacy's part! i think given that the example in the docs is just an example, there's no need to add a note. By default rasa will extract all spacy entities anyways. but let me know if you think there's a better place to make a note of this

**Comment by brunohjs** [comment]
I found in the spaCy documentation the reason for this problem. I found out that the Portuguese models are based on Wikipedia corpus and, because of that, have different entity tags.
image

English models are based on OneNote 5 corpus.

image

Link: https://spacy.io/api/annotation#ner-wikipedia-scheme

Maybe create a forum thread to make a note of that?

**Pull request closed without merging**
