### PR TITLE
Quotes character appear as &quot; in the docs

### PR DESCRIPTION
**Pull request by jppgomes**
Co-authored-by: erico <ericobandeira@hotmail.com>

**Proposed changes**:

issue #8288

In the docs, in the format_message function, quotes appear as &quot; as shown below :
I am from [Berlin]{&quot;entity&quot;: &quot;city&quot;}.
which corresponds to this code where quotes appear ok.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @melindaloubser1 will take a look at it as soon as possible ✨

**Review by melindaloubser1 — APPROVED** [review]
Good catch, thanks!

**Comment by melindaloubser1** [comment]
Ope, I think you want to base it off of another branch though, that's not a branch that's live

**Comment by melindaloubser1** [comment]
My bad, didn't mean to close the PR 🙈

**Comment by melindaloubser1** [comment]
Can you please reopen the PR, but based on `main`?

**Comment by jppgomes** [comment]
@melindaloubser1  Okay, I'll do this

**Pull request closed without merging**
