### PR TITLE
Support for PersistentMenu & GetStartedButton

### PR DESCRIPTION
**Pull request by RogersNtr**
Add support for Persistent Menu and The Get Started Button for Facebook Messenger channel.

**Proposed changes**:
- Add Persistent Menu support on Facebook Messenger
- Add Get started button, which is mandatory for Persistent Menu to work.

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
Thanks for the PR. Looks like it is failing the type check and the code formatting checks, can you please fix those and add a changelog entry as well? Then we can give it a review. Changelog and formatting instructions are in the PR template.

**Comment by erohmensing** [comment]
@RogersNtr are you planning on continuing with this PR?

**Comment by RogersNtr** [comment]
@erohmensing  Yes sure. I will dive again deeply on it this week.

**Comment by amn41** [comment]
just a question - why  should this be part of Rasa? Setting the get started message and persistent menu are just one-time API calls you make, right? Not sure that should be in this codebase

**Comment by RogersNtr** [comment]
> just a question - why should this be part of Rasa? Setting the get started message and persistent menu are just one-time API calls you make, right? Not sure that should be in this codebase

@amn41 Maybe  you're right. I will check this deeply. However, having it there in Rasa will prevent the dev from diving into fb_messenger api that you are using.

**Comment by RogersNtr** [comment]
> > just a question - why should this be part of Rasa? Setting the get started message and persistent menu are just one-time API calls you make, right? Not sure that should be in this codebase
> 
> @amn41 Maybe you're right. I will check this deeply. However, having it there in Rasa will prevent the dev from diving into fb_messenger api that you are using.
After checking, I have made the conclusion that it is not necessary as I have successfully implemented on our custom action server successfully. So I close this pull request.

**Pull request closed without merging**
