### PR TITLE
Add run_eagerly to DIET best models to improve test run time

### PR DESCRIPTION
**Pull request by d61h6k4**
**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by Shmuma — APPROVED** [review]
Looks good. What is the test performance impact?

**Review by twerkmeister — CHANGES_REQUESTED** [review]
`UnexpecTEDPolicy` also needs to have the config paramater :)

**Comment by d61h6k4** [comment]
> Looks good. What is the test performance impact?

Biggest impact comes to the `test-nlu-predictors`, so for ubuntu, python-3.9 number around from **36m 27s** to **12m 0s**

**Comment by d61h6k4** [comment]
> `UnexpecTEDPolicy` also needs to have the config paramater :)

For TensorFlow 2.11 `load` of the `TED` model fails. I will roll back `eager` mode for policies for now.

**Review by twerkmeister — APPROVED** [review]

**Comment by twerkmeister** [comment]
> For TensorFlow 2.11 load of the TED model fails. I will roll back eager mode for policies for now.

@d61h6k4 ok, let's get this in with another PR then. I had to make some changes on the model loading for DIET for a windows version for the tf 2.11 upgrade. Maybe that's causing issues now ~

**Pull request merged**
