### PR TITLE
Pickling exceptions

### PR DESCRIPTION
**Pull request by Mazyod**
**Proposed changes**:
- Fix error thrown when attempting to pickle `UnsupportedModelError` and `InvalidModelError`

I needed to pass exceptions from background processes to be handled in the main process, but it was these exceptions were causing issues during pickling. The fix is easy, and hopefully a better practice especially for a project like rasa which relies on multiprocessing.

Previous error:

```python
def test_exception_pickling():
        exception = UnsupportedModelError("test run")
>       cycled_exception = pickle.loads(pickle.dumps(exception))
E       TypeError: __init__() missing 1 required positional argument: 'message'
```

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by Mazyod** [comment]
Another option is to make `message` an optional argument:
https://stackoverflow.com/a/16245182/456434

**Comment by Mazyod** [comment]
would appreciate any feedback on this PR

**Review by tttthomasssss — CHANGES_REQUESTED** [review]
Hey, apologies this took so long. Thanks very much for submitting this PR.

All looks good codewise - great work 🎸 !  Could you just expand on the purpose of being able to pickle the exceptions in the `changelog`? I.e. just a line or two on why this is needed and what use-case it covers.

**Comment by Mazyod** [comment]
Appreciate it @tttthomasssss. Certainly, I have added the purpose for making exceptions pickleable. I hope the explanation would suffice, otherwise I could try adding more information.

**Review by tttthomasssss — APPROVED** [review]
Awesome, thanks very much for the lightning fast resolution 🚀

**Pull request merged**
