### PR TITLE
Optional Prefix for commands

### PR DESCRIPTION
**Pull request by seanog8**
**Proposed changes**:
- We want to add this optional prefix in order to use with other channels(rocket chat) which do not accept starting `/`

**Status (please check what you already did)**:
- [x ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by alebeta90** [comment]
There is an error in line 27. This why is not passing the checks. Fixing this in a moment

**Comment by alebeta90** [comment]
Hi @erohmensing 

Could give us some light, why the test for Code Formatting failed? do we need to use specific syntax?

I will appreciate some help 

thanks

**Comment by msamogh** [comment]
Thanks for the PR, we'll give it a review as soon as possible.

**Comment by msamogh** [comment]
@alebeta90 You need to use `black` for formatting (https://github.com/rasahq/rasa#code-style).

**Comment by amn41** [comment]
I don't think this is a good solution. I would rather override the `INTENT_MESSAGE_PREFIX` in the rocketchat channel and add docs that on rocketchat you have to start with a `!` instead.

**Comment by alebeta90** [comment]
> Thanks for the PR!
> I see the need for this, I don't like the current solution. I would rather override the `INTENT_MESSAGE_PREFIX` in the rocketchat channel and add docs that on rocketchat you have to start with a `!` instead.

Hi @amn41 

thanks for the suggestion, then the best practice would be to do it in the channel directly.
I will do so , and you can have a look at it!

all the best

**Comment by erohmensing** [comment]
Hi @alebeta90, are you still working on this PR?

**Comment by alebeta90** [comment]
> Hi @alebeta90, are you still working on this PR?

@erohmensing 

sorry for the delay, we have to close the PR, at the end we found out how to make the `/restart` command works with RocketChat without changing anything else. There was an option in rocketchat settings that allow non registered commands to run.

**Comment by erohmensing** [comment]
Great, glad you found a native solution!

**Pull request closed without merging**
