### PR TITLE
update predicted events in test tracker with policy and confidence

### LINKED ISSUE #6899: mapping policy predicts action listen while running, but not in testing
**Rasa version**:

1.10.x

**Issue**:

If I have a mapping in my domain that is not in my stories, it is correctly predicted by the mapping policy, and the action listen is predicted by the mapping policy, as expected, while talking to the bot in rasa shell: 

```
The predicted intent 'bot_challenge' is mapped to  action 'utter_iamabot' in the domain.
2020-10-05 12:12:03 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_MappingPolicy
2020-10-05 12:12:03 DEBUG    rasa.core.processor  - Predicted next action 'utter_iamabot' with confidence 1.00.
2020-10-05 12:12:03 DEBUG    rasa.core.processor  - Action 'utter_iamabot' ended with events '[BotUttered('I am a bot, powered by Rasa.', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1601892723.318448)]'.
2020-10-05 12:12:03 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'intent_mood_unhappy': 1.0, 'prev_action_listen': 1.0}, {'intent_mood_unhappy': 1.0, 'prev_utter_cheer_up': 1.0}, {'intent_mood_unhappy': 1.0, 'prev_utter_did_that_help': 1.0}, {'intent_bot_challenge': 1.0, 'prev_action_listen': 1.0}, {'intent_bot_challenge': 1.0, 'prev_utter_iamabot': 1.0}]
2020-10-05 12:12:03 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2020-10-05 12:12:03 DEBUG    rasa.core.policies.mapping_policy  - The mapped action, 'utter_iamabot', for this intent, 'bot_challenge', was executed last so MappingPolicy is returning to action_listen.
2020-10-05 12:12:03 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_MappingPolicy
2020-10-05 12:12:03 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with confidence 1.00.
```

However, if I have the same training data (the one-turn interaction isn't included in the training data), and a test in which this one-turn interaction occurs, the utterance is correctly predicted by the mapping policy, but the action_listen is not: 
```
2020-10-05 12:09:33 DEBUG    rasa.core.policies.mapping_policy  - The predicted intent 'bot_challenge' is mapped to  action 'utter_iamabot' in the domain.
2020-10-05 12:09:33 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_MappingPolicy
2020-10-05 12:09:33 DEBUG    rasa.core.processor  - Predicted next action 'utter_iamabot' with confidence 1.00.
2020-10-05 12:09:33 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'intent_mood_unhappy': 1.0, 'prev_action_listen': 1.0}, {'intent_mood_unhappy': 1.0, 'prev_utter_cheer_up': 1.0}, {'intent_mood_unhappy': 1.0, 'prev_utter_did_that_help': 1.0}, {'intent_bot_challenge': 1.0, 'prev_action_listen': 1.0}, {'intent_bot_challenge': 1.0, 'prev_utter_iamabot': 1.0}]
2020-10-05 12:09:33 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2020-10-05 12:09:33 DEBUG    rasa.core.policies.mapping_policy  - The mapped action, 'utter_iamabot', for the intent, 'bot_challenge', was executed last, but it was predicted by another policy, 'None', so MappingPolicy is not predicting any action.
2020-10-05 12:09:33 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_TEDPolicy
2020-10-05 12:09:33 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with confidence 0.87.
```

In this case TED still predicted the right action, but if it predicts lower than my core fallback threshold, this would cause my test to fail although it works as expected with the same input data while actually talking to the bot.

### PR DESCRIPTION
**Pull request by erohmensing**
**Proposed changes**:
- fix #6899 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
Debug logs (and non-included log of latest action) before: 
```
2020-10-05 14:47:45 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2020-10-05 14:47:45 DEBUG    rasa.core.policies.mapping_policy  - The predicted intent 'bot_challenge' is mapped to  action 'utter_iamabot' in the domain.
2020-10-05 14:47:45 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_MappingPolicy
2020-10-05 14:47:45 DEBUG    rasa.core.processor  - Predicted next action 'utter_iamabot' with confidence 1.00.
2020-10-05 14:47:45 WARNING  rasa.core.test  - latest action: ActionExecuted(action: utter_iamabot, policy: None, confidence: None)
2020-10-05 14:47:45 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'intent_mood_unhappy': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_cheer_up': 1.0, 'intent_mood_unhappy': 1.0}, {'prev_utter_did_that_help': 1.0, 'intent_mood_unhappy': 1.0}, {'prev_action_listen': 1.0, 'intent_bot_challenge': 1.0}, {'prev_utter_iamabot': 1.0, 'intent_bot_challenge': 1.0}]
2020-10-05 14:47:45 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2020-10-05 14:47:45 DEBUG    rasa.core.policies.mapping_policy  - The mapped action, 'utter_iamabot', for the intent, 'bot_challenge', was executed last, but it was predicted by another policy, 'None', so MappingPolicy is not predicting any action.
2020-10-05 14:47:45 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_TEDPolicy
2020-10-05 14:47:45 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with confidence 0.87.
2020-10-05 14:47:45 WARNING  rasa.core.test  - latest action: ActionExecuted(action: action_listen, policy: None, confidence: None)
2020-10-05 14:47:45 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'prev_utter_cheer_up': 1.0, 'intent_mood_unhappy': 1.0}, {'prev_utter_did_that_help': 1.0, 'intent_mood_unhappy': 1.0}, {'prev_action_listen': 1.0, 'intent_bot_challenge': 1.0}, {'prev_utter_iamabot': 1.0, 'intent_bot_challenge': 1.0}, {'intent_deny': 1.0, 'prev_action_listen': 1.0}]
```
After: 
```
2020-10-05 14:45:24 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2020-10-05 14:45:24 DEBUG    rasa.core.policies.mapping_policy  - The predicted intent 'bot_challenge' is mapped to  action 'utter_iamabot' in the domain.
2020-10-05 14:45:24 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_MappingPolicy
2020-10-05 14:45:24 DEBUG    rasa.core.processor  - Predicted next action 'utter_iamabot' with confidence 1.00.
2020-10-05 14:45:24 WARNING  rasa.core.test  - latest action: ActionExecuted(action: utter_iamabot, policy: policy_2_MappingPolicy, confidence: 1)
2020-10-05 14:45:24 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'prev_action_listen': 1.0, 'intent_mood_unhappy': 1.0}, {'prev_utter_cheer_up': 1.0, 'intent_mood_unhappy': 1.0}, {'prev_utter_did_that_help': 1.0, 'intent_mood_unhappy': 1.0}, {'prev_action_listen': 1.0, 'intent_bot_challenge': 1.0}, {'prev_utter_iamabot': 1.0, 'intent_bot_challenge': 1.0}]
2020-10-05 14:45:24 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2020-10-05 14:45:24 DEBUG    rasa.core.policies.mapping_policy  - The mapped action, 'utter_iamabot', for this intent, 'bot_challenge', was executed last so MappingPolicy is returning to action_listen.
2020-10-05 14:45:24 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_MappingPolicy
2020-10-05 14:45:24 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with confidence 1.00.
2020-10-05 14:45:24 WARNING  rasa.core.test  - latest action: ActionExecuted(action: action_listen, policy: policy_2_MappingPolicy, confidence: 1)
2020-10-05 14:45:24 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'prev_utter_cheer_up': 1.0, 'intent_mood_unhappy': 1.0}, {'prev_utter_did_that_help': 1.0, 'intent_mood_unhappy': 1.0}, {'prev_action_listen': 1.0, 'intent_bot_challenge': 1.0}, {'prev_utter_iamabot': 1.0, 'intent_bot_challenge': 1.0}, {'intent_deny': 1.0, 'prev_action_listen': 1.0}]
```

**Review by Ghostvv — COMMENTED** [review]
As tacky fix, I think it is fine (since MappingPolicy is deprecated), but technically it is a bad practice to update old event on the fly. We should rather feed new `WronglyPredictedAction` into the next prediction.
@tmbo could you please take a look?

**Comment by tmbo** [comment]
I really don't think this is a good idea and the code doesn't look like it is part of the mapping policy, is there any other way we can fix this?

**Comment by Ghostvv** [comment]
> is there any other way we can fix this?
yes, there outer loop that calls this method can be overwritten to use partial_tracker that contains `WronglyPredictedAction` event instead of original event, then it will contain the policy that was used to predict it

**Comment by sara-tagger** [comment]
> We should rather feed new WronglyPredictedAction into the next prediction.

What about the correctly predicted actions though? Those are the ones that are relevant here. 

I'm pretty sure that currently the arguments we pass here: https://github.com/RasaHQ/rasa/pull/6907/files#diff-af205c540e3d6ceb3627cf630700148eR349 will always be `None` for policy, confidence, etc

**Comment by erohmensing** [comment]
Oops, wrong account 🌝

**Comment by Ghostvv** [comment]
> What about the correctly predicted actions as well?

true, then we need to create a new `ActionExecuted` event for correct prediction and feed it into next step

**Comment by erohmensing** [comment]
> However, I'd say the policy should be updated only if predicted action corresponds to gold action

Wouldn't this affect the further actions if you don't have `--fail-on-prediction-errors` though? In production, the fact that mappingpolicy predicted x action (incorrectly) could then further affect the next predictions -- if we don't update the wrongly predicted one with the policy that predicted it, that changes future predictions

**Review by Ghostvv — APPROVED** [review]

**Pull request merged**
