### PR TITLE
Fix v1 docs noindex header

### PR DESCRIPTION
**Pull request by maggo**
Proposed changes:

Fix _redirects so that netlify picks up the noindex, nofollow rule

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @m-vdb will take a look at it as soon as possible ✨

**Review by m-vdb — APPROVED** [review]
🚀

**Review by lunelson — COMMENTED** [review]
@maggo should this file not have been named _headers rather than _redirects? Also, I think `none` is a more sure value than `noindex, nofollow` and maybe remove the comment...

**Comment by maggo** [comment]
@lunelson oh you're absolutely right. Was so used to the unified config file that I didn't look at the filename. 🤦  Also yeah, we can switch to `X-Robots-Tag: none`

Will open another PR

**Pull request merged**
