### PR TITLE
Refactor set states from prototyper.jsx

### LINKED ISSUE #8113: Refactor `prototyper.jsx`
**Description of Problem**: A file named `docs/themes/theme-custom/theme/Prototyper/prototyper.jsx` was written a while ago, and should definitely be refactored.

1.  the name of this component has changed since we introduced it, and it's now called `Playground` — this change should be reflected
2.  we can reduce dependencies (see @gausie's idea here: [https://github.com/RasaHQ/rasa/pull/8109#pullrequestreview-604039453](https://github.com/RasaHQ/rasa/pull/8109#pullrequestreview-604039453))
3.  we can also rewrite it in TypeScript to make more type safe
4.  the Rasa Playground frontend component is not yet merged (
     <g-emoji class="g-emoji" alias="sweat_smile" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f605.png">
     😅 
     </g-emoji>): [https://github.com/RasaHQ/rasa-x/pull/3215](https://github.com/RasaHQ/rasa-x/pull/3215)

### PR DESCRIPTION
**Pull request by santosm46**
**Proposed changes**:
- Refactor set states from `prototyper.jsx`
- Resolve #8113

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @degiz will take a look at it as soon as possible ✨

**Comment by degiz** [comment]
cc @alwx I don't think I have enough knowledge of the topic 😬

**Comment by alwx** [comment]
Hey @santosm46! Thanks for your contribution.

I would only be able to take a proper look and test it next week (probably on Monday/Tuesday).

**Comment by alwx** [comment]
While I find your changes nice, I would like to skip them for now because Playground requires more deep analysis and work — there are many things there that need to be refactored, and this sort of refactoring is more like a code style change. 

I will save it for later and will come back to it once we decide what to do next with the Playground component.

**Pull request closed without merging**
