### PR TITLE
add info on whatsapp in twilio docs

### PR DESCRIPTION
**Pull request by erohmensing**
**Proposed changes**:
- let users know that they can connect to whatsapp through twilio if they have whatsapp business

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by amn41** [comment]
dope!

**Comment by akelad** [comment]
@erohmensing don't you need to pass a "whatsapp" prefix to the numbeR? https://github.com/RasaHQ/rasa/issues/2541#issuecomment-427339203

**Comment by erohmensing** [comment]
I see that [here](https://www.twilio.com/docs/whatsapp/api#using-phone-numbers-with-whatsapp) but the next section about actually using whatsapp in production is confusing, it doesn't explicitly say that you need the prefix? 🤔 

Looks like we can try this btw https://www.twilio.com/docs/whatsapp/api#twilio-sandbox-for-whatsapp (but not the production stuff)

**Comment by akelad** [comment]
which section do you mean? i can't see anything about not needing a prefix

**Comment by erohmensing** [comment]
enabling whatsapp with a twilio number: https://www.twilio.com/docs/whatsapp/api#enabling-whatsapp-with-a-twilio-number

i guess i just dont understand how using whatsapp+twilio number is differnt from "enabling whatsapp on your twilio number" and if you need both or just one in production.

but the examples on the right use whatsapp+ so I guess it's probably still necessary?

**Comment by akelad** [comment]
i would say yes, we should add that to the docs

**Pull request merged**
