### PR TITLE
Add `ThirdPartyTokenizer` to integrate with existing NLP models

### PR DESCRIPTION
**Pull request by izhangzhihao**
**Proposed changes**:
In this PR, we add `ThirdPartyTokenizer` to provide support of existing NLP models.
Related to #453, users could add Stanford CoreNLP support by config the `ThirdPartyTokenizer` with `third_party_service_endpoint`.

Feedbacks are welcome, tests/documentation/changelog will be add/update later.

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by msamogh** [comment]
Thanks for the PR, we'll give it a review as soon as possible. In the meantime, could you also sign the CLA?

**Comment by izhangzhihao** [comment]
CLA signed.

**Comment by izhangzhihao** [comment]
Hi, We are considering to add a `ThirdPartyExtractor` which is similar to this `ThirdPartyTokenizer `. But I just realize that there have a `DucklingHTTPExtractor` already. So it's that make sense to create another Http extractor?

**Comment by tabergma** [comment]
@izhangzhihao Thanks for submitting this PR!
While we like the approach and code, this is something we consider to be outside of the core code. Doing a http round trip for tokenization is something we would rather like to not maintain. I'd suggest you implement this as a custom component if you want to use a different tokenizer (https://rasa.com/docs/rasa/api/custom-nlu-components/#id1).

**Comment by izhangzhihao** [comment]
Ok, I understand that. But as I see, there are some common demands about the `http comment` for support existing NLP models. So I'm suggesting to add sample code to somewhere like https://github.com/RasaHQ/rasa-demo. Or in another way, publish a third party pip library that contains the `http comment`.

**Comment by tabergma** [comment]
We are actually planning to collect useful code from our contributors in a central place so that we wouldn't maintain the actual code ourselves but people could find it easier and give some reputation points for devs behind the code. Unfortunately, we don't have anything in place yet.
Our suggestion: You create a GitHub repo and add your custom component there. If you sent us the link we could share it with the community and add it to our newsletters. What do you think?

**Comment by izhangzhihao** [comment]
Great, I've created a repo [rasa-contrib](https://github.com/izhangzhihao/rasa-contrib).

**Comment by tabergma** [comment]
Thanks, I'll make sure that it is shared with the community. Thanks for implementing it!

**Comment by tabergma** [comment]
If you want you can post the solution yourself in our forum here: https://forum.rasa.com/c/rasa/tutorials
Otherwise, I'll do it tomorrow. Do you have a forum account? If yes, can you share your user name with me, so that I can link you in the post? Thanks.

**Comment by izhangzhihao** [comment]
I don't have a forum account. So please do it for me.

**Pull request closed without merging**
