### PR TITLE
Reduce model_confidence softmax warning in CI Tests

### LINKED ISSUE #8146: Eliminate `model_confidence` softmax warning in CI Tests
**Python version**:
Python 3.6
Python 3.7

**Operating system** (windows, osx, ...):
Ubuntu
Windows

**Issue**:
This Issue is part of the effort to close the [Issue#7738](https://github.com/RasaHQ/rasa/issues/7738) hence to reduce the amount of warnings that are raised when running all tests in the CI. From a first investigation, it seems that this warning (_UserWarning: model_confidence is set to `softmax`. It is recommended to try using `model_confidence=linear_norm` to make it easier to tune fallback thresholds._) for which the current Issue was opened, had 150 occurrences but in a latest CI run it appears in only 81 tests.

**Possible Solutions**:
- I assume changing the `model_confidence` to `linear_norm` will eliminate the warning.
- However, from the moment this description is written until this issue is handled, the recommended value of `model_confidence` might have changed since this depends on the latest findings from the research team. So maybe rerun the CI tests to see the latest recommendation or one of the tests below.

**Error (including full traceback)**:
```
2021-03-09T05:38:31.3112981Z rasa/utils/train_utils.py:428: 81 tests with warnings
2021-03-09T05:38:31.3114236Z   /home/runner/work/rasa/rasa/rasa/utils/train_utils.py:428: UserWarning: model_confidence is set to `softmax`. It is recommended to try using `model_confidence=linear_norm` to make it easier to tune fallback thresholds.
2021-03-09T05:38:31.3115429Z     category=UserWarning,
```

**Command or request that led to error**:
- The warning can be found in any of the following CI tests log files :
   - 1_Run Tests (ubuntu-latest, 3.6, test-non-training).txt
   - 3_Run Tests (ubuntu-latest, 3.7, test-non-training).txt
   - 5_Run Tests (ubuntu-latest, 3.8, test-non-training).txt
   - 9_Run Tests (windows-latest, 3.7, test-non-training).txt
- Also, the warning can be reproduced when running one of the tests below:
```
pytest tests/utils/test_train_utils.py::test_confidence_loss_settings
pytest tests/utils/test_train_utils.py::test_confidence_similarity_settings
pytest tests/core/test_training.py::test_training_script_with_max_history_set
```

### PR DESCRIPTION
**Pull request by iurisevero**
Resolve #8146 
**Proposed changes**:
- Add pytests.warns to catch the softmax warning.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @TyDunn will take a look at it as soon as possible ✨

**Comment by TyDunn** [comment]
Nice contribution! I saw you have been chatting with @wochinge about this in the issue. Please tag him when you are ready for review

**Comment by wochinge** [comment]
@iurisevero How is it going with the change?

**Comment by iurisevero** [comment]
Hey, I've been very busy these last few days and couldn't take a look at it, sorry. :/
This weekend I'll have time and I'll see what I can do.

**Comment by iurisevero** [comment]
@wochinge I take a time to work on this issue and I don't think I can keep working on it :/
I just can't find what is raising the warning and try to do it on the blind is not worth it... 
I let my notes here to help anyone who takes it in the future:

```
2021-06-12T17:51:09.2841949Z rasa/utils/train_utils.py:566
2021-06-12T17:51:09.2842477Z rasa/utils/train_utils.py:566
2021-06-12T17:51:09.2843542Z tests/core/featurizers/test_single_state_featurizers.py::test_single_state_featurizer_with_interpreter_state_with_action_listen
2021-06-12T17:51:09.2844985Z tests/core/featurizers/test_single_state_featurizers.py::test_single_state_featurizer_with_entity_roles_and_groups
2021-06-12T17:51:09.2846415Z tests/core/featurizers/test_single_state_featurizers.py::test_single_state_featurizer_with_interpreter_state_not_with_action_listen
2021-06-12T17:51:09.2847888Z tests/core/featurizers/test_single_state_featurizers.py::test_single_state_featurizer_with_bilou_entity_roles_and_groups
2021-06-12T17:51:09.2849320Z tests/core/featurizers/test_single_state_featurizers.py::test_single_state_featurizer_with_interpreter_state_with_no_action_name
2021-06-12T17:51:09.2850765Z tests/core/featurizers/test_single_state_featurizers.py::test_single_state_featurizer_uses_regex_interpreter
2021-06-12T17:51:09.2852432Z   /home/runner/work/rasa/rasa/rasa/utils/train_utils.py:566: UserWarning: model_confidence is set to `softmax`. It is recommended to try using `model_confidence=linear_norm` to make it easier to tune fallback thresholds.
2021-06-12T17:51:09.2853670Z     category=UserWarning,
2021-06-12T17:51:09.2854032Z 

2021-06-12T17:56:01.6598135Z tests/core/policies/test_ted_policy.py: 72 warnings
2021-06-12T17:56:01.6599370Z   /home/runner/work/rasa/rasa/rasa/utils/train_utils.py:566: UserWarning: model_confidence is set to `softmax`. It is recommended to try using `model_confidence=linear_norm` to make it easier to tune fallback thresholds.
2021-06-12T17:56:01.6600511Z     category=UserWarning,
2021-06-12T17:56:01.6600818Z 

2021-06-12T17:54:21.4764858Z tests/nlu/classifiers/test_diet_classifier.py: 18 warnings
2021-06-12T17:54:21.4765493Z tests/nlu/selectors/test_selectors.py: 12 warnings
2021-06-12T17:54:21.4766681Z   /home/runner/work/rasa/rasa/rasa/utils/train_utils.py:566: UserWarning: model_confidence is set to `softmax`. It is recommended to try using `model_confidence=linear_norm` to make it easier to tune fallback thresholds.
2021-06-12T17:54:21.4773392Z     category=UserWarning,
2021-06-12T17:54:21.4773727Z

2021-06-12T17:53:56.7021105Z tests/test_model_training.py: 9 warnings
    tests/test_model_training.py::test_model_finetuning_core[True]
    tests/test_model_training.py::test_model_finetuning_core[True]
    tests/test_model_training.py::test_model_finetuning_core[False]
    tests/test_model_training.py::test_model_finetuning_core_with_default_epochs
    tests/test_model_training.py::test_model_finetuning_nlu[True]
    tests/test_model_training.py::test_model_finetuning_nlu[True]
    tests/test_model_training.py::test_model_finetuning_nlu[False]
    tests/test_model_training.py::test_model_finetuning_nlu_new_label_to_domain_only
    tests/test_model_training.py::test_model_finetuning_nlu_with_default_epochs
    /mnt/c/Users/NB/Desktop/Faculdade/semestre_7/GCES/rasa/rasa/utils/train_utils.py:566: UserWarning: model_confidence is set to `softmax`. It is recommended to try using `model_confidence=linear_norm` to make it easier to tune fallback thresholds.
        category=UserWarning,
2021-06-12T17:53:56.7021706Z tests/core/test_examples.py: 3 warnings
    tests/core/test_examples.py::test_moodbot_example
    tests/core/test_examples.py::test_formbot_example
    tests/core/test_examples.py::test_formbot_example
    /mnt/c/Users/NB/Desktop/Faculdade/semestre_7/GCES/rasa/rasa/utils/train_utils.py:566: UserWarning: model_confidence is set to `softmax`. It is recommended to try using `model_confidence=linear_norm` to make it easier to tune fallback thresholds.
        category=UserWarning,
2021-06-12T17:53:56.7023037Z tests/nlu/test_train.py: 9 warnings
    tests/nlu/test_train.py::test_train_persist_load_parse[en-pipeline1]
    tests/nlu/test_train.py::test_train_persist_load_parse[en-pipeline3]
    tests/nlu/test_train.py::test_train_persist_load_parse_non_windows[en-pipeline0]
    tests/nlu/test_train.py::test_train_model_without_data[en-pipeline1]
    tests/nlu/test_train.py::test_train_model_without_data[en-pipeline3]
    tests/nlu/test_train.py::test_train_model_without_data_non_windows[en-pipeline0]
    tests/nlu/test_train.py::test_load_and_persist_without_train[en-pipeline1]
    tests/nlu/test_train.py::test_load_and_persist_without_train[en-pipeline3]
    tests/nlu/test_train.py::test_load_and_persist_without_train_non_windows[en-pipeline0]
    /mnt/c/Users/NB/Desktop/Faculdade/semestre_7/GCES/rasa/rasa/utils/train_utils.py:566: UserWarning: model_confidence is set to `softmax`. It is recommended to try using `model_confidence=linear_norm` to make it easier to tune fallback thresholds.
        category=UserWarning,
2021-06-12T17:53:56.7024224Z   /home/runner/work/rasa/rasa/rasa/utils/train_utils.py:566: UserWarning: model_confidence is set to `softmax`. It is recommended to try using `model_confidence=linear_norm` to make it easier to tune fallback thresholds.
2021-06-12T17:53:56.7025389Z     category=UserWarning,
2021-06-12T17:53:56.7025713Z 

2021-06-12T17:55:26.0155804Z tests/test_validator.py: 4 warnings
2021-06-12T17:55:26.0157107Z tests/core/test_evaluation.py: 7 warnings
2021-06-12T17:55:26.0158409Z tests/core/test_test.py: 1 warning
2021-06-12T17:55:26.0159026Z tests/nlu/test_components.py: 5 warnings
2021-06-12T17:55:26.0160326Z tests/nlu/test_evaluation.py: 4 warnings
2021-06-12T17:55:26.0161626Z   /home/runner/work/rasa/rasa/rasa/utils/train_utils.py:566: UserWarning: model_confidence is set to `softmax`. It is recommended to try using `model_confidence=linear_norm` to make it easier to tune fallback thresholds.
2021-06-12T17:55:26.0162886Z     category=UserWarning,
2021-06-12T17:55:26.0163248Z
```

The log from all files where the warning was raised when running the tests.

**Comment by wochinge** [comment]
> I just can't find what is raising the warning and try to do it on the blind is not worth it...

Could it be the used fixtures? E.g. the `test_single_state_featurizer_uses_regex_interpreter` uses a fixture called `unpacked_trained_spacybot_path` which in turn uses a fixture `trained_spacybot_path` which trains a model using `TEDPolicy`.

**Comment by iurisevero** [comment]
> test_single_state_featurizer_uses_regex_interpreter
Probably, cause I tried to catch the warning in every line of ```tests/core/featurizers/test_single_state_featurizers.py::test_single_state_featurizer_with_interpreter_state_with_action_listen``` and it failed in all test. The warning is there, but no line of the function raised it.

**Comment by wochinge** [comment]
👍🏻 Then we should eliminate the warnings in the fixtures. We've recently dropped a lot deprecated code which resolves most of these warnings.

**Comment by iurisevero** [comment]
Hey, @wochinge, sorry for the late response. I took a look at the changes that were made and realize that there is no warning anymore, actually, it has gone for a while and I haven't noticed it before cause nothing broke until this last merge.

With that said, I believe that both the issue and the PR can be closed (I'll just wait for an answer to close it).

The `FutureWarning`, that "replaced" the `UserWarning` I was working on, is been raised in the following functions:
```
9_Run Tests (test-policies, ubuntu-latest, 3.7).txt

2021-07-31T13:32:25.9282225Z tests/core/policies/test_ted_policy.py::TestTEDPolicyLinearNormConfidence::test_training_with_no_intent
2021-07-31T13:32:25.9283572Z tests/core/policies/test_ted_policy.py::TestTEDPolicyLinearNormConfidence::test_similarity_type
2021-07-31T13:32:25.9284905Z tests/core/policies/test_ted_policy.py::TestTEDPolicyLinearNormConfidence::test_featurizer
2021-07-31T13:32:25.9286251Z tests/core/policies/test_ted_policy.py::TestTEDPolicyLinearNormConfidence::test_persist_and_load[False]
2021-07-31T13:32:25.9287600Z tests/core/policies/test_ted_policy.py::TestTEDPolicyLinearNormConfidence::test_persist_and_load[True]
2021-07-31T13:32:25.9288979Z tests/core/policies/test_ted_policy.py::TestTEDPolicyLinearNormConfidence::test_persist_and_load_empty_policy
2021-07-31T13:32:25.9290958Z   /home/runner/work/rasa/rasa/rasa/utils/train_utils.py:627: FutureWarning: model_confidence is set to `linear_norm`. We introduced this option in Rasa Open Source 2.3.0, but have identified multiple problems with it based on user feedback. Therefore, `model_confidence=linear_norm` is now deprecated and will be removed in Rasa Open Source `3.0.0`.Please use `model_confidence=softmax` instead.
2021-07-31T13:32:25.9292736Z     f"{MODEL_CONFIDENCE} is set to `{LINEAR_NORM}`. We "

17_Run Tests (test-nlu-predictors, ubuntu-latest, 3.7).txt

2021-07-31T13:27:48.9437828Z tests/nlu/classifiers/test_diet_classifier.py::test_inner_linear_normalization[classifier_params0-data/test_moodbot/data/nlu.yml]
2021-07-31T13:27:48.9439319Z tests/nlu/classifiers/test_diet_classifier.py::test_train_tensorboard_logging[epoch]
2021-07-31T13:27:48.9440371Z tests/nlu/classifiers/test_diet_classifier.py::test_train_tensorboard_logging[batch]
2021-07-31T13:27:48.9441350Z tests/nlu/selectors/test_selectors.py::test_train_model_checkpointing
2021-07-31T13:27:48.9442820Z tests/nlu/selectors/test_selectors.py::test_cross_entropy_with_linear_norm[classifier_params0-9]
2021-07-31T13:27:48.9445079Z   /home/runner/work/rasa/rasa/rasa/utils/train_utils.py:627: FutureWarning: model_confidence is set to `linear_norm`. We introduced this option in Rasa Open Source 2.3.0, but have identified multiple problems with it based on user feedback. Therefore, `model_confidence=linear_norm` is now deprecated and will be removed in Rasa Open Source `3.0.0`.Please use `model_confidence=softmax` instead.
2021-07-31T13:27:48.9446939Z     f"{MODEL_CONFIDENCE} is set to `{LINEAR_NORM}`. We "

25_Run Tests (test-other-unit-tests, ubuntu-latest, 3.7).txt

2021-07-31T13:26:49.3148163Z tests/utils/test_train_utils.py::test_confidence_loss_settings[component_config3-False]
2021-07-31T13:26:49.3149414Z tests/utils/test_train_utils.py::test_confidence_loss_settings[component_config4-False]
2021-07-31T13:26:49.3150659Z tests/utils/test_train_utils.py::test_confidence_loss_settings[component_config5-False]
2021-07-31T13:26:49.3151924Z tests/utils/test_train_utils.py::test_confidence_similarity_settings[component_config2-False]
2021-07-31T13:26:49.3153238Z tests/utils/test_train_utils.py::test_confidence_similarity_settings[component_config3-False]
2021-07-31T13:26:49.3155165Z   /home/runner/work/rasa/rasa/rasa/utils/train_utils.py:627: FutureWarning: model_confidence is set to `linear_norm`. We introduced this option in Rasa Open Source 2.3.0, but have identified multiple problems with it based on user feedback. Therefore, `model_confidence=linear_norm` is now deprecated and will be removed in Rasa Open Source `3.0.0`.Please use `model_confidence=softmax` instead.
2021-07-31T13:26:49.3156883Z     f"{MODEL_CONFIDENCE} is set to `{LINEAR_NORM}`. We "
```

If you open an issue about it, this info may be useful.

**Comment by wochinge** [comment]
Thanks for investigating! Created the issue [here](https://github.com/RasaHQ/rasa/issues/9447)

**Pull request closed without merging**
