### PR TITLE
Fix `rasa data validate` for rules containing default actions as `active_loop`

### LINKED ISSUE #10430: rasa data validate causes error with "action_two_stage_fallback"
### Rasa Open Source version

3.0.0

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

When using the two-stage fallback, I get the following error when running `rasa data validate`

UserWarning: The form 'action_two_stage_fallback' is used in the 'Activate two stage fallback' block, but it is not listed in the domain file. You should add it to your domain file!

I have this in my rules:

version: "3.0" rules:

*   rule: Activate two stage fallback steps:
*   intent: nlu_fallback
*   action: action_two_stage_fallback
*   active_loop: action_two_stage_fallback

### Command / Request

<pre>rasa data validate</pre>

### Relevant log output

 _No response_

### PR DESCRIPTION
**Pull request by ancalita**
**Proposed changes**:
- Fixes #10430 

**Status (please check what you already did)**:
- [X] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [X] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by melindaloubser1 — APPROVED** [review]

**Review by losterloh — CHANGES_REQUESTED** [review]
It seems like the test that was added does not actually test the bug / changed behavior, since the test runs green when the change in `validator.py` is reverted.

**Comment by ancalita** [comment]
@losterloh Good catch! For some reason, the rule that I add is not detected: it gets transformed in a `StoryGraph` with 0 steps, which is why the test runs green since the whole for loop in the verify method gets bypassed. I'll investigate further 👍🏼

**Comment by ancalita** [comment]
> the test that was added does not actually test the bug / changed behavior, since the test runs green when the change in validator.py is reverted.

Found the culprit - I was modifying by mistake the string parameter `file_name` to a Path, then the importer didn't recognise the file as a stories/rules file and therefore initialised a StoryGraph with 0 steps.  Fixed now, if you revert the change and run the test, it fails.

**Review by losterloh — APPROVED** [review]
🚀 💯

**Pull request merged**
