### PR TITLE
Including relative path to the data files in Building Assistants Tutorial

### PR DESCRIPTION
**Pull request by brunogcarneiro**
The absence of the path caused a question in the Rasa forum to be openned. (forum.rasa.com/t/getting-a-json-response-instead-of-a-text-message/29730/3)

**Proposed changes**:
- Includes the path for training data (nlu.md and stories.md) to help beginners to find or crate these files in the correct place.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [X] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @koaning will take a look at it as soon as possible ✨

**Comment by brunogcarneiro** [comment]
> Thanks for the helpful clarification! Congrats on your first contribution 🎉

@erohmensing Thank you for your support! Could you help me once more? 

A check in this Pull Request has failed: "Countinuous Itegration / Code Quality". I checked the details but I can't figure out what was wrong. The problem occurred in the "Test docs" step.

What should I do?

**Comment by brunogcarneiro** [comment]
Hello again @erohmensing ! A new commit in the master branch caused my PR to be outdated. Then, the GitHub asked me to update my PR and it caused all checks to run again. This time, all checks have passed. 

If it happen again, maybe this situation should be reported for someone.

Thanks again!

**Comment by erohmensing** [comment]
No problem @brunogcarneiro , the failing before was due to a link in our docs that wasn't responding (their servers must have been down, because the link is rendering again). When you updated the branch, it re-tested and everything was okay. Thanks for your concern!

**Pull request merged**
