### PR TITLE
Add template file

### LINKED ISSUE #9391: ci: the lack of template file causes the "Automatic main branch merger" workflow fails on release branches
**The Problem:**

The  "Automatic main branch merger" workflow fails on release branches.

See the workflow runs:
https://github.com/RasaHQ/rasa/actions/workflows/automatic-release-to-main-merger.yml

**The solution:**
Cherry-pick the file `PULL_REQUEST_AUTOMATIC_TEMPLATE.md` to release branches. 
Probably need to manually merge those unmerged changes on release branches to the `main` branch.

### PR DESCRIPTION
**Pull request by HotThoughts**
**Proposed changes**:
- fix #9391

### CODE REVIEW

**Comment by HotThoughts** [comment]
@mprazz Tag you here because you know the workflow that backports release branches to the main. It is failing because of the lack of a template file.

**Comment by HotThoughts** [comment]
Duplicate of https://github.com/RasaHQ/rasa/pull/9434

**Comment by mprazz** [comment]
Just pushed a fix for adding the template on `2.8.x` -- this is the latest release branch, should be enough to port it there.
Reason behind this: Katja implemented the workflow before we branched out to 2.8.x, but she made the fix that added the PR template after we made the branch :sweat_smile:

**Comment by mprazz** [comment]
Sorry to have duplicated your work, I just saw this notif after noticing the same thing :pray:

**Pull request closed without merging**
