### PR TITLE
allow other fields in utterance in addition to `custom` field

### PR DESCRIPTION
**Pull request by wochinge**
**Proposed changes**:
- remove `return` so other message keys are actually respected

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
I know I had a reason to exit, but I really can't figure it out now, so I think it must have been something I ended up not using in the code.... while you're at it i would move it to that the bottom so that text comes before whatever custom stuff. What made you hit this issue? Just curious.

**Comment by wochinge** [comment]
> while you're at it i would move it to that the bottom so that text comes before whatever custom stuff. What made you hit this issue? Just curious.

but the order doesn't really matter, does it?

> What made you hit this issue? Just curious.

Currently doing a workshop, and they had an issue with custom output channels where we discovered it.

**Comment by erohmensing** [comment]
I mean the order will affect the order of the output, I would expect a bigger use case where someone would want text and then their custom thing to show rather than the other way around. In general it would make more sense if this logic could take into account the order of the fields in the domain, but that stuff is a dict so i don't know if it's possible. what are they using in addition to custom?

**Comment by wochinge** [comment]
@erohmensing Struggled a bit with the order, but should not be fine. Could you please have another look?

**Comment by wochinge** [comment]
feel free to merge if everything is alright btw

**Comment by wochinge** [comment]
@erohmensing Thanks for finishing this up!

**Pull request merged**
