### PR TITLE
rename occurrences of "master" to "main"

### PR DESCRIPTION
**Pull request by m-vdb**
Relates to https://github.com/RasaHQ/rasa/issues/6028

**Proposed changes**:
- Rename occurrences of `master` in the repository
- Some occurrences of `master` deal with other repositories outside of our control, so we can't change them.
- Some changes touch workflows and Docker builds.
- When this PR is ready for merging, we should:
  - [x] Make an announcement on Slack
  - [x] Rename the `master` branch to `main` in the repo configuration [here](https://github.com/RasaHQ/rasa/settings/branches)
  - [ ] Merge this PR
  - [ ] Merge [this Rasa SDK PR](https://github.com/RasaHQ/rasa-sdk/pull/393)
- ⚠️ **documentation link check fails on the PR because the `main` branch doesn't exist yet. I think it's fine and we can force-merge, and make sure the check passes after the PR is merged. If we decide to wait, the repo might stay in a weird state for too long**

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by tczekajlo** [comment]
@m-vdb there is one test that failed - https://github.com/RasaHQ/rasa/pull/7742/checks?check_run_id=1709962917

**Review by wochinge — APPROVED** [review]
Thank you 🙌🏻

**Comment by m-vdb** [comment]
@tczekajlo will you have time for a quick review this week? This touches some of the workflows you set up I think

**Review by tczekajlo — APPROVED** [review]
LGTM 🍏

**Pull request merged**
