### PR TITLE
Mine hard negatives instead of random negatives

### PR DESCRIPTION
**Pull request by dakshvar22**
**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by dakshvar22** [comment]
/modeltest

```yml
include:
 - dataset: ["all"]
   config: ["all"]
```

**Comment by dakshvar22** [comment]
Closing the issue as there is no improvement in the performance.

**Comment by dakshvar22** [comment]
Current experiments running with same configuration as above but with reduced number of epochs to 25 for DIET and 100 for EmbeddingIntent

**Comment by tczekajlo** [comment]
@dakshvar22 restored report

Dataset: `Carbon Bot`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m19s`, train: `11m17s`, total: `12m36s` |0.7806 (0.00)|0.6260 (-0.13)|0.5497 (-0.01)|
| `BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m19s`, train: `5m14s`, total: `6m33s` |0.7748 (-0.02)|0.8242 (0.06)|0.5430 (-0.03)|
| `ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `48s`, train: `9m20s`, total: `10m8s` |0.8369 (0.00)|0.6260 (0.00)|0.6179 (0.00)|
| `ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `55s`, train: `5m28s`, total: `6m23s` |0.8214 (0.00)|0.8421 (0.00)|0.6133 (0.00)|
| `Sparse + BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m23s`, train: `10m44s`, total: `12m7s` |0.7922 (-0.01)|0.6260 (-0.13)|0.5497 (-0.02)|
| `Sparse + BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m28s`, train: `5m51s`, total: `7m18s` |0.7883 (-0.02)|0.8571 (0.06)|0.5894 (`no data`)|
| `Sparse + ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `51s`, train: `10m24s`, total: `11m15s` |0.8369 (0.00)|0.6260 (0.00)|0.6093 (0.00)|
| `Sparse + ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m1s`, train: `6m5s`, total: `7m5s` |0.8155 (0.00)|0.8645 (0.00)|0.6159 (0.00)|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `28s`, train: `8m37s`, total: `9m4s` |0.7340 (-0.01)|0.6260 (-0.13)|0.5166 (`no data`)|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `36s`, train: `5m2s`, total: `5m37s` |0.7456 (0.00)|0.7619 (0.05)|0.5629 (`no data`)|

Dataset: `Hermit`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `3m28s`, train: `45m18s`, total: `48m46s` |0.8987 (0.00)|0.7504 (0.00)|`no data`|
| `BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `2m46s`, train: `18m46s`, total: `21m32s` |0.9071 (0.01)|0.8043 (0.00)|`no data`|
| `ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m36s`, train: `43m19s`, total: `44m55s` |0.8941 (0.00)|0.7504 (0.00)|`no data`|
| `ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m40s`, train: `18m23s`, total: `20m2s` |0.9080 (0.00)|0.8125 (0.00)|`no data`|
| `Sparse + BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `3m20s`, train: `46m8s`, total: `49m27s` |0.8829 (0.00)|0.7504 (0.00)|`no data`|
| `Sparse + BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `2m43s`, train: `19m8s`, total: `21m51s` |0.8894 (0.02)|0.8017 (0.01)|`no data`|
| `Sparse + ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m37s`, train: `45m19s`, total: `46m55s` |0.3699 (0.00)|0.7504 (0.00)|`no data`|
| `Sparse + ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m44s`, train: `19m25s`, total: `21m9s` |0.9006 (0.00)|0.7999 (0.00)|`no data`|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `56s`, train: `40m36s`, total: `41m31s` |0.8550 (0.03)|0.7504 (0.00)|`no data`|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m7s`, train: `17m46s`, total: `18m53s` |0.8532 (0.02)|0.7571 (0.00)|`no data`|

Dataset: `Private 1`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m48s`, train: `12m18s`, total: `14m6s` |0.9044 (-0.00)|0.9612 (-0.00)|`no data`|
| `BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m59s`, train: `5m18s`, total: `7m17s` |0.9200 (0.00)|0.9724 (-0.00)|`no data`|
| `Spacy + DIET(bow) + ResponseSelector(bow)`<br> test: `1m13s`, train: `11m52s`, total: `13m4s` |0.7370 (-0.06)|0.9574 (0.00)|`no data`|
| `Spacy + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m25s`, train: `5m52s`, total: `7m17s` |0.8222 (-0.02)|0.9270 (-0.00)|`no data`|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `20s`, train: `11m15s`, total: `11m34s` |0.9012 (0.00)|0.9612 (-0.00)|`no data`|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `35s`, train: `5m7s`, total: `5m41s` |0.9023 (0.00)|0.9709 (-0.00)|`no data`|
| `Sparse + Spacy + DIET(bow) + ResponseSelector(bow)`<br> test: `1m14s`, train: `12m37s`, total: `13m51s` |0.8981 (0.00)|0.9574 (0.00)|`no data`|
| `Sparse + Spacy + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m27s`, train: `6m12s`, total: `7m39s` |0.8971 (-0.01)|0.9683 (-0.00)|`no data`|

Dataset: `Private 2`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m47s`, train: `20m6s`, total: `21m53s` |0.8703 (-0.01)|`no data`|`no data`|
| `Spacy + DIET(bow) + ResponseSelector(bow)`<br> test: `1m16s`, train: `15m16s`, total: `16m32s` |0.4469 (-0.14)|`no data`|`no data`|
| `Spacy + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m21s`, train: `8m52s`, total: `10m12s` |0.6967 (-0.01)|`no data`|`no data`|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `29s`, train: `12m49s`, total: `13m18s` |0.8542 (0.00)|`no data`|`no data`|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `32s`, train: `7m4s`, total: `7m35s` |0.8467 (-0.01)|`no data`|`no data`|
| `Sparse + Spacy + DIET(bow) + ResponseSelector(bow)`<br> test: `1m20s`, train: `16m52s`, total: `18m12s` |0.8532 (0.00)|`no data`|`no data`|
| `Sparse + Spacy + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m25s`, train: `9m17s`, total: `10m42s` |0.8478 (-0.01)|`no data`|`no data`|

Dataset: `Private 3`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `51s`, train: `3m1s`, total: `3m52s` |0.9177 (0.01)|`no data`|`no data`|
| `BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `53s`, train: `1m14s`, total: `2m7s` |0.9342 (0.12)|`no data`|`no data`|
| `Spacy + DIET(bow) + ResponseSelector(bow)`<br> test: `1m14s`, train: `3m28s`, total: `4m42s` |0.0288 (-0.04)|`no data`|`no data`|
| `Spacy + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m14s`, train: `1m52s`, total: `3m6s` |0.4568 (0.19)|`no data`|`no data`|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `27s`, train: `2m55s`, total: `3m22s` |0.8642 (0.02)|`no data`|`no data`|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `28s`, train: `1m10s`, total: `1m37s` |0.8807 (0.06)|`no data`|`no data`|
| `Sparse + Spacy + DIET(bow) + ResponseSelector(bow)`<br> test: `1m16s`, train: `3m48s`, total: `5m3s` |0.8642 (0.02)|`no data`|`no data`|
| `Sparse + Spacy + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m17s`, train: `1m57s`, total: `3m14s` |0.8807 (0.02)|`no data`|`no data`|

Dataset: `Sara`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `2m4s`, train: `17m48s`, total: `19m51s` |0.8697 (0.00)|0.8683 (0.00)|0.8783 (0.01)|
| `BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `2m19s`, train: `7m59s`, total: `10m18s` |0.8590 (0.01)|0.8828 (-0.01)|0.8870 (0.01)|
| `ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m14s`, train: `19m19s`, total: `20m32s` |0.8972 (0.00)|0.8683 (0.00)|0.9304 (0.00)|
| `ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m24s`, train: `8m35s`, total: `9m58s` |0.8825 (0.00)|0.9150 (0.00)|0.9304 (0.00)|
| `Sparse + BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `2m12s`, train: `19m35s`, total: `21m47s` |0.8717 (-0.00)|0.8683 (0.00)|0.9109 (0.01)|
| `Sparse + BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `2m24s`, train: `8m55s`, total: `11m18s` |0.8678 (-0.01)|0.8843 (-0.01)|0.9043 (0.01)|
| `Sparse + ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m22s`, train: `21m21s`, total: `22m43s` |0.8834 (0.00)|0.8683 (0.00)|0.9261 (0.00)|
| `Sparse + ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m36s`, train: `9m27s`, total: `11m2s` |0.8893 (0.00)|0.9231 (0.00)|0.9283 (0.00)|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `40s`, train: `17m43s`, total: `18m23s` |0.8325 (-0.00)|0.8683 (0.00)|0.8543 (0.02)|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `52s`, train: `8m0s`, total: `8m52s` |0.8178 (-0.02)|0.8405 (-0.01)|0.8761 (0.02)|

Dataset: `curekart_full`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m1s`, train: `2m27s`, total: `3m28s` |0.8233 (0.00)|`no data`|`no data`|
| `BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m3s`, train: `1m7s`, total: `2m9s` |0.8281 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `38s`, train: `2m34s`, total: `3m12s` |0.8408 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `42s`, train: `1m18s`, total: `1m59s` |0.8610 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m3s`, train: `2m35s`, total: `3m37s` |0.8399 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m5s`, train: `1m14s`, total: `2m18s` |0.8425 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `42s`, train: `2m48s`, total: `3m29s` |0.8661 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `43s`, train: `1m30s`, total: `2m13s` |0.8600 (0.00)|`no data`|`no data`|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `18s`, train: `2m12s`, total: `2m29s` |0.8322 (0.00)|`no data`|`no data`|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `20s`, train: `1m2s`, total: `1m21s` |0.8094 (0.00)|`no data`|`no data`|

Dataset: `curekart_subset`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m2s`, train: `1m53s`, total: `2m54s` |0.8018 (0.00)|`no data`|`no data`|
| `BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m4s`, train: `58s`, total: `2m2s` |0.8116 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `39s`, train: `2m1s`, total: `2m39s` |0.8402 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `43s`, train: `1m23s`, total: `2m5s` |0.8296 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m3s`, train: `2m4s`, total: `3m6s` |0.8264 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m7s`, train: `1m3s`, total: `2m10s` |0.8161 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `41s`, train: `2m8s`, total: `2m49s` |0.8456 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `44s`, train: `1m15s`, total: `1m58s` |0.8331 (0.00)|`no data`|`no data`|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `18s`, train: `1m43s`, total: `2m1s` |0.7928 (0.00)|`no data`|`no data`|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `19s`, train: `51s`, total: `1m10s` |0.7892 (0.00)|`no data`|`no data`|

Dataset: `powerplay11_full`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `57s`, train: `1m57s`, total: `2m54s` |0.5127 (0.00)|`no data`|`no data`|
| `BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `59s`, train: `1m0s`, total: `1m59s` |0.5418 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `49s`, train: `2m11s`, total: `3m0s` |0.5355 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `49s`, train: `1m7s`, total: `1m55s` |0.5464 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `59s`, train: `2m7s`, total: `3m5s` |0.6594 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m0s`, train: `1m4s`, total: `2m3s` |0.5745 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `49s`, train: `2m18s`, total: `3m7s` |0.5683 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `49s`, train: `1m11s`, total: `2m0s` |0.4945 (0.00)|`no data`|`no data`|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `30s`, train: `1m52s`, total: `2m22s` |0.5902 (0.00)|`no data`|`no data`|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `31s`, train: `53s`, total: `1m24s` |0.5927 (0.00)|`no data`|`no data`|

Dataset: `powerplay11_subset`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `59s`, train: `1m25s`, total: `2m23s` |0.4436 (0.00)|`no data`|`no data`|
| `BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m0s`, train: `48s`, total: `1m47s` |0.4436 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `45s`, train: `1m29s`, total: `2m14s` |0.4873 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `50s`, train: `57s`, total: `1m46s` |0.4473 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `1m0s`, train: `1m28s`, total: `2m28s` |0.5902 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `1m1s`, train: `50s`, total: `1m50s` |0.5091 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `51s`, train: `1m36s`, total: `2m26s` |0.4618 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `50s`, train: `58s`, total: `1m47s` |0.4691 (0.00)|`no data`|`no data`|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `31s`, train: `1m15s`, total: `1m45s` |0.5418 (0.00)|`no data`|`no data`|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `32s`, train: `42s`, total: `1m14s` |0.5055 (0.00)|`no data`|`no data`|

Dataset: `sofmattress_full`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `41s`, train: `1m33s`, total: `2m14s` |0.7013 (0.00)|`no data`|`no data`|
| `BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `43s`, train: `50s`, total: `1m32s` |0.7143 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `30s`, train: `1m35s`, total: `2m5s` |0.7619 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `30s`, train: `54s`, total: `1m24s` |0.7749 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `41s`, train: `1m37s`, total: `2m17s` |0.7273 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `41s`, train: `50s`, total: `1m31s` |0.6883 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `32s`, train: `1m44s`, total: `2m15s` |0.7619 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `32s`, train: `59s`, total: `1m30s` |0.7316 (0.00)|`no data`|`no data`|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `14s`, train: `1m21s`, total: `1m35s` |0.7186 (0.00)|`no data`|`no data`|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `17s`, train: `46s`, total: `1m3s` |0.6970 (0.00)|`no data`|`no data`|

Dataset: `sofmattress_subset`

| Configuration | Intent Classification Micro F1 | Entity Recognition Micro F1 | Response Selection Micro F1 |
|---------------|-----------------|-----------------|-------------------|
| `BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `42s`, train: `1m9s`, total: `1m50s` |0.6190 (0.00)|`no data`|`no data`|
| `BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `42s`, train: `42s`, total: `1m23s` |0.6407 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `34s`, train: `1m17s`, total: `1m51s` |0.6667 (0.00)|`no data`|`no data`|
| `ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `35s`, train: `54s`, total: `1m28s` |0.6710 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(bow) + ResponseSelector(bow)`<br> test: `41s`, train: `1m10s`, total: `1m51s` |0.6494 (0.00)|`no data`|`no data`|
| `Sparse + BERT + DIET(seq) + ResponseSelector(t2t)`<br> test: `42s`, train: `43s`, total: `1m24s` |0.5683 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(bow) + ResponseSelector(bow)`<br> test: `33s`, train: `1m26s`, total: `1m58s` |0.7056 (0.00)|`no data`|`no data`|
| `Sparse + ConveRT + DIET(seq) + ResponseSelector(t2t)`<br> test: `35s`, train: `56s`, total: `1m31s` |0.6147 (0.00)|`no data`|`no data`|
| `Sparse + DIET(bow) + ResponseSelector(bow)`<br> test: `15s`, train: `59s`, total: `1m14s` |0.5597 (0.00)|`no data`|`no data`|
| `Sparse + DIET(seq) + ResponseSelector(t2t)`<br> test: `17s`, train: `38s`, total: `54s` |0.5758 (0.00)|`no data`|`no data`|

**Pull request closed without merging**
