### PR TITLE
Add a command-line option to specify domain for `rasa test`

### LINKED ISSUE #10518: `rasa test nlu` does not accept `--domain` argument, making responses unavailable when using multiple domain files
### Rasa Open Source version

2.8.16

### Rasa SDK version

_No response_

### Rasa X version

_No response_

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

I have a directory structure with split domains, like this:
```
├── config.yml
├── credentials.yml
├── data
│   ├── faq.yml
│   ├── nlu.yml
│   ├── rules.yml
│   └── stories.yml
├── domain
│   ├── domain.yml
│   └── domain_responses.yml
├── endpoints.yml
```
ResponseSelector responses are in `domain/domain_responses.yml`, and this works fine for training and prediciton.

I am using ResponseSelector with `use_text_as_label: true` as e.g. this minimal config:

```
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: ResponseSelector
    epochs: 10
    use_text_as_label: true
```

When running NLU cross-validation, the responses are not available to ResponseSelector, because I cannot specify an alternative location of the domain on the command line. Therefore, it falls back to using the response labels for training and prediction. This is different from the behaviour at training time, so it means my test results do not reflect real-life results. 

### Command / Request

```shell
rasa test nlu --cross-validation
```

### Relevant log output

```shell
Expected type of errors in response_selection_errors.json:

[
  {
    "text": "whats your name",
    "intent_response_key_target": "faq/ask_name",
    "intent_response_key_prediction": {
      "name": "faq/ask_builder",
      "confidence": 0.6701710224151611
    }
  },
  {
    "text": "how old are you?",
    "intent_response_key_target": "faq/ask_age",
    "intent_response_key_prediction": {
      "name": "faq/ask_builder",
      "confidence": 0.997443437576294
    }
  }
]
```

Actual type of errors in response_selection_errors.json - no prediction at all:
```
[
  {
    "text": "whats your name",
    "intent_response_key_target": "faq/ask_name",
    "intent_response_key_prediction": {
      "name": "",
      "confidence": 0.0
    }
  },
  {
    "text": "what is your age?",
    "intent_response_key_target": "faq/ask_age",
    "intent_response_key_prediction": {
      "name": "",
      "confidence": 0.0
    }
  }
]
```
```

### PR DESCRIPTION
**Pull request by jupyterjazz**
**Proposed changes**:
- Adds a command-line option to specify domain file or a directory (`--domain` or `-d`) for `rasa test` and `rasa test nlu`.
- Fixes  #10518 

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by carlad** [comment]
Looks good @jupyterjazz 
I'm wondering if the test data we use covers the case Melinda mentions in the issue?

**Comment by jupyterjazz** [comment]
> Looks good @jupyterjazz I'm wondering if the test data we use covers the case Melinda mentions in the issue?

@carlad, 
No the tests doesn't cover Melinda's case. I wanted to test it at first but it didn't seem straightforward to me. Then I looked at the other tests (as it was already implemented for `rasa train`) and there aren't any that check how `--domain` works. So I suspect that testing Melinda's case which involves a response selector and a non-default project configuration could be a bit difficult and heavy. However, if you think we should test it I'm ok with that. If so, any ideas on how to approach it? :pray:

**Comment by carlad** [comment]
@jupyterjazz Have you been able to test it locally?

Also, I may have replicated some of this work yesterday while [backporting](https://github.com/RasaHQ/rasa/pull/10623/files) changes into `2.8.x`, so make sure you resolve any conflicts....

**Comment by jupyterjazz** [comment]
> @jupyterjazz Have you been able to test it locally?

Yes, sure. Since the domain file wasn't in its default position and we weren't able to specify our domain path, the outcome Melinda had was expected. Adding this cli command solves it. 

> Also, I may have replicated some of this work yesterday while backporting changes into 2.8.x, so make sure you resolve any > conflicts....

I'm looking at it rn and I think my PR isn't really needed anymore. I just tested current `2.8.x` and it works well so I'll just close this PR.

**Pull request closed without merging**
