### PR TITLE
Python 3.7 support

### LINKED ISSUE #1709: Python 3.7 support
**Issue**: When can we expect python 3.7 support?
I see that `tensorflow 1.12` is required for installing the tensorflow pipeline. Are there any breaking changes in `tensorflow 1.13` which is preventing the upgrade to `tensorflow 1.13`? 

The rest of my team is switching so `python 3.7` support would be nice.

### PR DESCRIPTION
**Pull request by tmbo**
**Proposed changes**:
- updated tensorflow dependencies
- marked python 3.7 as supported 
- added to travis build
- fixes #1709

**Can only be merged after tensorflow 1.13 is released (currently depends on release candidate)**

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] updated the documentation
- [x] updated the changelog

### CODE REVIEW

**Comment by tmbo** [comment]
@Ghostvv are there any more changes needed (and more importantly, does it work 😅 )?

**Comment by Ghostvv** [comment]
By "it" what do you mean? I didn't try your branch, and I didn't install `py37` yet. tf 1.13 works on py36

**Comment by tmbo** [comment]
ah my bad - I thought you ran it on 3.7 for some reason. never mind

**Comment by Ghostvv** [comment]
I wanted to, but decided not to waste time on potential issues for now

**Comment by Ghostvv** [comment]
@tmbo is it ready for review?

**Comment by tmbo** [comment]
No not really, tests are not passing

**Comment by tmbo** [comment]
do you need it because of the tf update?

**Comment by Ghostvv** [comment]
not really, I was just going through my PR requests and saw a tick ready for review up there

**Comment by tmbo** [comment]
I'll assign this to you @Ghostvv to check if the tensorflow models still train / load / run

**Comment by Ghostvv** [comment]
`nlu` is training with py3.7

**Comment by tmbo** [comment]
These changes already made it into master through the backpart for the 0.15.0 release. No need to merge this anymore.

**Pull request closed without merging**
