### PR TITLE
Add resolutions in docs/package.json to fix vulnerabilities

### PR DESCRIPTION
**Pull request by m-vdb**
**Proposed changes**:
- Add "resolutions" to `package.json` to pin vulnerable libraries.
- ⚠️ I've ran `yarn why ...` to find out which dependencies depend on these libraries, and check that `redoc`, `netlify-cli` and `plugin-ideal-image` continue to work on dev and production build.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by m-vdb** [comment]
FYI @tczekajlo

**Comment by tczekajlo** [comment]
> FYI @tczekajlo

Thanks a lot for taking care of it 🙏🏻

**Review by lunelson — COMMENTED** [review]
Again, I don't have the context, but it looks sound 👍🏻

**Review by lunelson — APPROVED** [review]

**Comment by m-vdb** [comment]
@lunelson we got some vulnerability alerts on sub-dependencies in `docs/yarn.lock`

**Pull request merged**
