### PR TITLE
Add 'Access-Control-Expose-Headers' for 'filename' header (#6075)

### PR DESCRIPTION
**Pull request by Ezhvsalate**
**Proposed changes**:
- 'filename' header added to 'Access-Control-Expose-Headers'

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @chkoss will take a look at it as soon as possible ✨

**Comment by Ezhvsalate** [comment]
> Nice! this PR isn't into RasaHQ's master, so the base needs to change but otherwise it's fine

OK, which is target branch then? 1.10.x?

**Comment by melindaloubser1** [comment]
@Ezhvsalate yes, into 1.10.x

**Comment by Ezhvsalate** [comment]
@melindaloubser1  unfortunately github doesn't allow to change source branch of PR. So to make it work I'll have to make my local repository 'master' branch be rebased on upstream '1.10.x' branch, which looks awful. Have created another PR with one clean commit: https://github.com/RasaHQ/rasa/pull/6102
Closing this.

To avoid issues like this for future contributors maybe you should update this instruction: https://github.com/RasaHQ/rasa/blob/master/CONTRIBUTING.md with some information about your branching model. I tried to follow it carefully and what I saw there was:

image

**Pull request closed without merging**
