### PR TITLE
Fix script to install docs: skip node_modules

### PR DESCRIPTION
**Pull request by m-vdb**
**Proposed changes**:
- Fix script that updates docs for a minor. Addresses issues like [this one](https://github.com/RasaHQ/rasa/runs/3351536720?check_suite_focus=true)

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by HotThoughts** [comment]
Wow, this was fast 🔥 

Could we add the trigger `pull_request:` [here](https://github.com/RasaHQ/rasa/blob/ce298c3e71284416dd8fe9fa674da5750ee4f8f7/.github/workflows/documentation.yml#L3) so the workflow runs in this PR and we can validate the fix? And of course we will remove it before merging.

**Comment by m-vdb** [comment]
done with 7adcaba1245 👍🏻 workflow running here: https://github.com/RasaHQ/rasa/runs/3361067002?check_suite_focus=true

**Comment by m-vdb** [comment]
done in: b4dac18e 👍🏻 workflow run: https://github.com/RasaHQ/rasa/pull/9387/checks?check_run_id=3361120558

**Comment by m-vdb** [comment]
done 👍🏻 workflow run: https://github.com/RasaHQ/rasa/pull/9387/checks?check_run_id=3361172679

**Comment by m-vdb** [comment]
@HotThoughts good call requesting me to run this in workflow. `find` options on MacOS and Ubuntu are definitely different... I'm hitting a wall here, I am not sure which type of regex I should use with `find` so that it works in the CI. I've followed [this doc](https://manpages.ubuntu.com/manpages/xenial/man7/regex.7.html) and [this SO answer](https://stackoverflow.com/a/36781850/999076), and tried out: `-regextype posix-egrep`, `-regextype egrep` and `-regextype posix-extended`, without success. (and of course without the option it also fails). Do you have any idea of what option I should use? If not, who could I ask?

**Comment by HotThoughts** [comment]
@m-vdb 😞 Not only `find`, `sed` also has special syntax on MacOS (yesterday I learned hah). The syntax differences between Linux and Unix really make everyone's life harder. 😢 

The [`find` man page](https://linux.die.net/man/1/find) says

> -regex pattern
  File name matches regular expression pattern. This is a match on the whole path, not a search. For example, to match a file named './fubar3', you can use the regular expression '.*bar.' or '.*b.*3', but not 'f.*r3'. The regular expressions understood by find are by default **Emacs Regular Expressions**, but this can be changed with the -regextype option.

Emacs's regular expression syntax requires us to escape `|` and `()` match group with `\`, so I did that. 

Pushed my changes to this PR. The workflow run [succeeded](https://github.com/RasaHQ/rasa/pull/9387/checks?check_run_id=3365013987). Nice!

**Review by HotThoughts — APPROVED** [review]
💯 Good to go

**Comment by m-vdb** [comment]
You rock! thanks 🚀 🙏🏻

**Pull request merged**
