### PR TITLE
Custom action modules

### PR DESCRIPTION
**Pull request by pheel**
**Proposed changes**:
Rasa allows module path-based custom natural language generators, interpreters, brokers and stores, but there is currently no easy way to extend it with native (non-SDK) actions. This is a limitation for some use cases, for example if one wants to implement a `LoopAction`.

This PR makes it possible to load custom actions by specifying module paths in the endpoints. The current implementation piggybacks on the `action_endpoint` object that's passed to action name resolution methods.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @samsucik will take a look at it as soon as possible ✨

**Comment by TyDunn** [comment]
Hey @pheel. Can you explain in a bit more detail 1) these use cases (e.g. implementing a LoopAction) and 2) what is limiting for them in our current approach of requiring all user actions to use the sdk?

**Comment by wochinge** [comment]
@pheel Why can't you implement a `LoopAction` in the SDK?

**Comment by pheel** [comment]
> @pheel Why can't you implement a `LoopAction` in the SDK?

@TyDunn @wochinge I guess the current lack of a base class in the SDK, and the deprecation warnings for `FormAction` there threw me off... Would a base class for `LoopAction` be a welcome PR for the SDK, then?

**Comment by wochinge** [comment]
@pheel I think this could make sense 👍🏻 To be honest, I'm super curious about your use case 😄  What are you trying to accomplish?

**Comment by pheel** [comment]
@wochinge This is to develop form-like flows with integrated condition verification (on potentially unfeaturized) slots. Essentially the idea outlined in https://github.com/RasaHQ/rasa/issues/6178.

**Comment by wochinge** [comment]
what do you mean by `integrated`? You can already implement conditions for slot mappings using the [`FormValidationAction`](https://rasa.com/docs/rasa/forms#dynamic-form-behavior)

**Pull request closed without merging**
