### PR TITLE
Add __repr__ to Token - Related to Issue #7250, PR #7839

### PR DESCRIPTION
**Pull request by ErickGiffoni**
Issue #7250 was previously solved via PR #7839 but there was some trouble during the checks.
The conversation in the PR 7839 ended, so I continued the work.

**Proposed changes**:

- Fixes a typo warned by the typo CI

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [X] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by ancalita** [comment]
Hi @ErickGiffoni Thank you for looking into this 🚀 
Since the branch `issue-7250` is quite outdated, I'd recommend starting from scratch and have your new PR target `main` branch to close this issue. Once you've done that, this PR should be closed.

**Comment by ErickGiffoni** [comment]
> Hi @ErickGiffoni Thank you for looking into this 🚀
> Since the branch `issue-7250` is quite outdated, I'd recommend starting from scratch and have your new PR target `main` branch to close this issue. Once you've done that, this PR should be closed.

Ok, no problem !

Would it be ok if I just change this PR's base branch to "main", since I've merged both branches ?

**Comment by ancalita** [comment]
> Would it be ok if I just change this PR's base branch to "main"

@ErickGiffoni Sure, as long as your changes/ commits become visible for review.

**Comment by ErickGiffoni** [comment]
@ancalita done. Thanks for reviewing this ! I'll be awaiting for further feedback.

**Comment by aeshky** [comment]
Thanks for your contribution, @ErickGiffoni. 
Can you please add a change log file (the instructions [here](https://github.com/RasaHQ/rasa/tree/main/changelog)). Also, can you target the `2.8.x` branch instead of `main`?

**Comment by ErickGiffoni** [comment]
> Thanks for your contribution, @ErickGiffoni.
> Can you please add a change log file (the instructions [here](https://github.com/RasaHQ/rasa/tree/main/changelog)). Also, can you target the `2.8.x` branch instead of `main`?

Yeah, sure, as you wish ! I’ll do it as soon as possible, thanks.

**Comment by ErickGiffoni** [comment]
> Thanks for your contribution, @ErickGiffoni.
> Can you please add a change log file (the instructions [here](https://github.com/RasaHQ/rasa/tree/main/changelog)). Also, can you target the `2.8.x` branch instead of `main`?

@aeshky Done! I did what you asked me to do. First the change file. But when changing the target branch, lots of new files were changed. Is it ok or should I do differently ?

**Comment by aeshky** [comment]
Thanks for making the changes @ErickGiffoni. I should have been clearer: can you rebase your branch on `2.8.x` and then target it for the merge? That way your change gets released in the next micro release instead of waiting for the next major release. So the only difference should be your changes.

**Comment by ErickGiffoni** [comment]
> Thanks for making the changes @ErickGiffoni. I should have been clearer: can you rebase your branch on `2.8.x` and then target it for the merge? That way your change gets released in the next micro release instead of waiting for the next major release. So the only difference should be your changes.

@aeshky Ok, done it ! I never solved soo many conflicts in my life ( lol ).

I rebased it like this: ```git pull --rebase upstream 2.8.x```, where "upstream" is set to here, RasaHQ/rasa.

Then, after solving lots of conflicts, I tried to ```git push origin issue-7250``` (my origin is set to my repository), but it says my current branch is behind the remote one. Maybe makes sense, since initially my branch ```issue-7250``` was created from branch ```main```.

But now it is rebased, so it's like it was created from ```2.8.x``` which is probably behind ```main```.
**My point is that I am so confused right now that I need help, lol**. I'm sorry.

What should I do ?

**Comment by aeshky** [comment]
Hey @ErickGiffoni. Sorry you had to resolve so many conflicts! Your original submission only had changes to a couple of files, but it looks like rebasing your branch on `2.8.x` created too many conflicts. 

I think the easiest way to resolve this is to create a new branch from `2.8.x`, then move your commits to it (using `git cherry-pick`). You can then create a new pull request and tag me in it. How does that sound?

**Comment by ErickGiffoni** [comment]
Hey, @aeshky, ok that sounds good for me, I'm on it. Looking forward to have my contribution accepted !

**Comment by ErickGiffoni** [comment]
New PR created: #9631 

Closing this one !

**Pull request closed without merging**
