### PR TITLE
Update agent docstring

### PR DESCRIPTION
**Pull request by MetcalfeTom**
Example was wrong

### CODE REVIEW

**Comment by erohmensing** [comment]
For me, both of these work 🤔what was the relevant issue?

**Comment by MetcalfeTom** [comment]
You can't call `await` outside of a function.  This example worked for you when run from a Python terminal?

**Comment by erohmensing** [comment]
```
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from rasa.core.agent import Agent

In [2]: from rasa.core.interpreter import RasaNLUInterprete
   ...: r

In [3]: agent = Agent.load("examples/restaurantbot/models/c
   ...: urrent")
2019-08-09 14:19:44.578657: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /Users/ella/miniconda3/envs/rasa/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /Users/ella/miniconda3/envs/rasa/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.

In [4]: await agent.handle_text("hello")
Out[4]: [{'recipient_id': 'default', 'text': 'how can I help you?'}]

In [5]: agent.handle_text("hello")
Out[5]: <coroutine object Agent.handle_text at 0x143fc9f48>
```

**Comment by wochinge** [comment]
I somewhat agree with @erohmensing . They should probably know when to use `await` and when not.

**Comment by MetcalfeTom** [comment]
Isn't working in my terminal, but as long as it does for @erohmensing we can close this

**Comment by erohmensing** [comment]
well thats strange 🤔

**Pull request closed without merging**
