### PR TITLE
Merge 2.2.7 to main

### PR DESCRIPTION
**Pull request by chdorner**
**Proposed changes**:
Merge changes from `2.2.x` that shipped in 2.2.7 back to `main`.

**Status (please check what you already did)**:
- ~~[ ] added some tests for the functionality~~
- ~~[ ] updated the documentation~~
- ~~[ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)~~
- ~~[ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)~~

### CODE REVIEW

**Comment by chdorner** [comment]
I've tried my best resolving merge conflicts in `poetry.lock` and then updating the file with `poetry lock --no-update` afterwards, maybe something to look at in a bit more detail.

**Comment by mprazz** [comment]
@chdorner just making sure since it was changed relatively recently -- you used poetry version `1.1.4` right? 😊

**Comment by chdorner** [comment]
@mprazz Yep, I was running it with poetry `1.1.4`. It is [moving a whole bunch of lines around](https://github.com/RasaHQ/rasa/pull/7816/commits/c9c37a1722f35c62d944435d093f4b2228b9e566) within certain blocks, not sure why 🤷

**Comment by mprazz** [comment]
It does that all the time, I have no idea why 😅

**Comment by mprazz** [comment]
If the tests are passing, we should be good I'd say :)

**Review by mprazz — APPROVED** [review]

**Pull request merged**
