### PR TITLE
simply fix for exporting properties in domain

### LINKED ISSUE #3766: triggers keyword lost in IL domain export
before IL: 
```
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great:
      use_entities: false
  - mood_unhappy
  - random:
      triggers: utter_random
```

after IL:
```
intents:
- greet
- random
- affirm
- mood_unhappy
- goodbye
- deny
- mood_great:
    use_entities: false
```

### LINKED ISSUE #3841: Command line interactive learning session erased all my intent triggers during export
**Rasa version**: 1.1.3

**Rasa X version** (if used & relevant): n/a

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Win10

**Issue**: After using interactive session to generate new stories and exporting, all my intent triggers were lost (domain.yml file). Everything else seems to be fine during the export overwrite.

For example, before using interactive session
```
intents:
 - ask_is_bot:
     triggers: action_is_bot
```
after interactive session export:
```
intents:
 - ask_is_bot
```

**Command or request that led to error**:
```
rasa interactive
```

### PR DESCRIPTION
**Pull request by imLew**
Fixes #3766.
Fixes #3841

`use_entities` has always been assumed to be true, this behaviour is now
use to differentiate between the cases where the user explicitly set it
to true and those where they didn't
if `use_entities` is not explicitly set the intent dictionary will not
have that key. all keys that are present in the intent dictionary are
exported in the cleaned domain
in order to conform to the this new convention intents created during
interactive learning are no longer given the `use_entities` property but
instead are empty dictionaries (i.e. `{_intent_name_: {}}` instead of `{_intent_name_: {use_entities: True}}`)

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
@imLew any chance we can get this in today? it's been sitting around for a while and other people using the mapping policy are running into it

**Comment by imLew** [comment]
> @imLew any chance we can get this in today? it's been sitting around for a while and other people using the mapping policy are running into it

Not today, intent properties have changed in a way that makes this fix basically useless. I have an idea for a new fix but haven't gotten around to it.

**Comment by imLew** [comment]
@erohmensing What I'd hoped would work won't. So right now I think it will be pretty easy to create a fix that is perfect 99% of the time and will sometimes cause some confusion. 
The problem is that when the domain is exported as a yaml and a property has a default value we no longer know if this value was set by the user. So the simple fix would be to just not show any default value properties in the exported domain. (Which would be fine until someone decides to set `use_entities: True` and then notices it missing after IL).
Do you think this is good enough?
(I was hoping to just read the domain file again when exporting but that would not work in the case of merged domains so.)

**Comment by erohmensing** [comment]
Yeah, not 100% ideal but I think that would be fine, as it wouldn't change the bot's behavior

**Pull request merged**
