### PR TITLE
Fix DynamoDB TrackerStore

### PR DESCRIPTION
**Pull request by hotzenklotz**
**Proposed changes**:
- The "old" DynamoDB TrackerStore implementation created one table entry per Tracker update resulting in many objects/rows per user and session. This was caused because of the use of a timestamp (`session_date`) as part of the table's index. This fix drops the index `session_date` and only uses the `sender_id` when creating/updating DB entries. 

- The PR includes a backward compatibility check to continue usage for DynamoDBs tables with the old schema. It also introduces a deprecation warning for these kind of tables.

- Changes we tested together with @tmbo on a private project connecting to DynamoDB.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by tmbo — APPROVED** [review]

**Comment by tmbo** [comment]
@tczekajlo do you have a commit for the CI that I can cherry pick onto this branch to get the build working? (failing due to the github deprecation)

**Comment by tczekajlo** [comment]
> @tczekajlo do you have a commit for the CI that I can cherry pick onto this branch to get the build working? (failing due to the github deprecation)

@tmbo Alas, nothing that would fit the `1.10.x`, but here is a PR with the fix https://github.com/RasaHQ/rasa/pull/7367 for the `1.10.x`

**Comment by tmbo** [comment]
@hotzenklotz we've fixed the build on RasaHQ:1.10.x, can you please update this PR with the changes on that base branch

**Comment by hotzenklotz** [comment]
@tmbo I updated the base branch. Now all check pass. :-)

**Pull request merged**
