### PR TITLE
Update telegram.py

### PR DESCRIPTION
**Pull request by evios**
**Proposed changes**:
- added possibility to parse correctly user phone number information - after asking permission to see user phone number. Somehow only "location" was parsed in current version

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @degiz will take a look at it as soon as possible ✨

**Comment by degiz** [comment]
Hey @evios 

Thanks a lot, that looks great 👍 

Do you mind  adding a unit tests for the change? I know there's not a single test for Telegram channel yet, but that should be fairly easy to get! Somethings as simple as mocking the `json` from the user would do! 
You can take a look at the `tests/core/channels/test_hangouts.py`, it's not really for the "input", but gives the idea.

wdyt?

**Comment by evios** [comment]
Hi Alexander,
Currently I am in acceleration with startups, hence just created PR for
what I have done for our project. Will have more time in 8-12 weeks. If it
is OK, I think I can write some teste after acceleration.
-- 
wbr, ievgen iosifov

**Comment by degiz** [comment]
Hi @evios 

>If it is OK, I think I can write some tests after acceleration.

Sure! Good luck with the acceleration 👍

**Pull request closed without merging**
