### PR TITLE
Test `build changelog` step

### PR DESCRIPTION
**Pull request by chkoss**
Just testing, nothing to see here.

### CODE REVIEW

**Comment by erohmensing** [comment]
@chkoss if you're testing the validation, it doesn't check it in the `build changelog` step but rather the `test changelog step`: 

https://github.com/RasaHQ/rasa-x/blob/master/.github/workflows/continuous-integration.yml#L538
https://github.com/RasaHQ/rasa-x/blob/master/Makefile#L108
(the `-W` is what makes it fail on warnings)

**Comment by chkoss** [comment]
@erohmensing thx. I'm trying to test the `build changelog` step (I'm reviewing Maxime's PR where he added that step)... But apparently I didn't really understand what the step is supposed to do then, I thought it did the validation

**Comment by erohmensing** [comment]
Let me know if I can help, as I introduced it 🙂

**Comment by chkoss** [comment]
Yeah, I think I got it now. Your first hint helped me figure it out, thanks 🙂 
If the `Build Changelog` step is included, the `Test Docs` step fails when there is an invalid changelog snippet. I was expecting the `Build Changelog` step itself to fail...

(Also, I realised that in `master` building the changelog already happens in the `Test Docs` step itself since your commit https://github.com/RasaHQ/rasa/commit/36b522ddade5bdf5f4416d0f9c55440723db1b8c. It was just still missing in `1.10.x`)

**Pull request closed without merging**
