### PR TITLE
Update evaluating-models.rst - Confussion matrix 

### PR DESCRIPTION
**Pull request by gdsad**
In Section "Intent Classification" there was this note:

.. note::
    A confusion matrix will **only** be created if you are evaluating a model on a test set.
    In cross-validation mode, the confusion matrix will not be generated.

This is incorrect. If you run a test in cross-validation mode, a confusion matrix IS generated.

**Proposed changes**:
- Remove this note.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
Thanks for the PR! We'll give it a review as soon as possible.

**Comment by gdsad** [comment]
You are welcome!
Do I have to do something else?
I ask you this because of the "Travis CI - Pull Request Faling"
Sorry, is my first time doing it.

**Comment by Ghostvv** [comment]
Build failing independent of this PR, we're working on the solution.

**Comment by gdsad** [comment]
Ok!

**Comment by erohmensing** [comment]
@Ghostvv this is good to merge?

**Comment by Ghostvv** [comment]
yes

**Pull request merged**
