### PR TITLE
Change --data type in 'rasa data validate' command

### PR DESCRIPTION
**Pull request by martasls**
**Proposed changes**:
- Change "--data" type in the 'rasa data validate' command to allow more than one path to be passed 

**Status (please check what you already did)**:
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by martasls** [comment]
@ArjaanBuijk 
Opened the PR. Could you please assign yourself as reviewer as it doesn't look like I can do it from my end. Thanks!!

**Comment by sara-tagger** [comment]
Thanks for opening a draft pull request 🚀If you have any questions, you can direct them to @JustinaPetr ✨

**Review by ArjaanBuijk — APPROVED** [review]

**Comment by ArjaanBuijk** [comment]
@martasls ,
I tested your updates and they work perfect.

I think you still have to sign the Contributor License Agreement (see the link above), which must be done before we can merge it.

**Comment by ArjaanBuijk** [comment]
@wochinge ,
Can you have a look at the updates as well?

It all looks good to me and I tested the updates, but wanted to make sure before I merge it in.

**Comment by ArjaanBuijk** [comment]
@martasls ,
thanks for signing the CLA !

**Review by wochinge — COMMENTED** [review]
Thanks for the contribution! Can you please add a changelog entry?

**Comment by martasls** [comment]
> Thanks for the contribution! Can you please add a changelog entry?

Hi @wochinge, should I enter an entry under the latest version?

**Comment by ArjaanBuijk** [comment]
@wochinge ,
do you know why the **Continuous Integration / Wait for docs test (pull_request)** is failing ?

**Comment by wochinge** [comment]
> Hi @wochinge, should I enter an entry under the latest version?


A new file called `8225.improvemend.md` in the changelog folder is sufficient (see [the Readme here](https://github.com/RasaHQ/rasa/blob/main/changelog/README.md))

> do you know why the Continuous Integration / Wait for docs test (pull_request) is failing ?


tbh no, but it's not required for the merge afaik.

**Comment by ArjaanBuijk** [comment]
@martasls ,
the cli unit tests are failing. Can you please fix them?

Eg. see these [Details](https://github.com/RasaHQ/rasa/runs/2178844144)

**Comment by ArjaanBuijk** [comment]
@martasls ,
Are you interested and will you have time to try to fix the tests that fail? Without that, we will not be able to merge your update.

If you do not have time, I can also look into it, but I wanted to check with you first.

**Comment by martasls** [comment]
> @martasls ,
> Are you interested and will you have time to try to fix the tests that fail? Without that, we will not be able to merge your update.
> 
> If you do not have time, I can also look into it, but I wanted to check with you first.

Hi Arjaan! Thanks for the reminder! I just finished looking into fixing the tests that were failing (at least the CLI ones). I guess this changed a bit from last time and I have to wait for the actions to be approved in order for them to be run?

**Comment by ArjaanBuijk** [comment]
@martasls ,
thank you for fixing those tests. We're getting closer!

I noticed some failes tests unrelated to your updates, so I did another merge.

If that does not fix it, I will ask our QA team for help with those.

**Comment by ArjaanBuijk** [comment]
@mprazz ,
some tests now fail that are unrelated to the updates. 
Do you have any tips how to fix these?

**Comment by martasls** [comment]
> @martasls ,
> thank you for fixing those tests. We're getting closer!
> 
> I noticed some failed tests unrelated to your updates, so I did another merge.
> 
> If that does not fix it, I will ask our QA team for help with those.

Hi Arjaan,

it does look like those failing tests are still related with converting files (using the data command). I'll try to have a look tomorrow!

**Comment by martasls** [comment]
Hi @ArjaanBuijk , could you approve the workflow? Thanks!

**Comment by mprazz** [comment]
@ArjaanBuijk As far as I can see from the logs, the failures are related to the changes, or am I missing something? The errors mention the `--data` argument.

**Comment by martasls** [comment]
> @ArjaanBuijk As far as I can see from the logs, the failures are related to the changes, or am I missing something? The errors mention the `--data` argument.

Hi @mprazz,
you're right. I've already looked into it and I'm waiting for the workflow to be approved to see if the tests are succeeding now.

**Comment by martasls** [comment]
Hi @ArjaanBuijk, only the Code Quality test is failing now. I went ahead and added docstrings for the convert_training_data method.

**Review by ArjaanBuijk — CHANGES_REQUESTED** [review]
@martasls ,

I went through everything in detail again, and it all looks great. Awesome job.

I noticed that there is a new binary file called `other` . Was this checked in by accident?

**Comment by martasls** [comment]
> @martasls ,
> 
> I went through everything in detail again, and it all looks great. Awesome job.
> 
> I noticed that there is a new binary file called `other` . Was this checked in by accident?
> 
> I saw it was added with commit `2a9b90: Fix data path in convert data method`.

Done!

**Review by ArjaanBuijk — APPROVED** [review]

**Comment by ArjaanBuijk** [comment]
@martasls ,
nice!
once tests pass, it should be ready to go.

**Comment by martasls** [comment]
> @martasls ,
> nice!
> once tests pass, it should be ready to go.

Ah sorry, one last commit. There was a blank line after the docstring.

**Comment by martasls** [comment]
> @martasls ,
> seems like there is still a small mypy issue in the convert.py.
> 
> Note that you can run that test locally as well with:
> 
> ```shell
> $ make types
> rasa/nlu/convert.py:28: error: Value of type variable "AnyStr" of "exists" cannot be "Sequence[Any]"  [type-var]
> Found 1 error in 1 file (checked 258 source files)
> make: *** [Makefile:105: types] Error 1
> ```

Thanks. I wasn't aware of this mypy test. Hope it's fixed now (I ran it locally and it seemed ok)!

**Comment by ArjaanBuijk** [comment]
@martasls ,

It all passed and it is merged!

Thanks you so much for your contribution and getting it updated to pass all these tests.

**Comment by martasls** [comment]
> @martasls ,
> 
> It all passed and it is merged!
> 
> Thanks you so much for your contribution and getting it updated to pass all these tests.

Thanks for the help and availability!

**Pull request merged**
