### PR TITLE
[CI] Add git commit sha of the dataset branch in comment

### PR DESCRIPTION
**Pull request by HotThoughts**
**Proposed changes**:
- Resolve https://github.com/RasaHQ/rasa/issues/7678
- Add dataset commit sha to both the report and PR comment

**Status (please check what you already did)**:
- [X] test cpu with the branch `test-branch`. The commit shows in the comment is `395f75e58e092eedd31cb09fc622baa5de4dbce4`, which matches the [latest commit](https://github.com/RasaHQ/training-data/tree/test-branch) of the `test-branch` in our dataset repo.
- [x] test gpu

### CODE REVIEW

**Comment by HotThoughts** [comment]
dataset_branch: "test-branch"
include:
- dataset: ["Carbon Bot", "Sara"]
    config: ["all"]

**Comment by HotThoughts** [comment]
/modeltest

```yml
dataset_branch: "test-branch"
include:
  - dataset: ["Carbon Bot", "Sara"]
    config: ["all"]

```

**Comment by HotThoughts** [comment]
@tczekajlo This PR is ready for review. The result reports look great on both [cpu](https://github.com/RasaHQ/rasa/pull/8506#issuecomment-823140997) and [gpu](https://github.com/RasaHQ/rasa/pull/8506#issuecomment-823278384) runner.

**Review by tczekajlo — APPROVED** [review]
LGTM 🎖️

**Pull request merged**
