### PR TITLE
adding in endpoints parameter for the jupyter.chat method

### PR DESCRIPTION
**Pull request by mcminis1**
**Proposed changes**:
- adding in kwarg for passing endpoints when calling chat in the jupyter notebook. Proposed change in https://github.com/RasaHQ/rasa/issues/6051

**Status (please check what you already did)**:
- [x] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by mcminis1** [comment]
No tests exist (that I can find) for the jupyter notebook methods. So, I don't have any tests to extend. This change is trivial. It seems reasonable to me not to require an additional test.

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @rgstephens will take a look at it as soon as possible ✨

**Comment by mcminis1** [comment]
@rgstephens I've also cleaned up some sphinx warnings for creating docs in the "Continuous Integration / Code Quality (pull_request)" test.

Let me know if you need something else to merge this PR. Thanks you!

**Comment by mcminis1** [comment]
@rgstephens Is this ready to Merge?

**Pull request merged**
