### PR TITLE
merge 1.10.x to master

### PR DESCRIPTION
**Pull request by wochinge**
**Proposed changes**:
- merge 1.10.x to master

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by wochinge** [comment]
the commit history by github seems somewhat weird considering that most of these commits were already merged yesterday https://github.com/RasaHQ/rasa/pull/5823 🤔

**Comment by wochinge** [comment]
will fix this

**Comment by m-vdb** [comment]
build blocked by https://github.com/RasaHQ/rasa/pull/5879

**Comment by m-vdb** [comment]
can we merge `1.10.x` in `merge-master`? I've just merged some new changes 🙏

**Comment by wochinge** [comment]
> can we merge 1.10.x in merge-master? I've just merged some new changes 🙏

on it

**Comment by wochinge** [comment]
omg, that's the longest x to master merge I have ever done

**Comment by wochinge** [comment]
did new, clean merge

**Pull request merged**
