### PR TITLE
New docs: theme updates III

### PR DESCRIPTION
**Pull request by lunelson**
These can go in after the RC

latest updates always on staging
https://staging--rasahq-docsv2-rasa.netlify.app/docs/rasa/

### CODE REVIEW

**Comment by lunelson** [comment]
@akelad this fixes a few more details and also the incorrect rasa-x top nav link

**Review by akelad — APPROVED** [review]

**Comment by akelad** [comment]
actually, if i go on the staging link you posted, the github icon on the top right links to this `https://github.com/rasahq/tabula` - that's prob the wrong one :D

**Comment by lunelson** [comment]
@akelad Yeah I know. [Staging](https://staging--rasahq-docsv2-rasa.netlify.app/docs/rasa/) was out by a couple of commits but is up to date now with this PR. Are you able to skip the CI status checks?

**Comment by akelad** [comment]
ah ok got it. I can skip the CI checks, but let's just wait for it to run, better safe than sorry :D

**Pull request merged**
