### PR TITLE
Add loockup table validation

### PR DESCRIPTION
**Pull request by iurisevero**
**Proposed changes**:
- Resolve issue #5956 
- Update the _add_lookup_table_regexes function, at (regex_featurizer.py)[https://github.com/RasaHQ/rasa/blob/1.10.x/rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py], to verify if there is some table in the training data.loockup_tables and return a bool informing it
- Print a warning message if validation returns false

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @yennycheung will take a look at it as soon as possible ✨

**Comment by yennycheung** [comment]
Thank you for your contribution @iurisevero. The solution looks great. Would you mind pointing the pull request to `main` instead of `RasaHQ:1.10.x`? Then we could include your changes in the next releases. Thank you!

**Comment by iurisevero** [comment]
Hi @yennycheung, I'll change the pointing, no problem! But I don't think the CI will accept my changes, because I did them from the tag ```1.10.23```, once the issue was solved in ```2.x``` versions but still happening at ```1.10.x```.

**Comment by yennycheung** [comment]
Apologies for the late reply, it seems like there are a lot of unrelated changes, would you mind pulling the latest `main` and cherry-picking your changes against it?

**Comment by iurisevero** [comment]
Hi. Don't worry. So, I don't think that pulling the latest main is a good idea. As I said, my changes were made for the 1.10.x version, where this issue still relevant. On the 2.x versions it was already solved.

My idea was to merge these changes to 1.10.x  branch and fix this problem for the next 1.10 tag.
Does that make sense for you?

**Comment by yennycheung** [comment]
@wochinge, do we do patches over the older versions or Rasa OSS?

**Comment by wochinge** [comment]
We only do so if it's crucial. Rasa Open Source 2 is out since more than half a year and I'd highly encourage to switch to it. We unfortunately don't have the capacity to maintain two majors side by side at the moment.

**Comment by iurisevero** [comment]
I get it. I believe this pull request will be closed so, right?
I suggest closing the issue [#5956](https://github.com/RasaHQ/rasa/issues/5956) as well. It doesn't make sense anymore.

**Comment by yennycheung** [comment]
@iurisevero, thank you for your help on this one. Hope next time we can get your work merged! 🙏🏼

**Pull request closed without merging**
