### PR TITLE
rasa run: remove default model path

### PR DESCRIPTION
**Pull request by tabergma**
**Proposed changes**:
- Remove default value of argument `model` for `rasa run` so that it is actually possible to fetch a model from a server.

fixes https://github.com/RasaHQ/rasa/issues/3931

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
So in a quick test, i opened up a bot, ran `rasa run —connector cmdline`, and got 
```
No model found. Train a model before running the server using `rasa train`.
```
after training and running the same command, i got the same error (on master my bot loads). Does this officially mean I must pass `-m models` now? If so, we need a better error and additions to the docs, etc

**Comment by tabergma** [comment]
Yes, if you want to use a local model, you need to pass `-m models`. Will update the error message.

**Comment by erohmensing** [comment]
This is kind of a bummer since people have gotten used to `rasa run` just doing its magic — is there any other workaround, by e.g. putting the default in later after checking for a model from a server? Not sure how that fetching code works.

**Comment by tabergma** [comment]
The problem is that we always first check if there is a model path given, if that is the case, we assume the user wants to load a local model. Only if there is no model path, e.g. `None`, we load it from the server or remote storage. So, if we now have a default model path, we never reach the point where we are loading from a server.
But I can take another look, maybe I can find another solution. Will ping you once I have a solution.

**Comment by erohmensing** [comment]
> Only if there is no model path, e.g. None, we load it from the server or remote storage.

and then if this fails to return a model, or they have no remote storage configured, can we then try to load it from local? i.e. we would switch the order in which we run these?

**Comment by tabergma** [comment]
Updated the PR. Changed the loading order.

**Comment by erohmensing** [comment]
oops, we definitely should have re-named the PR after updating its functionality 😅

**Comment by wochinge** [comment]
Mhm, but `rasa run` with no model in `models/` would still fail right? Cause we have the check in `cli/run` whether a model is present.

**Pull request merged**
