### PR TITLE
Move Rasa SDK docs to Rasa OSS repo

### PR DESCRIPTION
**Pull request by znat**
**Proposed changes**:
The Rasa SDK documentation is moved the the Rasa Open Source repo (removal from SDK repo here: https://github.com/RasaHQ/rasa-sdk/pull/855)

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ X] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by ancalita — APPROVED** [review]
LGTM ⚡ 
I see the sdk changelog has not been migrated, how will that work in the future?

**Comment by znat** [comment]
Thanks for the review @ancalita.
As discussed with @tmbo future changes in the sdk will require a changelog entry in the Rasa OSS repo changelog.
See in corresponding [sdk PR](https://github.com/RasaHQ/rasa-sdk/pull/855/files#diff-50ab658d1ebfaf4edc5d77cafec3f16ce5fcca841c793e366245b7a0b960592d)

**Comment by ancalita** [comment]
> Thanks for the review @ancalita. As discussed with @tmbo future changes in the sdk will require a changelog entry in the Rasa OSS repo changelog. See in corresponding [sdk PR](https://github.com/RasaHQ/rasa-sdk/pull/855/files#diff-50ab658d1ebfaf4edc5d77cafec3f16ce5fcca841c793e366245b7a0b960592d)

@znat How would be the flow for a contributor to sdk repo? Open a 2nd PR in rasa-oss to add a changelog entry?

**Comment by znat** [comment]
> How would be the flow for a contributor to sdk repo? Open a 2nd PR in rasa-oss to add a changelog entry?
That is the idea. I added a hint in the [PR template](https://github.com/RasaHQ/rasa-sdk/pull/855/files#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35). Any thoughts?

**Comment by znat** [comment]
Closing as replaced by https://github.com/RasaHQ/rasa/pull/11571

**Pull request closed without merging**
