### PR TITLE
dummy change - running tests

### PR DESCRIPTION
**Pull request by amn41**
**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by amn41** [comment]
/modeltest

```yml
include:
- dataset: ["Hermit"]
  config: ["all"]
```

**Comment by dakshvar22** [comment]
/modeltest

```yml
dataset_branch: "banking77_tests"
include:
- dataset: ["banking77"]
  config: ["all"]
```

**Comment by mprazz** [comment]
@amn41 Does this PR need a review? if yes, could I get a bit more context on it?

**Comment by amn41** [comment]
no :)

**Pull request closed without merging**
