### PR TITLE
conversation_granularity for slack - per user | per user per channel | per user per thread (2.8.x)

### PR DESCRIPTION
**Pull request by srinivasupadhya**
allow conversation_id to be per user | per user per channel | per user per thread

**Proposed changes**:
- Allow multiple active conversations for a user on slack with bot

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by tayfun — APPROVED** [review]

**Comment by srinivasupadhya** [comment]
@tayfun thanks for merging this :) will a new 2.8.x release be created automatically?

**Comment by tayfun** [comment]
@srinivasupadhya Thanks for fixing this. No, releases are done manually. I think we don't have a fixed frequency for releases but we do one every few weeks at least. We will have a 3.0 release candidate (RC2) coming up in the next few days (probably early next week) which will have these changes. The other 2.8.x release could happen later. Would that work for you?

**Comment by srinivasupadhya** [comment]
Looking forward to the 2.8.x release since im working on a project using rasa of that version :)

**Comment by tayfun** [comment]
> Looking forward to the 2.8.x release since im working on a project using rasa of that version :)

In that case I went ahead and released 2.8.13 :) See https://pypi.org/project/rasa/ Your changes are visible in this release.

It was my first release so let me know if you see anything weird. Thanks for the contributions again.

**Comment by srinivasupadhya** [comment]
Thanks for you that! The pip upgrade hangs at this step.

```
Collecting multidict<7.0,>=4.5
  Using cached multidict-4.7.6-cp37-cp37m-macosx_10_14_x86_64.whl (48 kB)
INFO: pip is looking at multiple versions of multidict to determine which version is compatible with other requirements. This could take a while.
  Using cached multidict-4.7.5-cp37-cp37m-macosx_10_13_x86_64.whl (48 kB)
  Using cached multidict-4.7.4-cp37-cp37m-macosx_10_13_x86_64.whl (48 kB)
  Using cached multidict-4.7.3-cp37-cp37m-macosx_10_13_x86_64.whl (48 kB)
  Using cached multidict-4.7.2-cp37-cp37m-macosx_10_13_x86_64.whl (48 kB)
  Using cached multidict-4.7.1-cp37-cp37m-macosx_10_13_x86_64.whl (51 kB)
  Using cached multidict-4.7.0-cp37-cp37m-macosx_10_13_x86_64.whl (50 kB)
  Using cached multidict-4.6.1-cp37-cp37m-macosx_10_13_x86_64.whl (161 kB)
  Using cached multidict-4.6.0-cp37-cp37m-macosx_10_13_x86_64.whl (161 kB)
  Using cached multidict-4.5.2-cp37-cp37m-macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.whl (196 kB)
  Using cached multidict-4.5.1-cp37-cp37m-macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.whl (196 kB)
  Using cached multidict-4.5.0-cp37-cp37m-macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.whl (196 kB)
INFO: pip is looking at multiple versions of multidict to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
```

New conda env (3.7) & `pip3 install rasa` hangs as well. I think this was happening for 2.8.12 as well.

**Comment by tayfun** [comment]
> Thanks for that! The pip upgrade hangs at this step.
> 
> ```
> Collecting multidict<7.0,>=4.5
>   Using cached multidict-4.7.6-cp37-cp37m-macosx_10_14_x86_64.whl (48 kB)
> INFO: pip is looking at multiple versions of multidict to determine which version is compatible with other requirements. This could take a while.
>   Using cached multidict-4.7.5-cp37-cp37m-macosx_10_13_x86_64.whl (48 kB)
>   Using cached multidict-4.7.4-cp37-cp37m-macosx_10_13_x86_64.whl (48 kB)
>   Using cached multidict-4.7.3-cp37-cp37m-macosx_10_13_x86_64.whl (48 kB)
>   Using cached multidict-4.7.2-cp37-cp37m-macosx_10_13_x86_64.whl (48 kB)
>   Using cached multidict-4.7.1-cp37-cp37m-macosx_10_13_x86_64.whl (51 kB)
>   Using cached multidict-4.7.0-cp37-cp37m-macosx_10_13_x86_64.whl (50 kB)
>   Using cached multidict-4.6.1-cp37-cp37m-macosx_10_13_x86_64.whl (161 kB)
>   Using cached multidict-4.6.0-cp37-cp37m-macosx_10_13_x86_64.whl (161 kB)
>   Using cached multidict-4.5.2-cp37-cp37m-macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.whl (196 kB)
>   Using cached multidict-4.5.1-cp37-cp37m-macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.whl (196 kB)
>   Using cached multidict-4.5.0-cp37-cp37m-macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.whl (196 kB)
> INFO: pip is looking at multiple versions of multidict to determine which version is compatible with other requirements. This could take a while.
> INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
> ```
> 
> New conda env (3.7) & `pip3 install rasa` hangs as well. I think this was happening for 2.8.12 as well.

hello @srinivasupadhya , thanks for trying the new release! Can you update to latest pip before installing rasa? Latest pip should be able to install very fast, you should simply run `pip install -U pip` beforehand. Let me know if this works for you. See https://rasa.com/docs/rasa/installation/#quick-installation

**Comment by srinivasupadhya** [comment]
That solved it! Things are working as expected. Thanks for all the help @tayfun @ka-bu

**Comment by tayfun** [comment]
> That solved it! Things are working as expected. Thanks for all the help @tayfun @ka-bu

Perfect! Let us know if you run into any issues; you can also create new issues on Github or pull requests if you have an idea. Cheers.

**Pull request merged**
