### PR TITLE
Change the default model weights for HFTransformersNLP

### PR DESCRIPTION
**Pull request by dakshvar22**
**Proposed changes**:
- Closes https://github.com/RasaHQ/research/issues/119

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by dakshvar22** [comment]
Previous model regression tests available [here](https://github.com/RasaHQ/rasa/pull/6967#issuecomment-709454144). Running them again as those results were a week old, but expect them to not have changed.

**Comment by dakshvar22** [comment]
/modeltest

```yml

include:
 - dataset: ["all"]
   config: ["BERT + DIET(bow) + ResponseSelector(bow)", "BERT + DIET(seq) + ResponseSelector(t2t)", "Sparse + BERT + DIET(bow) + ResponseSelector(bow)", "Sparse + BERT + DIET(seq) + ResponseSelector(t2t)"]

```

**Comment by dakshvar22** [comment]
/modeltest

```yml

include:
 - dataset: ["Private 1", "Private 2", "Private 3"]
   config: ["BERT + DIET(bow) + ResponseSelector(bow)", "BERT + DIET(seq) + ResponseSelector(t2t)", "Sparse + BERT + DIET(bow) + ResponseSelector(bow)", "Sparse + BERT + DIET(seq) + ResponseSelector(t2t)"]

```

**Review by tabergma — APPROVED** [review]
Results look good 💯

**Pull request merged**
