### PR TITLE
2.8.x

### PR DESCRIPTION
**Pull request by aeshky**
**Proposed changes**:
- Merging after the micro release 2.8.2

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by wochinge — APPROVED** [review]
🙌🏻

**Comment by wochinge** [comment]
Re the conflict in `poetry.lock`: The easiest approach is to delete `poetry.lock` and regenerate it using `poetry lock`.

**Comment by aeshky** [comment]
Thanks for the tip! I'll do that.

**Comment by aeshky** [comment]
I deleted `poetry.lock` from `2.8.x` and regenerate it using `poetry lock` but can't push the change because `2.8.x` is now protected. Am I doing it wrong? 🤔

**Comment by wochinge** [comment]
oooooh. Sorry, I should have caught that earlier 😬 

The best way is not to merge `2.8.x.` directly but rather via a separate branch:

```
git checkout main
## Make sure local `main` branch is up to date
git pull origin main

git checkout 2.8.x
## Make sure that 2.8.x is up to date
git pull origin 2.8.x

# Create 
git checkout -b "merge-2.8.2-to-main"
git merge main

# [potentially resolve merge conflicts]

# Push to rasa repository
git push origin merge-2.8.2-to-main

# Create PR and request me as reviewer
```

Does that make sense? Sorry for not pointing this out earlier.

**Comment by aeshky** [comment]
Yes that makes sense, thanks!

**Comment by aeshky** [comment]
Okay I created a new pull request. Hopefully I did it right this time! 😄

**Pull request closed without merging**
