### PR TITLE
only run coveralls if secret is available

### PR DESCRIPTION
**Pull request by wochinge**
**Proposed changes**:
- only run coveralls if secret is available (which it isn't for fork prs)

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by wochinge** [comment]
it works: https://github.com/RasaHQ/rasa/pull/5265/checks?check_run_id=454959078

**Comment by tmbo** [comment]
I was looking into this yesterday, we talked about it on slack. https://github.com/RasaHQ/rasa/pull/5253

I don't think we should remove the coverage report completely, there is a way to submit it without the secret. Looking into this right now, just need to get the python coverage reporter to create the right output format...

**Comment by wochinge** [comment]
Ok, but should we still fix it for now this way so that community members aren't blocked?

**Comment by tmbo** [comment]
I think this one might work https://github.com/RasaHQ/rasa/runs/455373701?check_suite_focus=true -let's see if it doesn't we'll merge this as a standin :+1:

**Comment by tmbo** [comment]
the other PR seems to fix the issue while still being able to report coverage

**Pull request closed without merging**
