### PR TITLE
use autogenerated anchors instead of explicit ones

### PR DESCRIPTION
**Pull request by erohmensing**
**Proposed changes**:
- remove explicit anchors
- fix references to explicit anchors

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
`make docs` definitely doesn't check whether the anchors resolve correctly 😞  added figuring out how to automate that to the to-do list

**Comment by erohmensing** [comment]
the anchors seem to have all been merged back in :(

**Comment by m-vdb** [comment]
WDYM?

**Comment by erohmensing** [comment]
I thought i'd removed them all but there are still a ton on master https://github.com/RasaHQ/rasa/search?q=anchor&unscoped_q=anchor

I guess I missed some as they don't seem to be in the diff here

**Comment by m-vdb** [comment]
arf, it must be because of other docs PR?

**Pull request merged**
