### PR TITLE
add hidden_layers_sizes to mimic EmbeddingIntentClassifier

### PR DESCRIPTION
**Pull request by Ghostvv**
**Proposed changes**:
- fix updating dict config values

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by Ghostvv** [comment]
@tabergma should this go to `1.8.x`?

**Comment by Ghostvv** [comment]
hm, updating config working for some versions of python

**Comment by tabergma** [comment]
yes, this should go into 1.8.x

**Comment by Ghostvv** [comment]
is there a simple way to switch to `1.8.x`?
I guess test is a good idea

**Comment by Ghostvv** [comment]
https://github.com/RasaHQ/rasa/pull/5411

**Pull request merged**
