### PR TITLE
Fix #7624: only fill slots where auto_fill is true in extract_other_s…

### LINKED ISSUE #7624: Auto-fill not respected by FormAction
**Rasa version**: 2.2.2

**Python version**: 3.6

**OS**: Mac

**Issue**:

*   The form action `extract_other_slots` is not respecting the `auto_fill` property of the slots in the domain file. So they are being overwritten.

There is a bug report on the forum here and also here: [https://forum.rasa.com/t/slots-overwritten-in-forms-with-duckling-entities/38197/5](https://forum.rasa.com/t/slots-overwritten-in-forms-with-duckling-entities/38197/5)

I was able to resolve the issue through a modification of this function. Will open a pull request.

### PR DESCRIPTION
**Pull request by kearnsw**
**Proposed changes**:
Check auto_fill property before extracting slot in `extract_other_slots`, only fill the slot if auto_fill = True (default value)

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [N/A] updated the documentation
- [X] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [X] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @JustinaPetr will take a look at it as soon as possible ✨

**Review by wochinge — COMMENTED** [review]
@kearnsw Thanks for your contribution. I'm not sure if I understand the issue completely: why would you specify a slot mapping in the domain if this slot should not be filled by the form?

**Comment by ma7555** [comment]
> @kearnsw Thanks for your contribution. I'm not sure if I understand the issue completely: why would you specify a slot mapping in the domain if this slot should not be filled by the form?

@kearnsw 
please see this https://forum.rasa.com/t/slots-overwritten-in-forms-with-duckling-entities/38197/5

**Comment by kearnsw** [comment]
Thanks for linking that @ma7555. @wochinge, the thread linked above explains the issue. It's possible I'm going about the solution wrong, but I was able to solve that user's problem by the changes in this PR.

**Comment by kearnsw** [comment]
@wochinge, I came across this issue (#6939) as well which is related to the question of when you would want to define a slot mapping, but not fill the slot. Although, I'm not sure that this PR will necessarily resolve that as I didn't test for that specifically.

**Comment by wochinge** [comment]
@kearnsw To me it seems they should rather validate the [extracted slots](https://rasa.com/docs/rasa/forms#validating-form-input) or making the slot mappings more narrow (e.g. excluding an intent). What do you think?

**Comment by kearnsw** [comment]
> @kearnsw To me it seems they should rather validate the [extracted slots](https://rasa.com/docs/rasa/forms#validating-form-input) or making the slot mappings more narrow (e.g. excluding an intent). What do you think? 

@wochinge, Validation may not work if there is no pattern that the slot can be validated against and/or two slots have overlapping entity types. 

Narrowing the scope of the mapping is a possibility in some situations, however often intents are not easily distinguished between slots so are combined into a single `inform` intent. Also, as we move toward e2e models this will no longer be an option.

**Comment by wochinge** [comment]
> Validation may not work if there is no pattern that the slot can be validated against and/or two slots have overlapping entity types.

Makes sense - but how does this relate to auto slot filling? Sorry for not getting it 🙈 
I think I'm not understanding the motivation for this correctly: Forms are meant to fill slots based on the users input. If a slot mapping is wide / shouldn't apply in certain conditions then a custom slot mapping should be used.

**Comment by wochinge** [comment]
@kearnsw Please feel free to re-open if you have time to continue

**Pull request closed without merging**
