### PR TITLE
Raising exception error when it is not possible to train

### PR DESCRIPTION
**Pull request by lucianaribeiro**
**Proposed changes**:
Closes [RasaHQ#4390](https://github.com/RasaHQ/rasa/issues/4390) 

- Raising ValueError exception when number of intents are equal one

**Changes made**:
- Added a Exception treating if is not possible to train in file `rasa/nlu/classifiers/embedding_intent_classifier.py` 

**Expected Behavior**:

- The number of intents must be equal one in your project file `/nlu`;
- Start training 
- The exception will raise  

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
Thanks for the PR, we'll give it a review as soon as possible.

**Comment by Ghostvv** [comment]
Thank you for creating this PR. The reason why we don't raise is that it is might be convenient to start developing with a single intent and maybe a couple of entities.

I think the proper fix is to always return the one intent we find.

**Comment by lucianaribeiro** [comment]
Hi @Ghostvv, I tried to do what you suggested, can you give some feedback about it? I do not know if it's all correct. Thanks!

**Comment by lucianaribeiro** [comment]
> Thank you for creating this PR. The reason why we don't raise is that it might be convenient to start developing with a single intent and maybe a couple of entities.
> 
> I think the proper fix is to always return the one intent we find.

**Comment by wochinge** [comment]
@twhughes How is it going with this PR? Do you need more feedback / help?

**Comment by tmbo** [comment]
I'd close this PR, I think the added benefit of showing the one intent we find does not justify the added code.

**Pull request closed without merging**
