### PR TITLE
Make it possible to call RemoteAction to ask for the next slot in FormAction

### PR DESCRIPTION
**Pull request by monatis**
**Proposed changes**:
- I implemented a TODO to make it possible to use a custom action to ask for the next slot.
- These custom actions should be prefixed with `action_ask_`, and can be `action_ask_{form_name}_{slot_name}` or `action_ask_{slot_name}` shortly, just as in the `utter_ask_` counterpart.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
I think you might be right behind us 😄 this is being implemented on master for rasa 2.0: https://github.com/RasaHQ/rasa/pull/6384/files#diff-263e4240a19c4cc6db32118bdb0f47d1R443

**Comment by monatis** [comment]
Hahha @erohmensing 😂 I was planning to review 2.0@master but then I decided to make this PR first. So should I cancel it?

**Comment by erohmensing** [comment]
Unfortunately I think so! Appreciate the PR though. How did you discover this, did you see the issue, or the to-do in the code?

**Comment by monatis** [comment]
@erohmensing Well I was in need of this functionality in one of our projects and I reviewed the source code to better understand how things go on with each other. And just happened to see the TODO and decided to implement it. Thanks anyway, good luck with 2.0 😄

**Pull request closed without merging**
