### PR TITLE
changing personId to roomId

### PR DESCRIPTION
**Pull request by techBeck03**
**Proposed changes**:
- changed `personId` to `roomId` on input channel since all of the output channel functions use roomId
- changed `roomID` to `roomId` in custom_json output

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @TyDunn will take a look at it as soon as possible ✨

**Comment by isaac-philip** [comment]
Very much needed fix, thanks!

Although what I fail to understand is why the latest package - **1.10.2** - which released few days back doesn't have this fix/code present.

Please let me know what I may be missing, thanks!

**Comment by wochinge** [comment]
@isaac-philip This was merged into `master` which means it will be part of the next minor (`1.11.0`). Would you want to quickly backport the changes? You'd need to branch of `1.10.x`, apply the changes from the PR, and then create a PR against `1.10.x`.

**Comment by isaac-philip** [comment]
Thanks @wochinge for the suggestion.

I guess it would make sense to backport it since 1.1.0 is way far off.

Let me get to it.

Have a great day!

**Pull request merged**
