### PR TITLE
add the variables import back in

### PR DESCRIPTION
**Pull request by akelad**
**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by erohmensing — APPROVED** [review]

**Comment by akelad** [comment]
hm so the CI check is failing on this
```
    if errors:
>           raise AssertionError(f"({mdx_file_path}):{''.join(errors)}")
E           AssertionError: (docs/docs/tracker-stores.mdx):
E             - Title '# Switch to root user to install packages' at line 132 cannot be level 1. Use '## Switch to root user to install packages' instead.
E             - Title '# Copy in oracle instaclient' at line 137 cannot be level 1. Use '## Copy in oracle instaclient' instead.
E             - Title '# https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html' at line 138 cannot be level 1. Use '## https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html' instead.
E             - Title '# Install the Python wrapper library for the Oracle drivers' at line 141 cannot be level 1. Use '## Install the Python wrapper library for the Oracle drivers' instead.
E             - Title '# Install Oracle client libraries' at line 144 cannot be level 1. Use '## Install Oracle client libraries' instead.
```
but these aren't headers :D

**Comment by erohmensing** [comment]
oh hrm, @m-vdb might need your help here 😄

**Comment by m-vdb** [comment]
yep, that's my bad. Pushing a fix to this branch in a second

**Comment by m-vdb** [comment]
fixed CI with deaa733e34f (I did the same change on Rasa X side but forgot to get it in Rasa)

**Pull request merged**
