### PR TITLE
Added e2e tests for examples bot

### PR DESCRIPTION
**Pull request by Archish27**
**Proposed changes**:
- Added e2e tests for mood bot

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @tttthomasssss will take a look at it as soon as possible ✨

**Comment by Archish27** [comment]
@tttthomasssss Can you merge this?

**Comment by Archish27** [comment]
Can someone merge this?

**Comment by akelad** [comment]
ah, sorry that we missed merging this! I'm afraid that format for end to end tests is now out of date since we're moving to the new yaml format with the 2.0. 
There is docs on how the new e2e format looks like [here](https://rasa.com/docs/rasa/next/training-data-format#test-conversations) - if you're up for it, then we'd love to accept an updated version of those tests. But I also understand if you don't have the time to do that.

**Comment by Archish27** [comment]
> ah, sorry that we missed merging this! I'm afraid that format for end to end tests is now out of date since we're moving to the new yaml format with the 2.0.
> There is docs on how the new e2e format looks like [here](https://rasa.com/docs/rasa/next/training-data-format#test-conversations) - if you're up for it, then we'd love to accept an updated version of those tests. But I also understand if you don't have the time to do that.

Ohhh cool will do the change with `yaml` format. Thanks

**Comment by tmbo** [comment]
Thanks a lot for the effort, but this has already been implemented when we added the support for the yaml format. I am sorry, we should have been clearer about that.

**Comment by Archish27** [comment]
Ohh cool no problem 😄

**Pull request closed without merging**
