### PR TITLE
Model checkpointing

### PR DESCRIPTION
**Pull request by tttthomasssss**
**Proposed changes**:

Implemented model checkpointing for DIET. The best DIET model during training will be stored instead of just the last model. The model is evaluated on the basis of `evaluate_every_number_of_epochs`. Checkpointing is enabled iff the following is set for the `DIETClassifier` in the `config.yml` file:
     * `checkpoint_model: True`
     * `evaluate_on_number_of_examples > 0`

The model is stored to whatever location has been specified with the `--out` parameter when calling `rasa train nlu ...`

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by tmbo** [comment]
should probably target master

**Comment by tabergma** [comment]
The PR still contains changes from @m-vdb, I guess that is not intended. Can you please check that?

Question to the logic itself: Are we only storing the best model or the best + last model?

**Comment by tttthomasssss** [comment]
hmm, guess these happened due to the merge. Whats the best way of removing these from this PR?

We are only storing the best model. The model performance is checked on the basis of `evaluate_every_number_of_epochs` and when training is over (i.e. compared to the last model).

**Comment by tttthomasssss** [comment]
right, i've painted myself in a very nice merge-hell corner. going to close this pr and create a clean new one.

**Pull request closed without merging**
