### PR TITLE
Replace ubuntu-latest with ubuntu-22.04

### PR DESCRIPTION
**Pull request by miraai**
**Proposed changes**:
- Replaced `ubuntu-latest` with `ubuntu-22.04` because Github is moving `latest` to `22.04`.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by rasa-jmac — APPROVED** [review]
LGTM

**Review by rasa-jmac — CHANGES_REQUESTED** [review]
Let's not merge this yet until we have clarity about the status of 3.10 support from here on.

**Review by rasa-jmac — APPROVED** [review]
Approved but please change the PR title to reflect that it's changing to Ubuntu 22.04

**Review by radovanZRasa — APPROVED** [review]
LGTM

**Pull request merged**
