### PR TITLE
prepared release of version 2.0.8

### PR DESCRIPTION
**Pull request by samsucik**
**Proposed changes**:
- Micro release that fixes bugs in `RulePolicy`, see [this forum thread](https://forum.rasa.com/t/contradicting-rules-or-stories-found/36563) and #7244 for the issues, #7235 for the fixes.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by wochinge — APPROVED** [review]
Please make sure to migrate the changelogs for the old patch releases for `2.0` to `master` as well

**Comment by samsucik** [comment]
@wochinge thanks!

> migrate the changelogs for the old patch releases for 2.0 to `master` as well

I'm not sure I understand what this translates to. Is it enough to merge `2.0.x` into `master` after the release is completed? (In this case, the plan is to first release 2.0.8, then merge `2.0.x` into `2.1.x`, then release 2.1.2. Would merging `2.1.x` into `master` after that achieve what we want?)

**Comment by wochinge** [comment]
>  Is it enough to merge 2.0.x into master after the release is completed?

You can do that yes 👍  However, please make sure that this merge doesn't introduce any regression. Basically the only diff should be the changelog and in your case the code for the bugfix.

**Comment by samsucik** [comment]
Okay, thanks for clarifying, Tobi 🙂

**Pull request merged**
