### PR TITLE
Rework the NLU training data format page

### LINKED ISSUE #4063: Rework the NLU training data page
We should rewrite that to use markdown examples for most of the features -- right now it uses json, which is very strange.
I think ideally we could have an element where you can switch from markdown to json, but the primary one should be markdown
https://rasa.com/docs/rasa/nlu/training-data-format/

### PR DESCRIPTION
**Pull request by msamogh**
Fixes #4063

**Changes**
1. Change the training data format from JSON to Markdown for all the examples
2. Add a general thematic note about how the various components work together
3. Move the Chatito part to the end (as it's mostly likely not relevant until they have learnt about the basic training format first)
4. Segregate synonyms from the other parts (since it doesn't affect the model)

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] updated the documentation
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by msamogh** [comment]
@MetcalfeTom When does this get merged?

**Comment by MetcalfeTom** [comment]
@msamogh Whenever you can catch it **after** the tests pass but **before** it is outdated with `master` 😄

**Comment by msamogh** [comment]
Intense!

**Comment by erohmensing** [comment]
got it! 😆

**Pull request merged**
