### PR TITLE
pin tensorflow-estimator to 2.1.0

### PR DESCRIPTION
**Pull request by m-vdb**
**Context**
I tried to install `rasa` using poetry and python 3.7.7, and it failed with this error: https://github.com/tensorflow/tensorflow/issues/37525

I tried the solution in [this comment](https://github.com/tensorflow/tensorflow/issues/37525#issuecomment-598480859) in my own project and it worked, so I am porting the change on the repo, so that other may benefit from the fix. (apparently I was not the only rasa user with this issue)

**Proposed changes**:
- Pin the version of `tensorflow-estimator`.

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by alwx** [comment]
If you change the dependencies then you should also update `poetry.lock` (it happens automatically when you run `poetry update` or `poetry install`)

**Comment by m-vdb** [comment]
@alwx I figured, but I have a weird diff ⬇️ 
```
diff --git a/poetry.lock b/poetry.lock
index a70b763a6aa..ef544ef07e9 100644
--- a/poetry.lock
+++ b/poetry.lock
@@ -55,7 +55,7 @@ version = "0.6.3"
 aiohttp = ">=2.0.0,<4.0.0"
 
 [[package]]
-category = "dev"
+category = "main"
 description = "A configurable sidebar-enabled Sphinx theme"
 name = "alabaster"
 optional = false
@@ -216,7 +216,7 @@ cryptography = ">=2.1.4"
 msrest = ">=0.6.10"
 
 [[package]]
-category = "dev"
+category = "main"
 description = "Internationalization utilities"
 name = "babel"
 optional = false
@@ -962,7 +962,7 @@ version = "1.1.0"
 idna = ">=2.0"
 
 [[package]]
-category = "dev"
+category = "main"
 description = "Getting image size from png/jpeg/jpeg2000/gif file"
 name = "imagesize"
 optional = false
@@ -1062,7 +1062,7 @@ python-versions = "*"
 version = "0.39"
 
 [[package]]
-category = "dev"
+category = "main"
 description = "A very fast and expressive template engine."
 name = "jinja2"
 optional = false
@@ -1251,7 +1251,7 @@ setuptools = ">=36"
 testing = ["coverage", "pyyaml"]
 
 [[package]]
-category = "dev"
+category = "main"
 description = "Safely add untrusted strings to HTML/XML markup."
 name = "markupsafe"
 optional = false
@@ -1689,7 +1689,6 @@ version = "2.5.0"
 [[package]]
 category = "main"
 description = "C parser in Python"
-marker = "sys_platform == \"win32\" and platform_python_implementation == \"CPython\""
 name = "pycparser"
 optional = false
 python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"
@@ -1715,7 +1714,7 @@ python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"
 version = "2.1.1"
 
 [[package]]
-category = "dev"
+category = "main"
 description = "Pygments is a syntax highlighting package written in Python."
 name = "pygments"
 optional = false
@@ -2067,7 +2066,7 @@ category = "main"
 description = "YAML parser and emitter for Python"
 name = "pyyaml"
 optional = false
-python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"
+python-versions = "*"
 version = "5.3"
 
 [[package]]
@@ -2423,7 +2422,7 @@ python = "<3.7"
 version = ">=2.1"
 
 [[package]]
-category = "dev"
+category = "main"
 description = "This package provides 26 stemmers for 25 languages generated from Snowball algorithms."
 name = "snowballstemmer"
 optional = false
@@ -2469,7 +2468,7 @@ ja = ["mecab-python3 (0.7)"]
 ko = ["natto-py (0.9.0)"]
 
 [[package]]
-category = "dev"
+category = "main"
 description = "Python documentation generator"
 name = "sphinx"
 optional = false
@@ -2527,7 +2526,7 @@ Sphinx = ">=1.7"
 test = ["pytest (>=3.1.0)", "typing-extensions (>=3.5)"]
 
 [[package]]
-category = "dev"
+category = "main"
 description = "Read the Docs theme for Sphinx"
 name = "sphinx-rtd-theme"
 optional = false
@@ -2585,7 +2584,7 @@ version = "1.0.2"
 sphinx = "*"
 
 [[package]]
-category = "dev"
+category = "main"
 description = "Sphinx extension that allows building versioned docs for self-hosting."
 name = "sphinxcontrib-versioning"
 optional = false
@@ -2603,7 +2602,7 @@ type = "git"
 url = "https://github.com/RasaHQ/sphinxcontrib-versioning.git"
 
 [[package]]
-category = "dev"
+category = "main"
 description = "Sphinx API for Web Apps"
 name = "sphinxcontrib-websupport"
 optional = false
@@ -3150,7 +3149,7 @@ spacy = ["spacy"]
 transformers = ["transformers"]
 
 [metadata]
-content-hash = "f11b37a3b8735943cebca76d0c8307b67dd2723641c7455b26b19ffadc9be14f"
+content-hash = "0aac797c555c164699a94d6324622c6cd8a8fec919ccac1a685f4583d5a1dc14"
 python-versions = "^3.6"
 
 [metadata.files]
@@ -3266,6 +3265,7 @@ boto = [
     {file = "boto-2.49.0.tar.gz", hash = "sha256:ea0d3b40a2d852767be77ca343b58a9e3a4b00d9db440efb8da74b4e58025e5a"},
 ]
 boto3 = [
+    {file = "boto3-1.12.8-py2.py3-none-any.whl", hash = "sha256:e8feb81da4602c5544bee1c106624b784315ae53b28ea6565a957318b8bf160a"},
     {file = "boto3-1.12.8.tar.gz", hash = "sha256:107fbf212daf1b25fff1efd6425c3e81be8db08d45e864197b0b61a6d12dbc60"},
 ]
 botocore = [
```

Any idea why? (poetry versions `1.0.0`)

**Comment by alwx** [comment]
Well, the only thing I can can suggest doing is updating to poetry 1.0.3 :)

But I don't see anything weird about that — `poetry.lock` updates automatically, and it's not very human-readable in general.

**Comment by m-vdb** [comment]
ok I'll upgrade and push it then!

**Comment by tmbo** [comment]
Let’s also add a comment and a link to the original issue to make sure we know why we added this (since it is not a direct dependency)

**Comment by m-vdb** [comment]
should I also add this link in the changelog msg?

**Comment by tmbo** [comment]
mhm, I'd say no - the changelog is for our users, e.g. for them the error message would be more important than how you fixed it.

**Comment by amn41** [comment]
first PR!! 🎉

**Pull request merged**
