### PR TITLE
Re add e2e reading

### PR DESCRIPTION
**Pull request by wochinge**
**Proposed changes**:
- last part of the revert of https://github.com/RasaHQ/rasa/pull/6518
- add support for reading end-to-end stories for **training** Rasa Open Source

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by Ghostvv** [comment]
@wochinge, we also need our `md` reader back for now as well, because we have e2e stories only in `md`

**Comment by wochinge** [comment]
It doesn't make any sense adding it back in as we can't merge it to `master` anyway. I suggest to convert the stories.

**Comment by Ghostvv** [comment]
yes, we'll see about removing it, but for now we need it. It is already implemented and it doesn't make sense to waste time on converting stories

**Comment by wochinge** [comment]
You have to convert these anyway before we are merging back to `master`, haven't you? The decision for Markdown was made so I don't see why we should do work which we will have to throw away anyway.

**Comment by Ghostvv** [comment]
no we don't have to convert these stories

**Comment by Ghostvv** [comment]
because when I suggested to create separate branch, you said you'll return everything back! Please do it

**Comment by wochinge** [comment]
Ok, makes absolutely no sense to me, but I can do it. I'm pretty busy with RC related tasks at the moment, so I'll have to see when I get to this.

**Comment by Ghostvv** [comment]
cool thanks

**Comment by wochinge** [comment]
@Ghostvv too many things changed in the markdown reader - I don't think it's worth the time to reapply all these changes.

**Comment by Ghostvv** [comment]
@evgeniiaraz can we continue working without markdown?

**Comment by evgeniiaraz** [comment]
@Ghostvv we can, but it will eat a bit of time on my side, but it's not the end of the world though.

**Comment by Ghostvv** [comment]
ok, @wochinge then could you please finish PR without markdown

**Review by evgeniiaraz — APPROVED** [review]
Looks good to me! 
I assume, the code is the same as before, right?

**Comment by wochinge** [comment]
@evgeniiaraz The production code implementation changed slightly as support for end-to-end testing was added on master

**Pull request merged**
