### PR TITLE
fix IL new action

### LINKED ISSUE #3296: "Create new action" in IL is broken
Using the current master `<create new action>` in interactive learning, skips the users option to enter a name and immediately throws an exception

### PR DESCRIPTION
**Pull request by paulaWesselmann**
**Proposed changes**:
- fixes #3296 
- the new action mapping was incorrect not allowing the user to create new actions, but skipping that step

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by paulaWesselmann** [comment]
This bug was introduced in one of the last commits in #3206 and must have slipped me and @akelad.
Thank you @anoop2503 for raising this issue!

**Comment by paulaWesselmann** [comment]
@anoop2503
you can change `OTHER_ACTION` to `NEW_ACTION` in here:
https://github.com/RasaHQ/rasa/blob/36077b97a649c691279826c068f184daa219f5d3/rasa/core/training/interactive.py#L622
This will hopefully fix the issue for you.

**Comment by anoop2503** [comment]
Great, thank you @paulaWesselmann. Will test it once, the code merge to master branch.

**Comment by anoop2503** [comment]
@paulaWesselmann Verified that code change and it seems like working fine so far. Let me do few more experiments with this. Thank you.

Also, is there any way to hide the warning/info messages which are being displayed in between the interactive training? I would say, these messages are annoying a bit. Sample messages are given below:

```
2019-04-23 05:18:21 INFO     sanic.access  - 
------
Chat History

 #    Bot            You        


Current slots: 
        environment: None, platform: None, requested_slot: None, server: None, support_type: None

------
[2019-04-23 05:18:21 +0000] - (sanic.access)[INFO][127.0.0.1:57032]: GET http://localhost:5005/conversations/cb8528acb99c4f4ab3a906d45e78be76/tracker?include_events=ALL  200 1264
2019-04-23 05:18:21 INFO     sanic.access  - 
? The bot wants to run 'action_listen', correct?  Yes
[2019-04-23 05:18:23 +0000] - (sanic.access)[INFO][127.0.0.1:57034]: GET http://localhost:5005/conversations/cb8528acb99c4f4ab3a906d45e78be76/tracker?include_events=AFTER_RESTART  200 380
2019-04-23 05:18:23 INFO     sanic.access  - 
[2019-04-23 05:18:23 +0000] - (sanic.access)[INFO][127.0.0.1:57036]: POST http://localhost:5005/conversations/cb8528acb99c4f4ab3a906d45e78be76/execute  200 512
2019-04-23 05:18:23 INFO     sanic.access  - 
[2019-04-23 05:18:23 +0000] - (sanic.access)[INFO][127.0.0.1:57038]: GET http://localhost:5005/conversations/cb8528acb99c4f4ab3a906d45e78be76/tracker?include_events=ALL  200 1371
2019-04-23 05:18:23 INFO     sanic.access  - 
[2019-04-23 05:18:23 +0000] - (sanic.access)[INFO][127.0.0.1:57040]: GET http://localhost:5005/conversations/cb8528acb99c4f4ab3a906d45e78be76/tracker?include_events=APPLIED  200 486
2019-04-23 05:18:23 INFO     sanic.access  - 
? Your input -> 
```

**Comment by paulaWesselmann** [comment]
@anoop2503 I agree that there is a lot of info messages, that are spamming the display. I'll raise this issue and see if they are all necessary or can be suppressed/ moved to debug mode.

**Comment by anoop2503** [comment]
Great! Thank you so much @paulaWesselmann

**Pull request merged**
