### PR TITLE
Fix rule policy training for slots with initial values

### PR DESCRIPTION
**Pull request by raoulvm**
**Rule policy was thrown off if slots have initial values defined**:
- addresses #11395 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by twerkmeister** [comment]
Hey @raoulvm, thanks so much for looking into this and tracking down the relevant code parts! I am thinking that it is probably even better to remove the configurability of `omit_unset_slot` entirely and make the logic so that unset slots are always ignored (so the opposite of what it is now). 

My reasoning being that initial values should be referenced explicitly in stories or rules if they have value for action prediction in a situation. Implicit inclusion, as we have seen, breaks the rule policy, probably also the Memoization policy, and probably forces the ML policies to ignore the slot in a lot of instances.

I am testing this approach in #11467. Will keep you updated.

**Comment by raoulvm** [comment]
Hello @twerkmeister , that is completely true. For reference, this is zendesk issue number 121

**Comment by twerkmeister** [comment]
Hey @raoulvm, thanks again for taking a stab at this one. I have merged a solution into the mainline earlier today and have ported it to `2.8.x` as well which is currently under review (#11498).

Digging a little deeper, I diverged from your approach and have assessed several different solutions. You can read more about them in the PR #11480. I went for simply skipping the cache when the states of the tracker are requested with `omit_unset_slots=True`. This only happens once, during the training of the rule policy. I thought this is better than having a least recently used type of caching which your solution goes for, given that all policies but the rule policy request the states with `omit_unset_slots=False`. With LRU of size 1 you might get some flipping back and forth of the cache with every request.

**Comment by raoulvm** [comment]
That is `True`

From: Thomas Werkmeister ***@***.***>
Date: Wednesday, 17. August 2022 at 15:37
To: RasaHQ/rasa ***@***.***>
Cc: von Metzen, Raoul ***@***.***>, Mention ***@***.***>
Subject: Re: [RasaHQ/rasa] Fix rule policy training for slots with initial values (PR #11465)

Ok I figured that omit_unset_slots is indeed necessary. I believe that I was right when it comes to the training time, where the initial slot values should not be incorporated. When generating the states of a current conversation however, you need to incorporate them.

I now understand the proposed solution better. We are mainly dealing with a caching issue here. The tracker states are cached with omit_unset_slots initially set to false. When they are requested by rule policy with omit_unset_slots=True one still gets the states as if it was set to false.

And you are checking wether the tracker states were cached with the same option as they were requested, otherwise they are regenerated.

**Pull request closed without merging**
