### PR TITLE
Revert "Implement FilterAndRerank for policy prediction"

### PR DESCRIPTION
**Pull request by varunshankar**
Reverts RasaHQ/rasa#12112

### CODE REVIEW

**Comment by varunshankar** [comment]
With the change in the spaces technical proposal, we need to merge this.

**Comment by m-vdb** [comment]
can you take care of it? thanks!

**Comment by varunshankar** [comment]
Ya, I'm taking care of it. I planned to merge this PR after I merge custom actions to avoid merge conflicts.

**Review by Shmuma — APPROVED** [review]
Looks good!

**Pull request merged**
