### PR TITLE
Fix tests on e2e branch

### PR DESCRIPTION
**Pull request by tabergma**
**Proposed changes**:
Fixes all tests on the `e2e` branch.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by tabergma** [comment]
@Ghostvv Still work in progress, but I think I need your help on some of the tests. Could you take a look at the remaining test failures in `test_policies.py`?

**Comment by tabergma** [comment]
@Ghostvv The following tests are failing. Not 100% how to fix those. Can you please take a look? Thanks.

```
FAILED tests/core/test_policies.py::TestMemoizationPolicy::test_memorise_with_nlu
FAILED tests/core/test_policies.py::TestAugmentedMemoizationPolicy::test_memorise_with_nlu
FAILED tests/core/test_processor.py::test_handle_message_with_session_start
FAILED tests/core/test_processor.py::test_get_next_action_probabilities_passes_interpreter_to_policies
FAILED tests/core/test_processor.py::test_get_next_action_probabilities_pass_policy_predictions_without_interpreter_arg[<lambda>0]
FAILED tests/core/test_processor.py::test_get_next_action_probabilities_pass_policy_predictions_without_interpreter_arg[<lambda>1]
FAILED tests/shared/core/test_trackers.py::test_tracker_state_regression_with_bot_utterance
FAILED tests/shared/core/test_trackers.py::test_bot_utterance_comes_after_action_event
FAILED tests/shared/importers/test_importer.py::test_import_nlu_training_data_from_e2e_stories
```

**Comment by Ghostvv** [comment]
@tabergma thank you, I'll take a look today/tomorrow

**Review by Ghostvv — APPROVED** [review]
all tests pass, shall we merge it?

**Pull request merged**
