### PR TITLE
fix adding slot values to states

### PR DESCRIPTION
**Pull request by Ghostvv**
**Proposed changes**:
- slots should be added even if user didn't say anything

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by wochinge** [comment]
@Ghostvv I am on vacation. Please request someone else

**Review by tabergma — COMMENTED** [review]
Looks good! 

Not sure, but do we need a changelog entry and maybe a test for it?

Also as it is a change in `rasa.shared` I think someone from the production squad needs to review it.

**Comment by Ghostvv** [comment]
I'll add changelog and test

**Comment by Ghostvv** [comment]
@degiz I don't understand how my changes would fail the test `test_handle_message_with_session_start`, could you please take a look?

**Review by degiz — APPROVED** [review]

**Review by joejuzl — COMMENTED** [review]
LGTM 👍

**Pull request merged**
