### PR TITLE
Prepare release 2.2.0

### PR DESCRIPTION
**Pull request by joejuzl**

### CODE REVIEW

**Review by wochinge — APPROVED** [review]
Thanks for coordinating this release so patiently! 💯

**Comment by m-vdb** [comment]
@joejuzl I've just pushed a commit to fix the bandit check, they updated a few things in version 1.7 and it's only coming up now on this PR 🤷🏻

**Comment by m-vdb** [comment]
about the timeout issues, it's possible to control the timeouts on particular tests using `@pytest.mark.timeout(300)` for instance. Default timeout is [120 second](https://github.com/RasaHQ/rasa/blob/master/pytest.ini)

**Comment by joejuzl** [comment]
> about the timeout issues, it's possible to control the timeouts on particular tests using @pytest.mark.timeout(300) for instance. Default timeout is 120 second

We probably don't want tests taking more than 120 seconds though to be honest. Increasing the timeout seems like fixing the wrong problem.

**Pull request merged**
