### PR TITLE
Add og:image to the docs

### PR DESCRIPTION
**Pull request by maggo**
**Proposed changes**:
- Adds `og:image` file and property in the custom docs theme

**Status (please check what you already did)**:
- [x] updated the documentation

### CODE REVIEW

**Review by lunelson — CHANGES_REQUESTED** [review]
Nice find @maggo ! I think this is an elegant solution. Can you verify whether the og-image related tags are now complete, and add any that are missing? See [metatags.io](https://metatags.io/) as a reference

@m-vdb if you're cool with this method, Marco or I would repeat the same on the other repos

**Comment by maggo** [comment]
> Can you verify whether the og-image related tags are now complete, and add any that are missing? See [metatags.io](https://metatags.io/) as a reference

Had a quick check, all required fields title, description, url, image will be there after this merge

**Review by lunelson — APPROVED** [review]

**Comment by m-vdb** [comment]
@lunelson good for me, but to be honest I'm missing context and I don't think I can give a proper review. If you're fine with this change, I'm fine.

**Comment by lunelson** [comment]
@m-vdb yeah this is the way to do this, AFAICT for the `alpha.63` version of Docusaurus that we're on here, and we have the custom theme anyway; I've made a [PR against `rasa-x`](https://github.com/RasaHQ/rasa-x/pull/6751) which uses the newer config options however

**Comment by lunelson** [comment]
BTW @m-vdb is `main` the right merge target here?

**Comment by m-vdb** [comment]
yes I think so

**Comment by maggo** [comment]
Rebased onto the latest master.
Will also port this change to https://github.com/RasaHQ/rasa-sdk

**Pull request merged**
