### PR TITLE
Enable convert to yml

### PR DESCRIPTION
**Pull request by koszta5**
**Proposed changes**:
- Add support to enable conversion to YML for NLU file

**Status (please check what you already did)**:
- [✅ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [✅] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @tabergma will take a look at it as soon as possible ✨

**Comment by tabergma** [comment]
Thanks for submitting the PR @koszta5! We are actually already supporting this, see [here](https://github.com/RasaHQ/rasa/blob/master/rasa/cli/data.py#L305). What is the reason adding this to the other method as well?

**Comment by koszta5** [comment]
OK @tabergma - that makes sense to me, now what does not make sense to me is having 2 methods for the same thing in different places :P 
The place where I made the edit - I originally used this script externally from bash to convert chatito generated json file to MD. I confess I didnt know about the functionality in cli/data.py. 

But that being said - my PR allows json -> yaml conversion. While if using the cli/data.py you would need to do JSON -> MD -> YAML

Care to make any decision how it taken from here? Do you want me to keep both places? Please provide more isight :) I m more than open to adjust things how you think they should be.

**Comment by degiz** [comment]
Hey @koszta5 

Do you mean that `rasa data convert nlu -f yaml` won't convert the `JSON` directly to the `YAML`?

**Pull request closed without merging**
