### PR TITLE
removed unused imports

### PR DESCRIPTION
**Pull request by sureshdsk**
**Proposed changes**:
- remove unused imports mentioned in issue #7041 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @b-quachtran will take a look at it as soon as possible ✨

**Review by b-quachtran — APPROVED** [review]
🚀 🚀

**Comment by alwx** [comment]
@sureshdsk could you please rebase it?

**Comment by wochinge** [comment]
This is done and enforced by flake now.

**Pull request closed without merging**
