### PR TITLE
use the right GH token for ci-model-regression-on-schedule.yml

### PR DESCRIPTION
**Pull request by m-vdb**
**Proposed changes**:
- Some GH issues created by `ci-model-regression-on-schedule` are not assigned to the right GH project (example: https://github.com/RasaHQ/rasa/issues/9154)
- Use `RASABOT_GITHUB_TOKEN` to trigger subsequent workflows

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by m-vdb** [comment]
@dakshvar22 FYI, I've noticed that the issues weren't assigned to the Research Issues board. This PR should fix it, and I've added the issues manually

**Review by tczekajlo — APPROVED** [review]
LGTM 🎖️

**Comment by dakshvar22** [comment]
@m-vdb Just out of curiosity and my learning: From the files changed, it's not clear to me how you are fixing: `Some GH issues created by ci-model-regression-on-schedule are not assigned to the right GH project (example: Scheduled Model Regression Test Failed #9154)`

How is that being handled?

**Comment by m-vdb** [comment]
the workflow used `GITHUB_TOKEN`, [which doesn't trigger subsequent workflows](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow) (when creating an issue in this case). I've changed the token to our custom `RASABOT_GITHUB_TOKEN` to fix that

**Comment by dakshvar22** [comment]
Ahh! It's a subsequent workflow which enables that. Sounds good. Thanks for fixing it 🙌

**Pull request merged**
