### PR TITLE
Add new events data

### PR DESCRIPTION
**Pull request by shotamakino**
**Proposed changes**:
- Adds a new message_type field in the 'user' event, and extends fb input channel to include this data

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by wochinge** [comment]
@shotamakino Thanks for submitting this pr! 
I think we should maybe cover this as part of https://github.com/RasaHQ/rasa/issues/3199 instead of doing this separately.

**Comment by shotamakino** [comment]
Okay! If that makes sense to your team. I did have a roadmap of extending all the channels to provide the message type field as well, and possibly the concept of an 'message id' in the events objects so that we can tie multiple events together to the same message.

**Comment by wochinge** [comment]
@shotamakino https://github.com/rasahq/rasa/pulls?utf8=%E2%9C%93&q=metadata is merged. Could you check whether you could put the new attribute in the metadata dict of the `UserMessage`?

**Comment by shotamakino** [comment]
apologies for the late reply. closing this now and will attempt at it again in the future. I also saw an enhancement req that might be relevant so will take a crack at that

**Comment by wochinge** [comment]
Ok @shotamakino 👍 Thanks for a all your effort! Hope to see you around in the community and let me know if you need any help with PR's. You can also create an `new feature` issue first, which we can use to discuss different implementation approaches.

**Pull request closed without merging**
