### PR TITLE
issue: #10617 Regex extractor ending or staring with special character

### PR DESCRIPTION
**Pull request by azizullah2017**
**Proposed changes**:
- ...
fixed and issue ,  Regex extractor does not work on entity value staring or ending with special character #10617 

https://github.com/RasaHQ/rasa/issues/10617
**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by tttthomasssss — CHANGES_REQUESTED** [review]
Thanks very much for submitting a PR that fixes #10617 🚀.

Could you add the following: 
* an entry in the changelog with a brief description of your fix (see [here](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
* run `black` to reformat the code (if you haven't already done so) - see [here](https://github.com/RasaHQ/rasa#code-style) for instructions
* Add appropriate test cases to `tests/nlu/extractors/test_regex_entity_extractor.py`

**Comment by tttthomasssss** [comment]
Hey @azizullah2017 👋 - just to check, are you still working on the PR and/or do you need any help getting it done?

**Comment by azizullah2017** [comment]
@tttthomasssss yes, I am working on this. working on changes.

**Comment by m-vdb** [comment]
Hi there! Thanks for your contribution. As the PR has been stale for a while, I'm closing it. Please feel free to reopen an issue / PR if the problem still occurs on latest rasa versions.

**Pull request closed without merging**
