### PR TITLE
fix docs for implementing two-stage fallback.

### PR DESCRIPTION
**Pull request by prathameshThakur**
**Proposed changes**:
- Fixes: #7237

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by prathameshThakur** [comment]
Looks good from my side, but don't know why there is a test fail for `Continuous Integration / Code Quality (pull_request)`.
@melindaloubser1 can you please review this..

**Comment by melindaloubser1** [comment]
This is the error in CI - not sure why it's happening here, doesn't usually complain about forked repo branches. I'll find out what's wrong.
```
Run git fetch origin master
From https://github.com/RasaHQ/rasa
 * branch                master     -> FETCH_HEAD
 * [new branch]          master     -> origin/master
fatal: couldn't find remote ref update-doc-7237
Error: Process completed with exit code 1.
```

**Comment by prathameshThakur** [comment]
Yes...
And please let me know if any changes required from my side... 😊

**Review by melindaloubser1 — APPROVED** [review]

**Comment by wochinge** [comment]
This might be failing due to `pydocstring`. Please let me know if the build fails again.

**Comment by prathameshThakur** [comment]
@wochinge I guess all the tests are working fine now!!
Do I need to make any changes or commits!?

**Comment by melindaloubser1** [comment]
Nope you're all good! Thanks for the contribution

**Pull request merged**
