### PR TITLE
Move activation to transformer block

### PR DESCRIPTION
**Pull request by tabergma**
**Proposed changes**:
Move activation to transformer block.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by dakshvar22** [comment]
I think @ghostvv wanted to place the call to the activation inside DIET conditioned on usage of transformer and not place it inside transformer?

**Comment by Ghostvv** [comment]
yes, let's keep transformer a "classic" transformer

**Comment by Ghostvv** [comment]
@tabergma this update requires retraining the model

**Comment by tabergma** [comment]
True. I guess it is already released 🙈

**Comment by Ghostvv** [comment]
that is a bit dangerous, since prediction might go haywire, because technically models can be loaded

**Comment by tabergma** [comment]
any suggestion on how to solve that?

**Comment by Ghostvv** [comment]
can we update docs and rerelease?

**Pull request merged**
