### PR TITLE
add tracker to interpreter context

### PR DESCRIPTION
**Pull request by pdan93**
**Proposed changes**:

- Add the tracker to the interpreter context so that it can be used by custom components in the NLU pipeline. 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by pdan93** [comment]
Hi. I had this problem while trying to do coreference. The tracker (especially the events) isn't available in any way in the interpreter. This is the cleanest way, cause it simply puts it in the interpreter's context variable, which as far as I can see, it's exactly that, a 'context' memory area.

**Comment by ancalita** [comment]
Hi @pdan93 we are currently in the process of revamping the entire rasa architecture for the 3.0 release scheduled in Q4-21. These changes will allow for much more flexible custom models, I would suggest waiting for this release and checking if the new changes solve your use-case?

**Comment by pdan93** [comment]
> Hi @pdan93 we are currently in the process of revamping the entire rasa architecture for the 3.0 release scheduled in Q4-21. These changes will allow for much more flexible custom models, I would suggest waiting for this release and checking if the new changes solve your use-case?

Hello. Sounds good. I kind of expected that you would redo the arhitecture in 3.0. It's good to hear it's scheduled for Q4 :)
Thanks

**Comment by wochinge** [comment]
@pdan93 We are currently working on a big architecture revamp which will unfortunately invalidate the given change. We will hopefully merge our changes to `main` soon (somewhen next week). Happy to discuss how we can apply such a change then (would be great if you could open an issue to discuss this first as this change has quite a lot of implications).

**Pull request closed without merging**
