### PR TITLE
Fix duplicated warning from tensorflow and sanic

### PR DESCRIPTION
**Pull request by tabergma**
**Proposed changes**:
- Log WARNING from tensorflow and sanic only once.

related to https://github.com/RasaHQ/rasa/issues/3272

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by Ghostvv** [comment]
Which one will be outputted?
```
WARNING:tensorflow:From /Users/ghost/Documents/rasa/rasa/rasa/core/policies/embedding_policy.py:451: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
```
or
```
2019-05-08 11:12:18 WARNING  tensorflow  - From /Users/ghost/Documents/rasa/rasa/rasa/core/policies/embedding_policy.py:451: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
```
I'd prefer the second

**Comment by tabergma** [comment]
The first one. But as it is related to tensorflow, we cannot do much about it. We can keep both or the first one.

**Comment by Ghostvv** [comment]
Why with the old script, it is only the second?

**Comment by tabergma** [comment]
In order to set the log level of tensorflow, we added the line `tf.logging.set_verbosity(tf_log_level)`. Apparently, this adds a new stream handler that causes the duplication of the log message (see https://github.com/tensorflow/tensorflow/issues/8023). Using `logging.getLogger("tensorflow").propagate = False` the message gets not propagated from the child handler to the parent handler anymore.

**Pull request merged**
