### PR TITLE
Merge 2.3.x in main

### PR DESCRIPTION
**Pull request by dakshvar22**
**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by wochinge — APPROVED** [review]

**Comment by m-vdb** [comment]
@tmbo 😬 why did you merge this branch? the tests were still failing. I just pushed a commit to fix it: https://github.com/RasaHQ/rasa/commit/ed134cd921a7f6158f768f3d3b9506e9922d7a2e

**Comment by m-vdb** [comment]
Opening another PR to fix it

**Comment by tmbo** [comment]
😂 I needed something from that branch - and it was approved + green so = 🤷. Sorry, it wasn't obvious that this PR wasn't ready yet

**Comment by m-vdb** [comment]
definitely not on you, Daksh [requested help from engineering to merge this on Friday](https://rasa-hq.slack.com/archives/C36SS4N8M/p1614356054179000), the integration tests were not passing (actually were flaky). Fixed it in https://github.com/RasaHQ/rasa/pull/8094

**Comment by tmbo** [comment]
thanks a lot for jumping on a fix 💯

**Pull request merged**
