### PR TITLE
Create a separate Docker base image for a build step

### PR DESCRIPTION
**Pull request by tczekajlo**
**Proposed changes**:
- Some libraries installed in the Docker base image are needed only during building the python packages. We can move them to a separate image that is used only for build purposes

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by mprazz** [comment]
@tczekajlo  can we run all tests on this, to make sure it all works?

**Comment by tczekajlo** [comment]
> @tczekajlo can we run all tests on this, to make sure it all works?

We run all tests that we have available in the rasa repository :D

**Comment by tczekajlo** [comment]
@m-vdb one improvement more to the recent changes, can you take a look if you have a minute?

**Review by mprazz — APPROVED** [review]
Can't find any issues, LGTM! 🚀

**Pull request merged**
