### PR TITLE
change for e2e actions in domain; adding actions from domain to actions

### PR DESCRIPTION
**Pull request by evgeniiaraz**
**Proposed changes**:
- Action names into domain

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by wochinge** [comment]
@evgeniiaraz Should I wrap this up as part of https://github.com/RasaHQ/rasa/issues/6410 or do you need it asap?

**Comment by evgeniiaraz** [comment]
@wochinge no, it's not super urgent! so, yes, it can be done in that PR

**Comment by Ghostvv** [comment]
part of new core featurization for e2e without e2e

**Comment by Ghostvv** [comment]
outdated due to https://github.com/RasaHQ/rasa/pull/6445

**Pull request closed without merging**
