### PR TITLE
Premerge branch 2.2.8

### PR DESCRIPTION
**Pull request by Imod7**
**Proposed changes**:
- Merge 2.2.x to main

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by joejuzl** [comment]
@wochinge I thought that micros were merged into release branches? Is that not the case anymore?

**Comment by wochinge** [comment]
@joejuzl 2.2.8 was already released. This is just merging the 2.2.x to `main` to have bug fixes and changelog applied

**Comment by joejuzl** [comment]
@wochinge Yeah I understand that it's already deployed. I thought we would merge `2.2.x` rather than the micro release branch, but I guess it's the same effect.

**Review by joejuzl — APPROVED** [review]

**Comment by wochinge** [comment]
This branch is actually branched of `2.2.x`. It's just an extra branch so that we can deal with any merge conflicts etc.

**Comment by joejuzl** [comment]
Good job on the release @Imod7 ! 🚀

**Pull request merged**
