### PR TITLE
Change default augmentation parameter

### LINKED ISSUE #6550: set `--augmentation 0` by default in `rasa train` and `rasa train core`

### PR DESCRIPTION
**Pull request by tabergma**
**Proposed changes**:
Change the default parameter for `augmentation` for `rasa train` commands from `50` to `0`.

closes #6550 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by Ghostvv** [comment]
before we do that, we need to run experiments on all available core datasets, to make sure it doesn't reduce performance. cc @akelad

**Comment by tabergma** [comment]
Ok, will use the model regression tests for that.

**Comment by Ghostvv** [comment]
but our model regression tests are nlu only, no?

**Comment by tabergma** [comment]
Yeah, makes sense. Too bad we can not use the model regression tests for this. Will run some experiments.

Why do we actually want to have this change?

**Comment by Ghostvv** [comment]
Because, it increases training time drastically, but we're not sure that with the new system (Rules+TED) it'd add to performance

**Comment by tabergma** [comment]
Do we already have Sara data in the new training data format using rules? And what about carbon bot?

**Comment by Ghostvv** [comment]
there are `rule` or `rules` branches, for them, but I don't know how fully updated they are

**Comment by tabergma** [comment]
Ok, does it make sense then to wait until those datasets are fully available so that we can test properly? We could close the PR until then.

**Comment by Ghostvv** [comment]
cc @evgeniiaraz

**Comment by tabergma** [comment]
Ok, will close this PR for now. Let's reopen once the datasets to test this are ready.

**Pull request closed without merging**
