### PR TITLE
Replace os.path for pathlib in utils and core modules

### PR DESCRIPTION
**Pull request by silvasara**
**Proposed changes**:

- Replace os.path for pathlib in `utils` and `core` modules to improve readability
- Resolves partially issue #3153

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @degiz will take a look at it as soon as possible ✨

**Comment by degiz** [comment]
@silvasara Are we closing the https://github.com/RasaHQ/rasa/pull/7118 then?

**Comment by silvasara** [comment]
> @silvasara Are we closing the #7118 then?

@degiz No, the [#7188](https://github.com/RasaHQ/rasa/pull/7118) is only for the `NLU` module, this PR is for the `utils` and `core` modules. We decided to do as suggested by the author of the issue #3153 , solving it in separate PRs.

**Review by degiz — COMMENTED** [review]
Thanks a lot for working on that 👍

**Comment by silvasara** [comment]
@degiz The pipeline is breaking in the windows tests, but I didn't find any relationship between these tests and the changes made in this PR, how to proceed in this case?

**Comment by wochinge** [comment]
@degiz Could you please come back to @silvasara ?

**Comment by degiz** [comment]
Hey @silvasara 

Shall we close the #7118 first? 😅

**Comment by silvasara** [comment]
> Hey @silvasara
> 
> Shall we close the #7118 first?

The two PRs are independent because the changes are made in different modules

**Comment by degiz** [comment]
Sure, but it's already approved and waits to be merged 😄

**Comment by degiz** [comment]
@silvasara  are you still working on this?

**Comment by silvasara** [comment]
@degiz I'm not.

**Pull request closed without merging**
