### PR TITLE
Two stage fallback policy actions deprecated

### LINKED ISSUE #6623: Mark default action of `TwoStageFallbackPolicyAction` as deprecated
Due to the introduction of the `RulePolicy` the `TwoStageFallbackPolicy` is deprecated. The `TwoStageFallbackPolicy` uses a couple of default actions:

- `action_revert_fallback_events`
- ~`action_default_ask_affirmation`~ (can be kept, used by new `TwoStageFallback`)
- ~`action_default_ask_rephrase`~ (can be kept, used by new `TwoStageFallback`)

We don't need them to deprecate them in the code as the policies which are using these actions are already deprecated. 

Todos:
- [x] update documentation for `default-actions` to reflect that the actions from above are deprecated
- [ ] Leave a comment in each of these actions in the code that they are deprecated and can be removed once the `TwoStageFallbackPolicy` is removed. 
- [ ] rename `two_stage_fallback` action to `action_two_stage_fallback `

### PR DESCRIPTION
**Pull request by musa-atlihan**
- fix #6623

**Proposed changes**:

- fixed a link in default-actions.mdx
- two_stage_fallback named changed to action_two_stage_fallback
- a comment added in ActionRevertFallbackEvents as deprecated

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @melindaloubser1 will take a look at it as soon as possible ✨

**Comment by wochinge** [comment]
@musa-atlihan Thanks so much for taking this on. I was on vacation, will review this today 👍

**Review by wochinge — COMMENTED** [review]
Thanks for this change @musa-atlihan ! It's so cool that you're helping us with the 2.0 release 🚀 

I found a couple of other todo items:
- [ ] rename `two_stage_fallback` to `action_two_stage_fallback` in `fallback-handoff.mdx`
- [ ] rename `two_stage_fallback` to `action_two_stage_fallback` in `migration-guide.mdx`
- [ ] Please add a short comment to `action_revert_fallback_events` that it is deprecated and can be removed once the `TwoStageFallbackPolicy` is deprecated? A simple comment is enough because we already have a deprecation warning for the policy itself

**Comment by musa-atlihan** [comment]
Thank you for the review @wochinge , I am ok with the changes for the first two in the todo list, however a bit confused about the third one. I had done a comment in the class itself here https://github.com/RasaHQ/rasa/blob/7e4b8d7c087717a04209c70a92ef67dba11aa625/rasa/core/actions/action.py#L685

but could you guide me if I need to update it to something else? Thank you.

**Comment by wochinge** [comment]
> I had done a comment in the class itself here

Nevermind. Somehow overlooked that 🙈 👍

**Comment by musa-atlihan** [comment]
awesome, thank you! I am pushing the new commits now.

**Comment by wochinge** [comment]
@musa-atlihan `test_rule_policy_slot_filling_from_text` is currently failing (please ignore the ConvertFeaturizer stuff - that's currently a problem on our side as another party took down the model serving this component 🙈 )

**Comment by musa-atlihan** [comment]
yep, I hope this last commit resolves it.

**Review by wochinge — APPROVED** [review]
Thanks a lot @musa-atlihan 🎉

**Comment by musa-atlihan** [comment]
thank you @wochinge , was a very nice experience!

**Comment by wochinge** [comment]
Fixing the failing test here https://github.com/RasaHQ/rasa/pull/6847 🙈

**Comment by wochinge** [comment]
Finally merged 🎉

**Pull request merged**
