### PR TITLE
#3863 added attachment handling to socketio channel

### LINKED ISSUE #3863: socketio channel should also support attachments
**Description of Problem**:
Socketio channel cannot handle attachments. Because of this, attachments are handled as text messages, which cannot be parsed by Webchat JS clients.

**Overview of the Solution**:
add send_attachment method to socketio.py, like so: 

```
async def send_attachment(
        self, recipient_id: Text, attachment: Iterable[Dict[Text, Any]], **kwargs: Any
    ) -> None:
        """Sends attachment to the output."""        
        await self._send_message(self.sid, {"attachment" : attachment})
```

I can create a pull request if needed. 

**Definition of Done**:
- [ ] Tested with webchat JS clients
- [ ] Feature is documented

### PR DESCRIPTION
**Pull request by mechko**
**Proposed changes**:
- added function to handle attachment sending in socketio channel, so that Webchat JS clients can handle those attachments, see feature request #3863 
- fixes #3863 
**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

I executed the pytest tests locally (running _python3 -m pytest tests_), there is at least no increased rate of errors, warnings or failed tests (47 failed, 823 passed, 135 warnings, 25 error). Maybe you could add some documentation on how to prepare and execute tests, and I don't know if this failed rate is the expected result (disclaimer: I have only very few knowledge about the python ecosystem). I had a look at _tests/core/test_channels.py_ and found no tests on single use cases for socketio, so I decided to not begin with this yet.

### CODE REVIEW

**Comment by akelad** [comment]
Great to see you making your first contribution :D Thanks a lot for submitting the PR, we'll give it a review as soon as possible!

**Comment by mechko** [comment]
I already signed the CLA, when I try to do it again the CLA tool says: _You have signed the CLA for RasaHQ/rasa_ (using the link provided by CLAassistant above).

**Comment by mechko** [comment]
Seems my mail address was not assigned correctly for the first commit, sorry for that. How do we proceed now? Should we close this PR and open a new one?

**Comment by akelad** [comment]
can you add the email address from that commit to your github profile? alternatively close this PR and resubmit it with commits only from the correct account

**Comment by mechko** [comment]
I'm afraid I there not an email attached to the first commit, so I'm closing this PR. I generated a new one below https://github.com/RasaHQ/rasa/pull/3891.

**Pull request closed without merging**
