### PR TITLE
Remove text argument from send_attachment function in  slack.py

### PR DESCRIPTION
**Pull request by vigneshp826**
**Proposed changes**:
- Removed text argument in send_attachment function to avoid duplicate text replies to Slack channel id
- https://forum.rasa.com/t/duplicating-attachments-with-text-in-slack-channel-output/14932  -- Detailed reason for the change is  here

**Status (please check what you already did)**:
- [x] made PR ready for code review

### CODE REVIEW

**Comment by erohmensing** [comment]
Hey @vigneshp826, thanks for the PR! Did you try also adding the kwargs back in to the Slack API call?

**Comment by vigneshp826** [comment]
@erohmensing added now. Hope i didn't miss anything now :)

**Comment by erohmensing** [comment]
Thanks! Tested it out and it looks good to me. Could you do me one more thing and add a changelog entry?

**Comment by vigneshp826** [comment]
@erohmensing any changelog policy document is there that i can refer?

**Comment by erohmensing** [comment]
@vigneshp826 you want to edit this file: https://github.com/RasaHQ/rasa/blob/master/CHANGELOG.rst

In this case i would put it under `fixed`. Something like "fixed duplication of Slack attachment text" or something like that -- however you want to phrase it :)

**Comment by vigneshp826** [comment]
@erohmensing thanks for the patience. My first PR, hope i will do better in next PR :) .

**Comment by erohmensing** [comment]
No problem! We're here to teach :)  Because you're merging this into master, instead of `1.2.x` (our development branch for the next patch release, in this case 1.2.8), you would add it to the changelog under `master`. The numbers don't actually increment each time someone merges a PR, but rather when we release the next version. Maybe that clears things up!

I moved the entry -- I hope you don't mind :) I want to get this merged before 1.3 releases, which should be very soon! Then your changes will be reflected. 

Also, it's best if you create branches on your own fork for different features/big fixes -- that way your master branch can stay up to date with ours, which makes it easier for you to contribute again 🚀

**Pull request merged**
