### PR TITLE
FloatSlot._as_feature should return unambiguous values

### PR DESCRIPTION
**Pull request by koernerfelicia**
Currently, if a float slot value is set to `0.0` and the min value is `0.0`, `FloatSlot._as_feature` will return `0.0`. However, this is also the default value returned when the value could not be converted. As a result, the slot is considered "unfilled" and isn't added:

Screenshot 2020-11-12 at 20 47 20

See user issue [here](https://github.com/RasaHQ/rasa/issues/7244)

**Proposed changes**:
- Make `FloatSlot` return two floats:
`[1.0, <value>]` if successfully converted
`[0.0, 0.0]` if not
This mimics the behaviour of `BooleanSlot`

**Status (please check what you already did)**:
- [X] added some tests for the functionality -> (updated existing tests)
- [X] updated the documentation -> (not really user-facing, the functionality should stay the same from the outside)
- [X] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [X] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by tmbo** [comment]
this is a model breaking change and needs to increase the minimum compatible model version

**Comment by tmbo** [comment]
@dakshvar22 should we run the model evaluation tests on this?

**Review by tmbo — CHANGES_REQUESTED** [review]
looks good, some minor remarks + breaking change as mentioned

**Comment by dakshvar22** [comment]
@tmbo Model regression tests are only for NLU at the moment, so not needed here.

**Comment by koernerfelicia** [comment]
>this is a model breaking change and needs to increase the minimum compatible model version
@tmbo: thank you for taking a look! What does the above mean in terms of action items? I'm guessing it has to be documented somewhere, just not sure where

**Comment by tmbo** [comment]
your changelog item should include a warning, e.g. here is an example: https://rasa.com/docs/rasa/changelog#deprecations-and-removals

and you'll need to increase the version in https://github.com/RasaHQ/rasa/blob/master/rasa/constants.py#L27

**Comment by koernerfelicia** [comment]
@tmbo sorry, could you take another look? I'm not sure why this is failing - I updated the rasa-sdk version by hand, maybe I shouldn't have done this?

**Comment by koernerfelicia** [comment]
Hi @tmbo, I think this is finally ready. I'm sorry it got so messy and required so many revisions... I definitely know better now for the future.

**Comment by tmbo** [comment]
don't worry, e.g. the poetry issues and needed updates aren't your fault - was actually good that we ran into that to fix it :+1:

**Review by tmbo — APPROVED** [review]
looks great :rocket:

**Pull request merged**
