### PR TITLE
Added option to persist nlu training data (default: False). Added tes…

### PR DESCRIPTION
**Pull request by ronancummins**
…ts for both cases. Modified existing test (which broke) such that it now passes. For issue #4347 

**Proposed changes**:
- #4347 

**Status (please check what you already did)**:
- [ x] made PR ready for code review
- [ x] added some tests for the functionality
- [ ] updated the documentation
- [ x] updated the changelog
- [ x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by tmbo** [comment]
Thanks for this PR. Did all of the commits come from your account? looks like your git email changed between commits

**Comment by ronancummins** [comment]
Yes they did. I hadn't set my user.email git variable and the CLA complained. I updated it and also updated the CHANGELOG which I had not done...

**Comment by ronancummins** [comment]
No problem, modifications look sensible... Thanks..

**Comment by akelad** [comment]
@ronancummins i just noticed that there's no flag you can pass to the cli to enable storing nlu training data - would you be up for submitting a PR to fix that?

**Comment by ronancummins** [comment]
@akelad I'll have a look and see what I can do over the next week. A yes, basically..

**Pull request merged**
