### PR TITLE
Multiple links in message - Slack sanitization

### PR DESCRIPTION
**Pull request by vigneshp826**
**Proposed changes**:
- This PR is part of Slack Sanitization #4418 . PR #4475 taken care only one link instead of converting 
   multiple links if present.

**Status (please check what you already did)**:
- [X] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [X] updated the changelog
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by vigneshp826** [comment]
@tmbo can you let me know where i need to do that?

**Comment by erohmensing** [comment]
@vigneshp826 you could add examples here: https://github.com/RasaHQ/rasa/blob/master/tests/core/test_channels.py#L464

**Comment by erohmensing** [comment]
@vigneshp826 are you still planning on finishing this PR?

**Comment by vigneshp826** [comment]
@erohmensing little bit busy in my BAU activities. Will try t complete next week. Sorry for the delay

**Comment by erohmensing** [comment]
Okay, just wanted to check it wasn't going stale. 

The mechanism for changelog has changed since, please remove your changelog file and follow [these instructions](https://github.com/RasaHQ/rasa/tree/master/changelog)

**Comment by vigneshp826** [comment]
@tmbo @erohmensing  added the test piece of code and changelog, let me know if any changes required

**Pull request merged**
