### PR TITLE
Add redis sentinel configuration

### LINKED ISSUE #3924: Support for Redis sentinel
We should provide for Redis sentinel ([https://redis.io/topics/sentinel](https://redis.io/topics/sentinel)) for high availability tracker stores.

This one is a good resource how to implement it: [https://github.com/andymccurdy/redis-py#sentinel-support](https://github.com/andymccurdy/redis-py#sentinel-support)

### PR DESCRIPTION
**Pull request by arthurTemporim**
Closes #3924
**Proposed changes**:
- Enable the usage of [redis-sentinel](https://redis.io/topics/sentinel)

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by wochinge** [comment]
Hey arthur, how is this going? Are you planning on finishing this up? If not, I'd close the PR for now.

**Comment by arthurTemporim** [comment]
Hi @wochinge I'm great and you?

Sorry but not for now, I had to focus in other things :s so I closed it.

Cheers ;)

**Comment by ErickGiffoni** [comment]
@arthurTemporim hey there... what was it missing to finish this PR ?
Do you or anyone else think it is still available for contributing ?

**Comment by arthurTemporim** [comment]
Hi, @ErickGiffoni , unfortunately I have no plans to reopen this PR, feel free to finalize it in another PR if still make sense 🚀

**Pull request closed without merging**
