### PR TITLE
Fix duckling timestamp parse warning

### PR DESCRIPTION
**Pull request by DraggonFantasy**
**Proposed changes**:
- Don't pass "message_id" as a second parameter to Interpreter class since it expects time to be passed there.
- closes https://github.com/RasaHQ/rasa/issues/4006

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
Thanks for the PR @DraggonFantasy! We'll review it as soon as possible.

**Comment by federicotdn** [comment]
@tabergma The line being modified here was added explicitly in https://github.com/RasaHQ/rasa/pull/3822, but now it appears to be causing trouble because we're using a message ID as `time` for `rasa.nlu.Interpreter.parse()`. Do you know if maybe this was added by mistake?

**Comment by tabergma** [comment]
As mentioned in the respective issue (https://github.com/RasaHQ/rasa/pull/3822) we are passing the `message_id` to `parse` so that it can be passed on to the `RasaNLUHttpInterpreter`. I think this functionality should not be removed.

**Comment by federicotdn** [comment]
I agree that the PR added the ability to specify a `message_id` via the HTTP API. The changes to `RasaNLUHttpInterpreter` and the API spec look OK - but why do we need to specify `message_id` to `rasa.nlu.model.Interpreter.parse()`? It does not accept any message ID as arguments (I am referring to the changes to `RasaNLUInterpreter`)

**Comment by federicotdn** [comment]
More specifically, this:
```diff
-result = self.interpreter.parse(text)
+result = self.interpreter.parse(text, message_id)
```

The problem being that `self.interpeter` is a `rasa.nlu.model.Interpreter`, whose `parse()` method does not take `message_id` as argument (but does take the message text).

**Comment by erohmensing** [comment]
I'm so excited for this to finally be fixed 😄thanks @DraggonFantasy !!

**Pull request merged**
