### PR TITLE
Add entity synonym fuzzy match

### PR DESCRIPTION
**Pull request by odannyc**
**Proposed changes**:
- Add fuzzy matching to `ner_synonyms`

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
Thanks for submitting this PR, we'll give it a review as soon as possible

**Comment by MetcalfeTom** [comment]
Linking this to the original issue: #1626

**Comment by tmbo** [comment]
We can not depend on `fuzzywuzzy ` because as far as I can see it is released under the GPL license, which would require us to relicense NLU under GPL as well

**Comment by MetcalfeTom** [comment]
@odannyc Any chance you could get this working with a library under an `Apache 2.0` license?

**Comment by odannyc** [comment]
@tmbo @MetcalfeTom 

Before I dive too deep into implementing another library, [I found this](https://github.com/aflc/editdistance) which has the MIT license.

Is that fine?

**Comment by odannyc** [comment]
@akelad @MetcalfeTom 

Still waiting on a response for this.


Thanks!

**Comment by akelad** [comment]
@odannyc we appreciate your hard work, but this requires some further discussion from our side. We'll get back to you once we've discussed it and ran some experiments ourselves.

**Comment by odannyc** [comment]
@akelad 

Any news?

**Comment by akelad** [comment]
not yet sorry, we haven't had time to properly look into it yet

**Comment by tmbo** [comment]
What we still need to validate: earlier tests showed that fuzzy matching is quite slow. To avoid introducing a component that can't be used in production, we need to validate whether we can really on the chosen matching library to deliver good performance.

**Comment by tmbo** [comment]
I'll close this for now as it is quite outdated. But happy to reopen if @Ghostvv thinks this makes sense from a entity matching accuricy standpoint.

**Pull request closed without merging**
