### PR TITLE
check if local tracker store is the correct one

### PR DESCRIPTION
**Pull request by wochinge**
**Proposed changes**:
- add assertions to avoid https://github.com/RasaHQ/rasa/issues/3606

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by tmbo** [comment]
mhm, why does it only work with the sqllite tracker store though?

**Comment by wochinge** [comment]
Because we use the SQLite tracker store to "stream" the events to Rasa X.

**Comment by tmbo** [comment]
Ok I see. I think this quickfix works then. But we should really create a proper sqllite eventstream rather than using the trackerstore. I'll create a separate issue for it.

**Comment by tmbo** [comment]
followup issue https://github.com/RasaHQ/rasa/issues/3702

**Pull request merged**
