### PR TITLE
type_name should be nullable=True

### PR DESCRIPTION
**Pull request by tommykoctur**
type_name should be nullable=True because it is not inserted by the tracker. The tracker is inserting only sender_id and data. 
Postgresql tracker is not usable without this change.

**Proposed changes**:
- set type_name as nullable=true or fix postgresql tracker inserts and also table structure. It is quite a mess. :) 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @koaning will take a look at it as soon as possible ✨

**Comment by tommykoctur** [comment]
I meant postgresql event broker not the tracker. I messed up terms :)

**Comment by wochinge** [comment]
@tommykoctur It's a key property of Rasa conversation events that they have a `type`. Events not have a type means that something is wrong. Can you please elaborate on the problem you want to solve with this? Thanks 🙏

**Comment by tommykoctur** [comment]
> @tommykoctur It's a key property of Rasa conversation events that they have a `type`. Events not have a type means that something is wrong. Can you please elaborate on the problem you want to solve with this? Thanks 🙏

It was probably some kind of error happened. Now event_broker table in postgres has only 3 columns. Please cancel this merge request.

**Pull request closed without merging**
