### PR TITLE
ci: Upload diagnostic data as artifact

### PR DESCRIPTION
**Pull request by HotThoughts**
This PR made multiple changes on the schedule version of Model Regression Tests workflow:
- Quote path strings
  When passing dataset/config path to `rasa test core/nlu`, paths with whitespaces will break at whitespace which leads to unexpected results, e.g., not being able to locate stories to test on. 
- Upload diagnostic data to artifact if tests that test `rasa test core`. 
  Resolves https://github.com/RasaHQ/rasa/issues/10730
  
- Skip Slack notifications on github events other than `on schedule`
  We don't want to make noise while testing on PR 🙃

TODOs:
- [x] Remove test lines, specifically, revert 2baed07dacd27885fe0ec0956a9323699a111ce9

### CODE REVIEW

**Comment by HotThoughts** [comment]
@dakshvar22 or @koernerfelicia , could one of you review this PR when you have a minute? 

You can download artifact [here](https://github.com/RasaHQ/rasa/actions/runs/1813356468). It should contains data like this:
```
diagnostic_data/
├── Sara
│   └── Rules + TED
│       ├── failed_test_stories.yml
│       └── story_confusion_matrix.png
└── financial-demo
    └── Rules + TED
        ├── failed_test_stories.yml
        └── story_confusion_matrix.png

```

**Comment by koernerfelicia** [comment]
@HotThoughts this looks good to me, I downloaded the artifact, and I think this is exactly what we wanted! Only thing is that the test lines ([trigger on PR, and run only on some datasets](https://github.com/RasaHQ/rasa/commit/2baed07dacd27885fe0ec0956a9323699a111ce9)) are still in there 🙏

**Comment by HotThoughts** [comment]
@koernerfelicia Thanks 💜 I have reverted the commits that contains test lines.

**Comment by koernerfelicia** [comment]
@HotThoughts hope this is not waiting on me! I approve from my end, dunno if you want Tomasz' okay as well

**Review by tczekajlo — APPROVED** [review]
LGTM

**Pull request merged**
