### PR TITLE
Policy config storage

### PR DESCRIPTION
**Pull request by imLew**
Change the storing of policy configuration parameters.
- fixes https://github.com/RasaHQ/roadmap/issues/403

Just a WIP currently.
So far mainly collected config parameters in the `.config` dictionary and overwrote the `__setattr__` and `__getattr__` methods of the `Policy` class to allow setting and getting these parameters like attributes.

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by akelad** [comment]
@imLew could you please link the associated issue?

**Comment by imLew** [comment]
> @imLew could you please link the associated issue?

it's the one I referenced it in, #403 in the roadmap

**Comment by akelad** [comment]
yeah, please reference that from the description with "fixes #403" or similar

**Comment by wochinge** [comment]
@imLew Is this still a thing or can we close it?

**Comment by imLew** [comment]
@wochinge yes, this is still happening, it's just always been lowest priority 😓

**Pull request closed without merging**
