### PR TITLE
update docs root page

### PR DESCRIPTION
**Pull request by akelad**
change the docs root page to point to 1.10.8, rather than the alpha. ideally this should just pick the latest 1.10.x release but i'm not sure how to make it do that in this conf file. 

Also I'm like 95% sure these are the correct configurations here, but @lunelson is there a way to preview what this is gonna look like before publishing?

### CODE REVIEW

**Comment by degiz** [comment]
@akelad Locally yo can run `poetry run sphinx-versioning build docs . -b dirhtml -A html_theme=rasabaster`

**Comment by akelad** [comment]
yeah i did that but it doesn't show me the versions in the sidebar 🤔

**Comment by akelad** [comment]
i am trying for a second time now

**Comment by degiz** [comment]
DId you check the `./html_theme=rasabaster/index.html` ? I generated the log yesterday and can see the tags on the left side.

**Comment by lunelson** [comment]
@akelad I'm guessing you and @degiz know more about this than I do, I'm not at all familiar with the sphinx build process :grimacing:

**Comment by akelad** [comment]
ahhh @degiz ok yes i think i looked at the wrong index.html 🙃

**Comment by akelad** [comment]
confirmed that it works - landing page is now 1.10.8. This message for 2.0.0a1 is somewhat untrue, but fine imo
image

**Comment by akelad** [comment]
yes good point, will do.

**Pull request merged**
