### PR TITLE
build multiarch docker for amd64 and arm64

### PR DESCRIPTION
**Pull request by tmbo**
**Proposed changes**:
- well, I have no clue if this works. it seems syntactically correct but I don't know if the images will actually build 🤷 CI will be the judge

fixes https://rasahq.atlassian.net/browse/ATO-326

### CODE REVIEW

**Comment by rasa-jmac** [comment]
CI didn't appear to like that, can you build ARM Docker images without the build itself running on ARM?

**Comment by tmbo** [comment]
well alright so i skimmed https://docs.docker.com/desktop/multi-arch/#build-multi-arch-images-with-buildx but now reading it properly it sounds like it works only on windows and macos? 🤔 bold choice

**Comment by tmbo** [comment]
well, was worth a shot 😂

**Comment by tmbo** [comment]
i'll give this a try https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54

**Comment by tmbo** [comment]
@rasa-jmac this does seem to run successfully now. it is using qemu to emulate the arch (which is the recommended way). I'd like to test the images. easiest is probably to merge and then use the build images? if it goes wrong we can still revert

**Comment by rasa-jmac** [comment]
Looks good to me but I want to make sure @virtualroot is aware of it in case it impacts his ongoing work.

**Review by rasa-jmac — APPROVED** [review]

**Comment by tmbo** [comment]
oh you mean in terms of automatically updating the containers? that is a good point not sure if @virtualroot restructured the files or the workflows. in either case, this is quite a straightforward change (you need to supply the architecture when calling `buildx`). where are the changes you've been working on?

**Pull request merged**
