### PR TITLE
Dialogflow Import Fix for Issue 6137

### PR DESCRIPTION
**Pull request by A-A-R0N**
**Proposed changes**:
- Fixed passing the wrong value to  `get_nlu_data` during training 

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

- This is a fix for existing functionality which I tested against several dialogflow models.
- No documentation are updates. The steps in current documentation work as expected now.

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @melindaloubser1 will take a look at it as soon as possible ✨

**Comment by melindaloubser1** [comment]
Thanks for the PR! I don't have a dialogue bot to test this with, but what happens now if the language is not defined in the config or on import? It still throws an error right?

**Comment by A-A-R0N** [comment]
@melindaloubser1 I recreated this as PR 6188. This way I don't have to worry about any previous merge conflicts that have already been resolved.

**Comment by melindaloubser1** [comment]
Sure, that makes sense

**Pull request closed without merging**
