### PR TITLE
Load partial ensemble

### PR DESCRIPTION
**Pull request by pheel**
Fixes https://github.com/RasaHQ/rasa/issues/7303.

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @joejuzl will take a look at it as soon as possible ✨

**Comment by pheel** [comment]
Currently fails at **test_policy_loading_load_returns_none**. Do you think this approach is appropriate to handle train/load incongruity described in https://github.com/RasaHQ/rasa/issues/7303, or is it better to make training fail instead? Personally I think it's weird that a lack of stories should make training of an ML fail.

**Comment by joejuzl** [comment]
This looks sensible to me. 
I think it should be ok to update `test_policy_loading_load_returns_none` to match the new expected behaviour.

**Comment by pheel** [comment]
@joejuzl Just updated test!

**Review by joejuzl — APPROVED** [review]
Looks good! Thanks for this 👍

**Comment by pheel** [comment]
Pinging @joejuzl in case...

**Pull request merged**
