### PR TITLE
Updated Slack Connector for new Events API

### PR DESCRIPTION
**Pull request by b-quachtran**
**Proposed changes**:
- Updated Slack Connector for new Events API format documented [here](https://api.slack.com/changelog/2020-09-15-events-api-truncate-authed-users#what)

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by anuragdtnomy** [comment]
Slack : Bot doesnt respond at all : "TypeError: 'NoneType' object is not iterable". trace =>line 203, in _sanitize_user_message , for uid_to_remove in uids_to_remove: #6895

**Review by rgstephens — APPROVED** [review]

**Comment by erohmensing** [comment]
@b-quachtran should we port this to 2.0.x?

**Comment by b-quachtran** [comment]
@erohmensing Yep, I'm on it, it shouldn't be too much effort from this PR

**Comment by gauravbgh** [comment]
any update?

**Pull request merged**
