### PR TITLE
Fix the bug of Chinese tokenization for rasa2.0.0rc1

### PR DESCRIPTION
**Pull request by HatuneMiku**
**Proposed changes**:
- Fix the bug of Chinese tokenization for rasa2.0.0rc1.   use rasa 1.9.x token logic which works fine.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by HatuneMiku** [comment]
fix #6752

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @degiz will take a look at it as soon as possible ✨

**Comment by tabergma** [comment]
@HatuneMiku I don't think we want to bring back the old logic as this is the first step in the direction of getting rid of the library specific tokenizers which is planned for the future. Also reading the discussion in https://github.com/RasaHQ/rasa/issues/6752 it seems like there is another solution to the problem. Do you agree?

**Comment by HatuneMiku** [comment]
@tabergma Ok, let me check. I will close this one.

**Pull request closed without merging**
