### PR TITLE
Docker: Suggest mounting /tmp as tmpfs

### PR DESCRIPTION
**Pull request by orgads**
Without this, rasa leaves behind tons of temp files when it unpacks the models.

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @amn41 will take a look at it as soon as possible ✨

**Review by tczekajlo — CHANGES_REQUESTED** [review]
@orgads Thanks a lot for the changes 😄  I left one comment. Additionally, the model unpacking issue shouldn’t happen as of 1.10.15 or 2.0.0:  https://github.com/RasaHQ/rasa/pull/6925

@erohmensing I have doubts if we should suggest something that has platform limitations. Especially, if the issue unpacking the model is fixed. 

What do you think?

**Comment by tczekajlo** [comment]
@erohmensing Taking intro account the platform limitation on which `tmpfs` can be used and the fact that the issue with unpacking the model is fixed I'm gonna drop the PR.  

@orgads Thank you a lot for your PR, and I'm looking forward to seeing your next PRs 😄  🙌

**Comment by orgads** [comment]
Yes, the issue seems to be fixed. Thank you.

**Pull request closed without merging**
