### PR TITLE
Added Dockerfile to pretrained spacy using pt-BR

### PR DESCRIPTION
**Pull request by lluchini**
Dockerfile_pretrained_embeddings_spacy_pt

**Proposed changes**:
- Added Dockerfile to pretrained spacy using pt-BR

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by lluchini** [comment]
The lint is accusing an error that wasn't related to my addition and does not happen on my lint execution.

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @degiz will take a look at it as soon as possible ✨

**Comment by lluchini** [comment]
I just don't know how to add a new tag to Docker hub...

Here: https://hub.docker.com/r/rasa/rasa/tags

**Comment by degiz** [comment]
Hey @lluchini 

We're limiting the out-of-the-box set (in this case Dockerfile) only to the english at the moment. 
You can though for sure upload/tag/use your own docker image to the registry!

**Comment by lluchini** [comment]
Hello @degiz ,

> We're limiting the out-of-the-box set (in this case Dockerfile) only to the English at the moment.

Does this mean that I should cancel this PR?

> You can though for sure upload/tag/use your own docker image to the registry!

I'm not sure what this means or how to do it, can you provide some material about the subject so I can read/learn how to do this?

Thanks!

**Comment by degiz** [comment]
Hey @lluchini 

> Does this mean that I should cancel this PR?

Yep, just close it.

> read/learn how to do this?

I think the best place to start is the Docker official [docs](https://docs.docker.com/docker-hub/repos/).

**Pull request closed without merging**
