### PR TITLE
fix: Update ConveRT model URL

### PR DESCRIPTION
**Pull request by connorbrinton**
**Proposed changes**:
- PolyAI recently updated the URL at which the ConveRT TensorFlow Hub model is hosted. These changes modify Rasa to load the ConveRT model from the new, updated URL.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by connorbrinton** [comment]
Closing in favor of #6743, which also adds support for run-time URL configuration

**Comment by dakshvar22** [comment]
@connorbrinton Sorry this clashed with the other PR. But thanks a lot for bringing this to our notice. Looking forward to more contributions from your side. 🚀

**Comment by tatianafrank** [comment]
when will this fix be released? This broke our production model

**Comment by dakshvar22** [comment]
@tatianafrank The fix was merged here in latest master - https://github.com/RasaHQ/rasa/pull/6743

**Comment by tatianafrank** [comment]
> @tatianafrank The fix was merged here in latest master - #6743

Yes but we don't host the source code so we need it in a release unfortunately. Can you guys release 1.10.14 tomorrow, please?

**Comment by tatianafrank** [comment]
We use Poetry to manage the Rasa package and it's dependencies.

**Comment by dakshvar22** [comment]
@tatianafrank A new version with the fix was released - https://github.com/RasaHQ/rasa/releases/tag/1.10.14

**Comment by tatianafrank** [comment]
Thank you!! @dakshvar22

**Pull request closed without merging**
