### PR TITLE
Incomplete set of modifications for replacing os.path to pathlib in nlu module

### PR DESCRIPTION
**Pull request by icaropires**
**Proposed changes**:
- The idea was to do as asked in  #3153 but this is not finished. I'm just sharing a part of the solution.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by akelad** [comment]
thanks @icaropires for submitting this PR - would you like us to give some feedback on this already? Asking bc it's still a draft PR

**Comment by icaropires** [comment]
@akelad it's not ready for review. But thanks.

**Comment by tmbo** [comment]
@icaropires how are things going? any progress on this one?

**Comment by icaropires** [comment]
> @icaropires how are things going? any progress on this one?

@tmbo I've been really busy for this month, so I opened this draft to show my progress as a reference if anyone would want to continue it. If nobody completes the issue until I have time I'll be glad to keep working on it but no problem if someone completes it.

**Pull request closed without merging**
