### PR TITLE
reduce tensorflow deprecation warnings

### PR DESCRIPTION
**Pull request by wochinge**
**Proposed changes**:
- reduce tensorflow deprecation warnings
- remove unused imports

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by wochinge** [comment]
@dakshvar22 Maybe you have some ideas how to suppress the other deprecation warnings? I tried this stuff https://github.com/RasaHQ/rasa-x/issues/1276#issuecomment-534335270

**Comment by dakshvar22** [comment]
@wochinge I think this is a [better solution](https://github.com/tensorflow/tensorflow/issues/27023#issuecomment-523710266) given that we bumped up to TF `1.14.0` now. It needs to be placed before the first `tensorflow` import. So, the best place for it would be in `rasa/__init__.py`, but would it be ideal to put it there?

**Comment by Saladdin** [comment]
@dakshvar22 should this go with the release?

**Comment by wochinge** [comment]
Mhm, having this in `__init__.py`  does not feel ideal since I'd like to have it configurable. But thanks for the solution! that definitely works!

**Comment by wochinge** [comment]
i'm trying to figure out where the import happens

**Comment by tmbo** [comment]
@wochinge are we ready to merge this?

**Pull request merged**
