### PR TITLE
Revert "remove end-to-end reading yaml"

### PR DESCRIPTION
**Pull request by wochinge**
**Proposed changes**:
- re-add end-to-end importer so that NLU training receives the necessary action names
- don't re-add the actual reading of end-to-end stories as this is not supposed to be supported yet

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by Ghostvv — APPROVED** [review]
I guess this is the same code?

**Comment by wochinge** [comment]
@evgeniiaraz Can you let me know when `new_core_featurization` passes so that I can then run the tests here, and merge? At the moment everything is breaking.

**Comment by wochinge** [comment]
Or should I just merge? However, then it's on you to ping me if things break 🙈

**Comment by evgeniiaraz** [comment]
@wochinge let's give it 5 mins, one of the commits (which I expect to fix things) shouls be done in 5. if it doesn't pass then, I'd just merge it. 
I'll give you a heads up once it's done

**Comment by evgeniiaraz** [comment]
@wochinge So, I think now all the test code tests should work, while the type checks fail (I have an idea of where it's coming from). Though -- I don't know if we should wait for all the tests to finish because github seems to have a bit of a hard time with tests.

**Pull request merged**
