### PR TITLE
fixed radom state in splitting and train

### PR DESCRIPTION
**Pull request by kohn1001**
**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by erohmensing** [comment]
@kohn1001 is this in a reviewable state? Looks like there are merge conflicts. Can you also add a description of the problem you encountered and are trying to solve?

**Comment by kohn1001** [comment]
Yeah - I see that you add the functionality I needed - fix the random seed for every train/test split

**Comment by kohn1001** [comment]
This PR has been merged and doing what I need :) 
https://github.com/RasaHQ/rasa/pull/4842

**Comment by erohmensing** [comment]
Awesome, I will close this then 🙂

**Pull request closed without merging**
