### PR TITLE
Fix bug in docs - set augmentation default to 20 as it is actually set to 20 in all other places

### PR DESCRIPTION
**Pull request by RolandJAAI**
**Proposed changes**:
- data augmentation default is set to 20 everywhere but the docs still say it was 50 ;)

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by akelad** [comment]
@RolandJAAI thanks for submitting this, but you've edited the cli defaults from 50 to 20, so actually the default was 50?

**Comment by RolandJAAI** [comment]
Hi @akelad, yes, the default used to be 50 but obviously was changed to 20 everywhere else, also the [policies doc](https://github.com/RasaHQ/rasa/blob/master/docs/core/policies.rst) says it was 20 and also if you search for agumentation in the repo you will find many places where the default is now set to 20, so this should be made consistent in one way or the other. I liked 50 better btw ;)

**Comment by akelad** [comment]
good point, @Ghostvv any thoughts on default values for augmentation factor?

**Comment by Ghostvv** [comment]
@RolandJAAI good catch! Thank you very much. Let's go with `50` since effectively it was `50` because of `cli` and since you like it better

**Comment by akelad** [comment]
@RolandJAAI would you be up for changing it to 50 everywhere then?

**Comment by RolandJAAI** [comment]
@akelad Done. ;)
I left the fixed values for tests and example bots where they are and set everything else to 50.

**Comment by akelad** [comment]
thanks! we'll get that reviewed for you soon

**Pull request merged**
