### PR TITLE
Fixing a typo in docs for rasa-sdk

### PR DESCRIPTION
**Pull request by nicht**
**Proposed changes**:
- Fixing a typo in docs section of rasa-sdk

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by nicht** [comment]
> Thanks for your first PR @nicht! Appreciate you putting the time in to improve our docs  once you sign the CLA and the tests pass, we can merge!

Hey, @erohmensing the CLA is now signed!

**Comment by erohmensing** [comment]
@nicht sorry about this, looks like your branch got out-of-date (we update master a lot 😅). Can you pull the latest master into your fork? Another option would be to give others (in general, or me) write access so that we are allowed to update the branch so I can get this commit in even if the base branch changes. 🙂

**Comment by nicht** [comment]
Hey, thanks for the reply! I updated the branch. Hope it all good now.

**Comment by nicht** [comment]
@erohmensing guess it's everything good to go now!

**Comment by erohmensing** [comment]
@nicht I'm so sorry its out of date 😂blame my colleague who pushed 5 mintues ago 🙄try one more time, I will keep a watch on it and push it in as soon as it's green!

**Comment by erohmensing** [comment]
Thanks @akelad. And thanks for contributing to Rasa, @nicht! 🎉

**Pull request merged**
