### PR TITLE
Fix non expressive variable name on `interactive.py`

### PR DESCRIPTION
**Pull request by rafaelteodosio**
**Proposed changes**:
- Change variable named `i` to `interactive_story_counter`
- Resolve: [#8453](https://github.com/RasaHQ/rasa/issues/8453)
**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @samsucik will take a look at it as soon as possible ✨

**Review by samsucik — CHANGES_REQUESTED** [review]
Thanks @rafaelteodosio! Before we merge this into `main`, could you remove the changelog entry? The changelog is meant for bigger changes, especially ones that affect users 🙂

**Comment by rafaelteodosio** [comment]
> Thanks @rafaelteodosio! Before we merge this into `main`, could you remove the changelog entry? The changelog is meant for bigger changes, especially ones that affect users 🙂

Ok @samsucik I made the requested change. Thanks.

**Review by samsucik — APPROVED** [review]
Great, thanks for the improvement @rafaelteodosio!

**Pull request merged**
