### PR TITLE
Upgrade poetry to 1.1.11

### PR DESCRIPTION
**Pull request by tayfun**
Fixes https://github.com/RasaHQ/rasa/issues/10708

We noticed some developer environments had problems with earlier Poetry
and also some community pull requests failed. Error such as:

```
ERROR: Could not install packages due to an OSError: [WinError 2] The
system cannot find the file specified:
'd:\\a\\rasa\\rasa\\.venv\\Lib\\site-packages\\nr\\__init__.py'
```

and

`'Link' object has no attribute 'is_absolute'`

**Proposed changes**:
- Upgrade poetry to 1.1.11

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by HotThoughts** [comment]
All the tests were [skipped](https://github.com/RasaHQ/rasa/runs/4922123536?check_suite_focus=true), so I added a label to trigger them all.

**Comment by HotThoughts** [comment]
Maybe also update Poetry version in [docker](https://github.com/RasaHQ/rasa/blob/36cfeee23bc6b511efd79cd00837f9dc4cd6e787/docker/docker-bake.hcl#L23-L25)? Just to keep the version is the same in docker and in the CI.

A quick question. Do we usually update `poetry.lock` when upgrading poetry? If so, we can run `poetry lock`.

**Comment by tayfun** [comment]
> Maybe also update Poetry version in [docker](https://github.com/RasaHQ/rasa/blob/36cfeee23bc6b511efd79cd00837f9dc4cd6e787/docker/docker-bake.hcl#L23-L25)? Just to keep the same version everywhere.
> 
> A quick question. Do we usually update `poetry.lock` when upgrading poetry? If so, we can run `poetry lock`.

Good catch on docker, updated it now. For lock file it is not strictly needed but done that as well.

**Review by HotThoughts — APPROVED** [review]
🚀 Thank you. This PR is ready to go.

**Pull request merged**
