### PR TITLE
Updating choosing_a_pipeline file

### PR DESCRIPTION
**Pull request by DeathReaper0965**
**Proposed changes**:
- The "template" and "Component Configuration" are both mentioned the same, though the Yaml file for the "template" was already created which is different from "Component Configuration" in the `pretrained_embeddings_convert` pipeline.

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by DeathReaper0965** [comment]
The error says as "Bad credentials". I think there's some credentials issue, can you please check for that as this is just a small documentation change.

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @tabergma will take a look at it as soon as possible ✨

**Comment by DeathReaper0965** [comment]
> 💯 Thanks for spotting and fixing this!

It's my pleasure. 

Also, even though there's no issue in code runs, the "mergepal-merge" still fails with error as "Bad Credentials", @tabergma could you please check on this?

**Comment by tabergma** [comment]
@DeathReaper0965 Sorry for the late reply, I was offline the last two weeks. The checks are now all passing. However, we got a merge conflict. Can you please resolve the merge conflict? Once that is done, I'll merge the PR. Thanks again for the contribution.

**Comment by tabergma** [comment]
@DeathReaper0965 Sorry, did not checked what changed. Yes, the file got removed. We just show the detailed config with the all the components now. I think that is sufficient. So, I guess we can close this PR. However, thanks again for taking care of this!

**Pull request closed without merging**
