### PR TITLE
Allow policies to get nlu training data

### PR DESCRIPTION
**Pull request by tmbo**
**Proposed changes**:
- expose nlu training data through variable needs generation

### CODE REVIEW

**Review by twerkmeister — APPROVED** [review]
looks consistent 👍. If I understand correctly, nlu components still get their training data from the previously run node, and any policy components get it straight for the data provider.

**Comment by tmbo** [comment]
yes exactly - in a sense it falls back to providing the `training_data` argument using `nlu_training_data_provider`, if there is a previous node thing it does that :+1:

**Comment by tmbo** [comment]
I'll merge this without all flaky tests passing - the tlaky tests passed on one os so will take a bet merging into main. will do release anyways which will highlight if things go wrong.

**Comment by tmbo** [comment]
image

**Pull request merged**
