### PR TITLE
ci(chore): Update tf-cuda config for TF 2.7

### PR DESCRIPTION
**Pull request by HotThoughts**
**Proposed changes**:

According to the [TF CUDA compatibility matrix](https://www.tensorflow.org/install/source#gpu), TF 2.7 still use CUDA 11.2 and cuDNN 8.1. 

TODO:
- [X] Add a step to make sure the tf-cuda config is updated with TF upgrades.
 [Example run](https://github.com/RasaHQ/rasa/runs/5359611384?check_suite_focus=true#step:6:10) ✅ 
image

### CODE REVIEW

**Comment by HotThoughts** [comment]
/modeltest
```yaml
include:
 - dataset: ["Carbon Bot"]
   config: ["Sparse + DIET(bow) + ResponseSelector(bow)"]
```

**Comment by HotThoughts** [comment]
Please ignore all above ☝🏻 . I was trying to test it out by running the model regression test on GPU runner. However, the branch `3.0.x` has not upgraded to TF `2.7`.
😛 Only The `main` branch had.

**Comment by HotThoughts** [comment]
/modeltest
```yaml
include:
 - dataset: ["Carbon Bot"]
   config: ["Sparse + DIET(bow) + ResponseSelector(bow)"]
```

**Review by tczekajlo — APPROVED** [review]
LGTM

**Review by virtualroot — APPROVED** [review]

**Pull request merged**
