### PR TITLE
Restart the tracker even if it is paused

### PR DESCRIPTION
**Pull request by psds01**
**Proposed changes**:
- Resolves https://github.com/RasaHQ/rasa/issues/4107

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by msamogh** [comment]
Thanks for the PR, we'll give it a review as soon as possible. In the meantime, please sign the Contributor License Agreement.

**Comment by akelad** [comment]
@imLew @MetcalfeTom wait a sec - did `/restart` not work at all since the addition of the mapping policy? I thought we had added the mapping of `/restart` to action_restart when merging that

**Comment by psds01** [comment]
@akelad  you want me to answer that?

**Comment by akelad** [comment]
sure :D i'm fairly certain `/restart` currently works though?

**Comment by psds01** [comment]
Thanks,

Consider only the MappingPolicy. 

The original issue is : `/restart` doesn't work if the tracker state is `paused`.
This is because the policy maps an intent to an action only if `tracker.latest_action_name == ACTION_LISTEN_NAME`.

But in case where the tracker is `paused`, the `tracker.latest_action_name` is `ConversationPaused` event and not `action_listen` so none of the first two `if`s are true.

**Comment by imLew** [comment]
@akelad yes it work, but as @psds01 just said it only predicts if the previous action is action_listen
what behaviour do we want in case the tracker is paused?

**Comment by imLew** [comment]
Hey @psds01 , I had to think about it a bit but your change is exactly what was needed here, thank you! :D
Would you mind quickly documenting it in the changelog?

**Pull request merged**
