### PR TITLE
Use labels for response selector training

### PR DESCRIPTION
**Pull request by dakshvar22**
**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by dakshvar22** [comment]
/modeltest

```
include:
 - dataset: ["Carbon Bot", "Sara"]
   config: ["all"]
```

**Comment by tmbo** [comment]
I think I touched this as part of #6323 as well

**Comment by dakshvar22** [comment]
@tmbo Right, I see it [here](https://github.com/RasaHQ/rasa/pull/6323/files#diff-0e775499654bc8adf9290d502dac3c0dR245-R253). This is just a quick experiment that we are trying to see if we can completely get rid of the distinction between usual utter templates and response templates. Would also solve the multiple response training problem if successful.

**Comment by tmbo** [comment]
@dakshvar22 is this still relevant?

**Pull request closed without merging**
