### PR TITLE
Update nlu.yaml

### PR DESCRIPTION
**Pull request by abdullahnaseem**
Removed `"value": "mexican"` from `Mexican` cuisine Entity the default value given did not match the cuisine name in the `knowledge_base_data.json` and was causing issues in the trained model.
The trained model would recognize the Entity ``Mexican`` but use the provided value that was ``mexican`` and then the action ``action_query_knowledge_base`` would ``utter_ask_rephrase`` because of the lowercase value and the uppercase value in the `knowledge_base_data.json` file.

**Proposed changes**:
- Remove the given value for Mexican in the Training Data

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @erohmensing will take a look at it as soon as possible ✨

**Review by erohmensing — APPROVED** [review]
Appreciate the update and the thorough description! Congrats on your first contribution 🚀

**Comment by abdullahnaseem** [comment]
Any idea why the bot Could not update branch? Do I need to do something?

**Comment by erohmensing** [comment]
Looks like there is a merge conflict, can you try merging master into your branch locally and resolving the conflicts?

**Comment by wj-Mcat** [comment]
@abdullahnaseem you can resolve it by hand in bottom of this page

**Comment by abdullahnaseem** [comment]
Its says 'these conflicts are too complex to resolve in the web editor'

**Comment by erohmensing** [comment]
Yes, you'll have to check out your branch, run a `git merge origin master`, and resolve the conflicts.

**Pull request closed without merging**
