### PR TITLE
Facebook Quick Reply bug Fix  + Add supports for persistent menu

### PR DESCRIPTION
**Pull request by RogersNtr**
**Proposed changes**:
- Facebook Quick Reply bug Fix
- Add supports for persistent menu using 'custom'

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)

### CODE REVIEW

**Comment by tmbo** [comment]
Hey @RogersNtr thanks a lot for this contribution :+1: 

Before we can continue, we need to make sure we don't run into any licensing issues. I saw that you signed the CLA, but your commits are not associated to your github account. I guess that is because your local git isn't set up properly. Can you please run the following 
```
git config --global user.email "email@example.com"
```
locally setting your email properly? After that, please rebase your commits, e.g. using 
`git rebase -i HEAD~5` from your branch.

**Comment by RogersNtr** [comment]
Hey @tmbo 
Thanks for the feedback. I just did this : 
git config --global user.email "r.nengwe@yahoo.fr"
git rebase -i  HEAD

What shoul I do next ? 
Thanks.

**Comment by tmbo** [comment]
well, this didn't work - the diff contains a lot of changes you didn't commit. I think it would be easiest for you if you make the git config change I posted, create a new clean branch and recommit your changes

**Comment by erohmensing** [comment]
@RogersNtr since I had asked you to create separate PRs for the bug fix and the enhancement, I've went ahead and created a new PR to fix the bug (https://github.com/RasaHQ/rasa/pull/3791) as it was critical to testing another bug fix. Feel free to create a new PR for your enhancement via @tmbo's instructions, though.

**Pull request closed without merging**
