### PR TITLE
disable searchbox shortcut in docs

### PR DESCRIPTION
**Pull request by m-vdb**
**Proposed changes**:
- Temporarily disable search box shortcuts

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by erohmensing — APPROVED** [review]
Looks good to me, I wish we could change `Search` to sth like `Search (coming soon)` but that doesn't live in the style so not sure there's a workaround way to implement that, and i don't think we should spend too much time on it

**Comment by m-vdb** [comment]
@erohmensing it might be possible with css, let me see 🏃‍♂️

**Comment by m-vdb** [comment]
made it work @erohmensing . so dirty

**Comment by erohmensing** [comment]
Amazing 🙌

**Pull request merged**
