### PR TITLE
Changed duckling extractor to return entity values as string

### PR DESCRIPTION
**Pull request by davidezanella**
Signed-off-by: Davide <davide.zanella10@gmail.com>

**Proposed changes**:
- let duckling return always string values, in order to allow entities extracted by it to be tested. With the actual rasa version in the following part of the test story, the entities cannot be tested correctly beacuse of the different types of the values:
```
* start_cooking: let's cook the [second]{"entity": "ordinal", "value": "2"} [one]{"entity": "number", "value": "1"}   <!-- predicted: start_cooking: let's cook the [second]{"entity": "ordinal", "value": 2} [one]{"entity": "number", "value": 1} -->
```
With the changes made, all the values are returned as a string and can be tested in the `conversation_tests.md` file, otherwise, they are reported as wrong predictions while testing.

**Status (please check what you already did)**:
- [x] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @tttthomasssss will take a look at it as soon as possible ✨

**Comment by davidezanella** [comment]
@tabergma, can you please review my pr?

**Comment by tabergma** [comment]
@davidezanella Thanks for submitting the PR. The changes look good, but I am not quite sure if I understand the problem? During our evaluation we don't compare the actual values. So why is this needed? You mentioned something about an `conversation_tests.md` file. Do you have your own evaluation that is failing due to this?

**Comment by davidezanella** [comment]
@tabergma While developing my project with rasa, I've written some tests story for my assistant in the `conversation_tests.md` file. Originally, duckling returns integer values with the ordinal and cardinal categories but they fail the tests in the test story because the entities extracted must be string while the predicted ones are integers. So with my own tests, using duckling the assistant cannot be tested correctly because of these different data types.

**Comment by tabergma** [comment]
@davidezanella Thanks for the quick response. Can you maybe convert the values into strings inside of your tests itself? I would hesitate to modify our code if it only affects your tests as the code is working and changing it would affect quite a lot of people.

**Comment by davidezanella** [comment]
@tabergma No, I cannot change the value into strings, I rewrite the example and try to explain it better.
```
* start_cooking: let's cook the [second]{"entity": "ordinal", "value": "2"} [one]{"entity": "number", "value": "1"}   
<!-- predicted: start_cooking: let's cook the [second]{"entity": "ordinal", "value": 2} [one]{"entity": "number", "value": 1} -->
```
The first row is a test that I've written, the type of the value is a string because is the only type accepted by rasa and otherwise it will raise an exception.
The second row is the predicted entities and intent by my model and their value, since coming from duckling are of type integer. With the changes made in this pr the predicted values will be strings as well and the test succeeds.

**Comment by tabergma** [comment]
Just to be sure, did you write the test on your own or are we talking about the end-to-end test?

**Comment by davidezanella** [comment]
I just wrote the not predicted part, which is a part of a story in the end-to-end format inside the `tests/conversation_test.md` file, that I tested using the `rasa test` command.

**Comment by tabergma** [comment]
Ah ok, sorry about that. That was a misunderstanding on my side. So I just checked with a colleague and we both agree that we should not change the type of the duckling output. 

If I understand the problem correctly, Rasa is reading all entity values of your `conversation_test.md` as strings. So something like 
```
let's cook the [second]{"entity": "ordinal", "value": 2} [one]{"entity": "number", "value": 1}
```
becomes actually
```
let's cook the [second]{"entity": "ordinal", "value": "2"} [one]{"entity": "number", "value": "1"}
```
Is that correct? If that is the case, then I guess a better way of fixing this would be to update the reading process. What do you think?

**Comment by davidezanella** [comment]
Yes, what you said and the example you reported are correct. Actually, I didn't get  what you mean with the "reading process". Anyway, if you're aware of the impact of this change on the slots type and functionality, I've already tested it and it seems to work as before, so when accessing the ordinal and cardinal slots from an action their value is numeric as should be even if duckling now returns strings.

**Comment by tabergma** [comment]
@davidezanella Thanks for the input. Before we merge this change, I would like to test it myself, just to be sure that it does not have any impact. Can you maybe share your assistant, so that I can use that for testing? Thanks.

**Comment by davidezanella** [comment]
Sure, I'm sending you an email with the code zipped

**Comment by tabergma** [comment]
Thanks for sharing your code! That helped debugging the problem.

I think I found another way to fix this: We can convert the duckling values to string just for the evaluation itself. When evaluating the e2e stories the entity values coming from duckling are converted into strings. That should fix the issue you have. However, we don't modify the duckling extractor itself, so there should be no effect for other users relying on it. 

The fix is currently on the branch `e2e-testing` (see https://github.com/RasaHQ/rasa/compare/e2e-testing). My suggestion: We close this PR and I will create a new PR with my changes referencing this one. How does that sound?

**Comment by davidezanella** [comment]
It sounds good, thanks!

**Pull request closed without merging**
